node {
   stage('init') {
      checkout scm
   }
   stage('build') {
      sh '''
         mvn clean package -DskipTests=true
         cd target
         cp ../src/main/resources/web.config web.config
         cp isf-rest-server-java-1.0.3.war app.war 
         zip todo.zip app.war web.config
      '''
   }
   stage('deploy') {
      azureWebAppPublish azureCredentialsId: env.AZURE_CRED_ID,
      resourceGroup: env.RES_GROUP, appName: env.WEB_APP, filePath: "**/todo.zip"
   }
}