package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BehaviourDetails generated by hbm2java
 */
@Entity
@Table(name = "behaviourDetails", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "SH_Out_Folder"))
public class BehaviourDetails implements java.io.Serializable {

	private int idbehaviourDetails;
	private int idShTasks;
	private String shBehaviourDetailsName;
	private String shTasksname;
	private String shOutFolder;
	private String shActionName;
	private String shClass;
	private String shValidation;
	private String shType;
	private String shInitiator;
	private String shDetails;
	private Date shDeployedAt;
	private String shBehaviourDetailsStatus;
	private String shManualTime;
	private String shShtime;
	private String shSpoc;
	private String shProject;
	private String shRegion;
	private String shDeveloper;
	private String shCategory;
	private String shTimeBookingAvailable;
	private String shUseFrequency;
	private Integer shUserCount;
	private String shNdxactivity;
	private String shNdxsubActivity;
	private String shDomain;
	private String shJarName;
	private String shBotfor;
	private String shParallelWoexecution;
	private String shSubactivityId;
	private String shRparequestId;
	private String shProjectName;
	private String shCodeReuseFactor;
	private String shLineOfCode;
	private String shUatstatus;
	private String shUatowner;
	private Date shUatcompletionDate;

	public BehaviourDetails() {
	}

	public BehaviourDetails(int idbehaviourDetails, int idShTasks, String shBehaviourDetailsName, String shTasksname,
			String shOutFolder, String shClass, String shValidation, String shType, String shBehaviourDetailsStatus) {
		this.idbehaviourDetails = idbehaviourDetails;
		this.idShTasks = idShTasks;
		this.shBehaviourDetailsName = shBehaviourDetailsName;
		this.shTasksname = shTasksname;
		this.shOutFolder = shOutFolder;
		this.shClass = shClass;
		this.shValidation = shValidation;
		this.shType = shType;
		this.shBehaviourDetailsStatus = shBehaviourDetailsStatus;
	}

	public BehaviourDetails(int idbehaviourDetails, int idShTasks, String shBehaviourDetailsName, String shTasksname,
			String shOutFolder, String shActionName, String shClass, String shValidation, String shType,
			String shInitiator, String shDetails, Date shDeployedAt, String shBehaviourDetailsStatus,
			String shManualTime, String shShtime, String shSpoc, String shProject, String shRegion, String shDeveloper,
			String shCategory, String shTimeBookingAvailable, String shUseFrequency, Integer shUserCount,
			String shNdxactivity, String shNdxsubActivity, String shDomain, String shJarName, String shBotfor,
			String shParallelWoexecution, String shSubactivityId, String shRparequestId, String shProjectName,
			String shCodeReuseFactor, String shLineOfCode, String shUatstatus, String shUatowner,
			Date shUatcompletionDate) {
		this.idbehaviourDetails = idbehaviourDetails;
		this.idShTasks = idShTasks;
		this.shBehaviourDetailsName = shBehaviourDetailsName;
		this.shTasksname = shTasksname;
		this.shOutFolder = shOutFolder;
		this.shActionName = shActionName;
		this.shClass = shClass;
		this.shValidation = shValidation;
		this.shType = shType;
		this.shInitiator = shInitiator;
		this.shDetails = shDetails;
		this.shDeployedAt = shDeployedAt;
		this.shBehaviourDetailsStatus = shBehaviourDetailsStatus;
		this.shManualTime = shManualTime;
		this.shShtime = shShtime;
		this.shSpoc = shSpoc;
		this.shProject = shProject;
		this.shRegion = shRegion;
		this.shDeveloper = shDeveloper;
		this.shCategory = shCategory;
		this.shTimeBookingAvailable = shTimeBookingAvailable;
		this.shUseFrequency = shUseFrequency;
		this.shUserCount = shUserCount;
		this.shNdxactivity = shNdxactivity;
		this.shNdxsubActivity = shNdxsubActivity;
		this.shDomain = shDomain;
		this.shJarName = shJarName;
		this.shBotfor = shBotfor;
		this.shParallelWoexecution = shParallelWoexecution;
		this.shSubactivityId = shSubactivityId;
		this.shRparequestId = shRparequestId;
		this.shProjectName = shProjectName;
		this.shCodeReuseFactor = shCodeReuseFactor;
		this.shLineOfCode = shLineOfCode;
		this.shUatstatus = shUatstatus;
		this.shUatowner = shUatowner;
		this.shUatcompletionDate = shUatcompletionDate;
	}

	@Id

	@Column(name = "idbehaviourDetails", unique = true, nullable = false)
	public int getIdbehaviourDetails() {
		return this.idbehaviourDetails;
	}

	public void setIdbehaviourDetails(int idbehaviourDetails) {
		this.idbehaviourDetails = idbehaviourDetails;
	}

	@Column(name = "idSH_Tasks", nullable = false)
	public int getIdShTasks() {
		return this.idShTasks;
	}

	public void setIdShTasks(int idShTasks) {
		this.idShTasks = idShTasks;
	}

	@Column(name = "SH_behaviourDetailsName", nullable = false, length = 350)
	public String getShBehaviourDetailsName() {
		return this.shBehaviourDetailsName;
	}

	public void setShBehaviourDetailsName(String shBehaviourDetailsName) {
		this.shBehaviourDetailsName = shBehaviourDetailsName;
	}

	@Column(name = "SH_Tasksname", nullable = false, length = 100)
	public String getShTasksname() {
		return this.shTasksname;
	}

	public void setShTasksname(String shTasksname) {
		this.shTasksname = shTasksname;
	}

	@Column(name = "SH_Out_Folder", unique = true, nullable = false, length = 100)
	public String getShOutFolder() {
		return this.shOutFolder;
	}

	public void setShOutFolder(String shOutFolder) {
		this.shOutFolder = shOutFolder;
	}

	@Column(name = "SH_Action_Name", length = 100)
	public String getShActionName() {
		return this.shActionName;
	}

	public void setShActionName(String shActionName) {
		this.shActionName = shActionName;
	}

	@Column(name = "SH_Class", nullable = false, length = 400)
	public String getShClass() {
		return this.shClass;
	}

	public void setShClass(String shClass) {
		this.shClass = shClass;
	}

	@Column(name = "SH_Validation", nullable = false, length = 3)
	public String getShValidation() {
		return this.shValidation;
	}

	public void setShValidation(String shValidation) {
		this.shValidation = shValidation;
	}

	@Column(name = "SH_Type", nullable = false, length = 7)
	public String getShType() {
		return this.shType;
	}

	public void setShType(String shType) {
		this.shType = shType;
	}

	@Column(name = "SH_Initiator", length = 10)
	public String getShInitiator() {
		return this.shInitiator;
	}

	public void setShInitiator(String shInitiator) {
		this.shInitiator = shInitiator;
	}

	@Column(name = "SH_Details")
	public String getShDetails() {
		return this.shDetails;
	}

	public void setShDetails(String shDetails) {
		this.shDetails = shDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DeployedAt", length = 23)
	public Date getShDeployedAt() {
		return this.shDeployedAt;
	}

	public void setShDeployedAt(Date shDeployedAt) {
		this.shDeployedAt = shDeployedAt;
	}

	@Column(name = "SH_behaviourDetailsStatus", nullable = false, length = 10)
	public String getShBehaviourDetailsStatus() {
		return this.shBehaviourDetailsStatus;
	}

	public void setShBehaviourDetailsStatus(String shBehaviourDetailsStatus) {
		this.shBehaviourDetailsStatus = shBehaviourDetailsStatus;
	}

	@Column(name = "SH_ManualTime", length = 10)
	public String getShManualTime() {
		return this.shManualTime;
	}

	public void setShManualTime(String shManualTime) {
		this.shManualTime = shManualTime;
	}

	@Column(name = "SH_SHTime", length = 10)
	public String getShShtime() {
		return this.shShtime;
	}

	public void setShShtime(String shShtime) {
		this.shShtime = shShtime;
	}

	@Column(name = "SH_SPOC", length = 45)
	public String getShSpoc() {
		return this.shSpoc;
	}

	public void setShSpoc(String shSpoc) {
		this.shSpoc = shSpoc;
	}

	@Column(name = "SH_Project", length = 45)
	public String getShProject() {
		return this.shProject;
	}

	public void setShProject(String shProject) {
		this.shProject = shProject;
	}

	@Column(name = "SH_Region", length = 45)
	public String getShRegion() {
		return this.shRegion;
	}

	public void setShRegion(String shRegion) {
		this.shRegion = shRegion;
	}

	@Column(name = "SH_Developer", length = 45)
	public String getShDeveloper() {
		return this.shDeveloper;
	}

	public void setShDeveloper(String shDeveloper) {
		this.shDeveloper = shDeveloper;
	}

	@Column(name = "SH_Category", length = 45)
	public String getShCategory() {
		return this.shCategory;
	}

	public void setShCategory(String shCategory) {
		this.shCategory = shCategory;
	}

	@Column(name = "SH_TimeBookingAvailable", length = 15)
	public String getShTimeBookingAvailable() {
		return this.shTimeBookingAvailable;
	}

	public void setShTimeBookingAvailable(String shTimeBookingAvailable) {
		this.shTimeBookingAvailable = shTimeBookingAvailable;
	}

	@Column(name = "SH_UseFrequency", length = 45)
	public String getShUseFrequency() {
		return this.shUseFrequency;
	}

	public void setShUseFrequency(String shUseFrequency) {
		this.shUseFrequency = shUseFrequency;
	}

	@Column(name = "SH_UserCount")
	public Integer getShUserCount() {
		return this.shUserCount;
	}

	public void setShUserCount(Integer shUserCount) {
		this.shUserCount = shUserCount;
	}

	@Column(name = "SH_NDXActivity", length = 250)
	public String getShNdxactivity() {
		return this.shNdxactivity;
	}

	public void setShNdxactivity(String shNdxactivity) {
		this.shNdxactivity = shNdxactivity;
	}

	@Column(name = "SH_NDXSubActivity", length = 250)
	public String getShNdxsubActivity() {
		return this.shNdxsubActivity;
	}

	public void setShNdxsubActivity(String shNdxsubActivity) {
		this.shNdxsubActivity = shNdxsubActivity;
	}

	@Column(name = "SH_Domain", length = 45)
	public String getShDomain() {
		return this.shDomain;
	}

	public void setShDomain(String shDomain) {
		this.shDomain = shDomain;
	}

	@Column(name = "SH_JarName", length = 45)
	public String getShJarName() {
		return this.shJarName;
	}

	public void setShJarName(String shJarName) {
		this.shJarName = shJarName;
	}

	@Column(name = "SH_BOTFor", length = 45)
	public String getShBotfor() {
		return this.shBotfor;
	}

	public void setShBotfor(String shBotfor) {
		this.shBotfor = shBotfor;
	}

	@Column(name = "SH_ParallelWOExecution", length = 5)
	public String getShParallelWoexecution() {
		return this.shParallelWoexecution;
	}

	public void setShParallelWoexecution(String shParallelWoexecution) {
		this.shParallelWoexecution = shParallelWoexecution;
	}

	@Column(name = "SH_Subactivity_ID", length = 100)
	public String getShSubactivityId() {
		return this.shSubactivityId;
	}

	public void setShSubactivityId(String shSubactivityId) {
		this.shSubactivityId = shSubactivityId;
	}

	@Column(name = "SH_RPARequestID", length = 45)
	public String getShRparequestId() {
		return this.shRparequestId;
	}

	public void setShRparequestId(String shRparequestId) {
		this.shRparequestId = shRparequestId;
	}

	@Column(name = "SH_ProjectName", length = 100)
	public String getShProjectName() {
		return this.shProjectName;
	}

	public void setShProjectName(String shProjectName) {
		this.shProjectName = shProjectName;
	}

	@Column(name = "SH_CodeReuseFactor", length = 45)
	public String getShCodeReuseFactor() {
		return this.shCodeReuseFactor;
	}

	public void setShCodeReuseFactor(String shCodeReuseFactor) {
		this.shCodeReuseFactor = shCodeReuseFactor;
	}

	@Column(name = "SH_LineOfCode", length = 45)
	public String getShLineOfCode() {
		return this.shLineOfCode;
	}

	public void setShLineOfCode(String shLineOfCode) {
		this.shLineOfCode = shLineOfCode;
	}

	@Column(name = "SH_UATStatus", length = 5)
	public String getShUatstatus() {
		return this.shUatstatus;
	}

	public void setShUatstatus(String shUatstatus) {
		this.shUatstatus = shUatstatus;
	}

	@Column(name = "SH_UATOwner", length = 45)
	public String getShUatowner() {
		return this.shUatowner;
	}

	public void setShUatowner(String shUatowner) {
		this.shUatowner = shUatowner;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_UATCompletionDate", length = 23)
	public Date getShUatcompletionDate() {
		return this.shUatcompletionDate;
	}

	public void setShUatcompletionDate(Date shUatcompletionDate) {
		this.shUatcompletionDate = shUatcompletionDate;
	}

}
