package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Completeresourcedetails generated by hbm2java
 */
@Entity
@Table(name = "completeresourcedetails", schema = "dbo")
public class Completeresourcedetails implements java.io.Serializable {

	private CompleteresourcedetailsId id;

	public Completeresourcedetails() {
	}

	public Completeresourcedetails(CompleteresourcedetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resourceRequestId", column = @Column(name = "ResourceRequestID", nullable = false)),
			@AttributeOverride(name = "resourceType", column = @Column(name = "ResourceType")),
			@AttributeOverride(name = "jobRoleId", column = @Column(name = "JobRoleID")),
			@AttributeOverride(name = "jobStageId", column = @Column(name = "JobStageID")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "onsiteCount", column = @Column(name = "OnsiteCount", nullable = false)),
			@AttributeOverride(name = "remoteCount", column = @Column(name = "RemoteCount", nullable = false)),
			@AttributeOverride(name = "positionStatus", column = @Column(name = "PositionStatus", length = 100)),
			@AttributeOverride(name = "inActivatedOn", column = @Column(name = "InActivatedOn", length = 10)),
			@AttributeOverride(name = "crstatus", column = @Column(name = "CRStatus", length = 100)),
			@AttributeOverride(name = "workEffortId", column = @Column(name = "WorkEffortID", nullable = false)),
			@AttributeOverride(name = "wkeffCreatedOn", column = @Column(name = "WKEffCreatedON", nullable = false, length = 23)),
			@AttributeOverride(name = "resourcePositionId", column = @Column(name = "ResourcePositionID", nullable = false)),
			@AttributeOverride(name = "positionStartDate", column = @Column(name = "PositionStartDate", nullable = false, length = 10)),
			@AttributeOverride(name = "positionEndDate", column = @Column(name = "PositionEndDate", nullable = false, length = 10)),
			@AttributeOverride(name = "duration", column = @Column(name = "Duration")),
			@AttributeOverride(name = "ftePercent", column = @Column(name = "FTE_Percent", precision = 53, scale = 0)),
			@AttributeOverride(name = "remoteOnsite", column = @Column(name = "remote_onsite")),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", precision = 53, scale = 0)),
			@AttributeOverride(name = "blockedResource", column = @Column(name = "BlockedResource", length = 8)),
			@AttributeOverride(name = "workEffortStatus", column = @Column(name = "WorkEffortStatus", length = 100)),
			@AttributeOverride(name = "jobRoleName", column = @Column(name = "JobRoleName")),
			@AttributeOverride(name = "jobStageName", column = @Column(name = "JobStageName")) })
	public CompleteresourcedetailsId getId() {
		return this.id;
	}

	public void setId(CompleteresourcedetailsId id) {
		this.id = id;
	}

}
