package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CompleteProjectsdetails generated by hbm2java
 */
@Entity
@Table(name = "completeProjectsdetails", schema = "dbo")
public class CompleteProjectsdetails implements java.io.Serializable {

	private CompleteProjectsdetailsId id;

	public CompleteProjectsdetails() {
	}

	public CompleteProjectsdetails(CompleteProjectsdetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "projectType", column = @Column(name = "ProjectType")),
			@AttributeOverride(name = "cpm", column = @Column(name = "CPM")),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator")),
			@AttributeOverride(name = "projectStartDate", column = @Column(name = "ProjectStartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "projectEndDate", column = @Column(name = "ProjectEndDate", length = 23)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "projectStatus", column = @Column(name = "PRojectStatus")),
			@AttributeOverride(name = "operationalManager", column = @Column(name = "OperationalManager")),
			@AttributeOverride(name = "scopeName", column = @Column(name = "ScopeName")),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID", nullable = false)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 128)),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID", nullable = false)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "serviceAreaId", column = @Column(name = "ServiceAreaID", nullable = false)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "subServiceArea", column = @Column(name = "SubServiceArea", length = 128)),
			@AttributeOverride(name = "opportunityName", column = @Column(name = "OpportunityName")),
			@AttributeOverride(name = "companyName", column = @Column(name = "CompanyName")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName")) })
	public CompleteProjectsdetailsId getId() {
		return this.id;
	}

	public void setId(CompleteProjectsdetailsId id) {
		this.id = id;
	}

}
