package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DrOrgUnitOrder generated by hbm2java
 */
@Entity
@Table(name = "DR_ORG_UNIT_Order", schema = "refData")
public class DrOrgUnitOrder implements java.io.Serializable {

	private DrOrgUnitOrderId id;

	public DrOrgUnitOrder() {
	}

	public DrOrgUnitOrder(DrOrgUnitOrderId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orgUnitId", column = @Column(name = "ORG_UNIT_ID", nullable = false)),
			@AttributeOverride(name = "orgUnit", column = @Column(name = "ORG_UNIT", length = 35)),
			@AttributeOverride(name = "orderId", column = @Column(name = "OrderID", nullable = false)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 7)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedON", length = 10)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", length = 7)),
			@AttributeOverride(name = "lastModifiedOn", column = @Column(name = "LastModifiedOn", length = 10)) })
	public DrOrgUnitOrderId getId() {
		return this.id;
	}

	public void setId(DrOrgUnitOrderId id) {
		this.id = id;
	}

}
