package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FlowChartCreationTmp generated by hbm2java
 */
@Entity
@Table(name = "FlowChartCreationTmp", schema = "dbo")
public class FlowChartCreationTmp implements java.io.Serializable {

	private FlowChartCreationTmpId id;

	public FlowChartCreationTmp() {
	}

	public FlowChartCreationTmp(FlowChartCreationTmpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "stepName", column = @Column(name = "StepName")),
			@AttributeOverride(name = "graphicalRepresentation", column = @Column(name = "GraphicalRepresentation")),
			@AttributeOverride(name = "executionType", column = @Column(name = "ExecutionType")),
			@AttributeOverride(name = "responsible", column = @Column(name = "Responsible")),
			@AttributeOverride(name = "dependentStepName", column = @Column(name = "DependentStepName")),
			@AttributeOverride(name = "ifDepnOnDecisionStep", column = @Column(name = "IfDepnOnDecisionStep")),
			@AttributeOverride(name = "isTaskOrSubTask", column = @Column(name = "IsTaskOrSubTask")),
			@AttributeOverride(name = "taskOrParentTaskMapped", column = @Column(name = "TaskOrParentTaskMapped"))
	})
	public FlowChartCreationTmpId getId() {
		return this.id;
	}

	public void setId(FlowChartCreationTmpId id) {
		this.id = id;
	}

}
