package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Merlin generated by hbm2java
 */
@Entity
@Table(name = "MERLIN", schema = "dbo")
public class Merlin implements java.io.Serializable {

	private MerlinId id;

	public Merlin() {
	}

	public Merlin(MerlinId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "employeeGroup", column = @Column(name = "Employee Group")),
			@AttributeOverride(name = "resourceName", column = @Column(name = "Resource Name")),
			@AttributeOverride(name = "signum", column = @Column(name = "Signum")),
			@AttributeOverride(name = "posNo", column = @Column(name = "PosNo")),
			@AttributeOverride(name = "fso", column = @Column(name = "FSO")),
			@AttributeOverride(name = "perNo", column = @Column(name = "Per_No")),
			@AttributeOverride(name = "jobName", column = @Column(name = "Job Name")),
			@AttributeOverride(name = "jobStage", column = @Column(name = "Job Stage")),
			@AttributeOverride(name = "unit", column = @Column(name = "Unit")),
			@AttributeOverride(name = "parentUnit", column = @Column(name = "ParentUnit")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain")),
			@AttributeOverride(name = "subDomain", column = @Column(name = "Sub Domain")),
			@AttributeOverride(name = "countryName", column = @Column(name = "Country Name")),
			@AttributeOverride(name = "companyName", column = @Column(name = "Company Name")),
			@AttributeOverride(name = "functionalArea", column = @Column(name = "Functional Area")),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "Service Area")),
			@AttributeOverride(name = "industryVertical", column = @Column(name = "Industry Vertical")),
			@AttributeOverride(name = "costCentre", column = @Column(name = "Cost Centre")),
			@AttributeOverride(name = "lineManager", column = @Column(name = "Line Manager")),
			@AttributeOverride(name = "profileType", column = @Column(name = "Profile Type")),
			@AttributeOverride(name = "cvStatus", column = @Column(name = "CV Status")),
			@AttributeOverride(name = "assessmentStatus", column = @Column(name = "Assessment Status")),
			@AttributeOverride(name = "certificationFlag(yes/no)", column = @Column(name = "Certification Flag (Yes/No)")),
			@AttributeOverride(name = "etcpCertificateCount", column = @Column(name = "ETCP Certificate Count")),
			@AttributeOverride(name = "giapCertificateCount", column = @Column(name = "GIAP Certificate Count")),
			@AttributeOverride(name = "nonEricssonCertificateCount", column = @Column(name = "Non Ericsson Certificate Count")),
			@AttributeOverride(name = "competenceName", column = @Column(name = "Competence Name")),
			@AttributeOverride(name = "competenceLevel", column = @Column(name = "Competence Level")),
			@AttributeOverride(name = "lastAssessedDate", column = @Column(name = "Last Assessed Date")),
			@AttributeOverride(name = "f30", column = @Column(name = "F30")),
			@AttributeOverride(name = "f31", column = @Column(name = "F31")) })
	public MerlinId getId() {
		return this.id;
	}

	public void setId(MerlinId id) {
		this.id = id;
	}

}
