package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectDeatilsId generated by hbm2java
 */
@Embeddable
public class ProjectDeatilsId implements java.io.Serializable {

	private int projectId;
	private Serializable projectName;
	private Serializable projectCreator;
	private Integer opportunityId;
	private Serializable opportunityName;
	private Integer countryId;
	private Integer marketAreaId;

	public ProjectDeatilsId() {
	}

	public ProjectDeatilsId(int projectId) {
		this.projectId = projectId;
	}

	public ProjectDeatilsId(int projectId, Serializable projectName, Serializable projectCreator, Integer opportunityId,
			Serializable opportunityName, Integer countryId, Integer marketAreaId) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectCreator = projectCreator;
		this.opportunityId = opportunityId;
		this.opportunityName = opportunityName;
		this.countryId = countryId;
		this.marketAreaId = marketAreaId;
	}

	@Column(name = "ProjectID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ProjectName")
	public Serializable getProjectName() {
		return this.projectName;
	}

	public void setProjectName(Serializable projectName) {
		this.projectName = projectName;
	}

	@Column(name = "ProjectCreator")
	public Serializable getProjectCreator() {
		return this.projectCreator;
	}

	public void setProjectCreator(Serializable projectCreator) {
		this.projectCreator = projectCreator;
	}

	@Column(name = "OpportunityID")
	public Integer getOpportunityId() {
		return this.opportunityId;
	}

	public void setOpportunityId(Integer opportunityId) {
		this.opportunityId = opportunityId;
	}

	@Column(name = "OpportunityName")
	public Serializable getOpportunityName() {
		return this.opportunityName;
	}

	public void setOpportunityName(Serializable opportunityName) {
		this.opportunityName = opportunityName;
	}

	@Column(name = "CountryID")
	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	@Column(name = "MarketAreaID")
	public Integer getMarketAreaId() {
		return this.marketAreaId;
	}

	public void setMarketAreaId(Integer marketAreaId) {
		this.marketAreaId = marketAreaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectDeatilsId))
			return false;
		ProjectDeatilsId castOther = (ProjectDeatilsId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& ((this.getProjectName() == castOther.getProjectName())
						|| (this.getProjectName() != null && castOther.getProjectName() != null
								&& this.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getProjectCreator() == castOther.getProjectCreator())
						|| (this.getProjectCreator() != null && castOther.getProjectCreator() != null
								&& this.getProjectCreator().equals(castOther.getProjectCreator())))
				&& ((this.getOpportunityId() == castOther.getOpportunityId())
						|| (this.getOpportunityId() != null && castOther.getOpportunityId() != null
								&& this.getOpportunityId().equals(castOther.getOpportunityId())))
				&& ((this.getOpportunityName() == castOther.getOpportunityName())
						|| (this.getOpportunityName() != null && castOther.getOpportunityName() != null
								&& this.getOpportunityName().equals(castOther.getOpportunityName())))
				&& ((this.getCountryId() == castOther.getCountryId()) || (this.getCountryId() != null
						&& castOther.getCountryId() != null && this.getCountryId().equals(castOther.getCountryId())))
				&& ((this.getMarketAreaId() == castOther.getMarketAreaId())
						|| (this.getMarketAreaId() != null && castOther.getMarketAreaId() != null
								&& this.getMarketAreaId().equals(castOther.getMarketAreaId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + (getProjectCreator() == null ? 0 : this.getProjectCreator().hashCode());
		result = 37 * result + (getOpportunityId() == null ? 0 : this.getOpportunityId().hashCode());
		result = 37 * result + (getOpportunityName() == null ? 0 : this.getOpportunityName().hashCode());
		result = 37 * result + (getCountryId() == null ? 0 : this.getCountryId().hashCode());
		result = 37 * result + (getMarketAreaId() == null ? 0 : this.getMarketAreaId().hashCode());
		return result;
	}

}
