package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectDetailsId generated by hbm2java
 */
@Embeddable
public class ProjectDetailsId implements java.io.Serializable {

	private Serializable projectName;
	private int projectId;
	private Serializable marketAreaName;
	private String domain;
	private String subDomain;
	private String technology;
	private Integer subActivityId;
	private String serviceArea;
	private String subActivity;
	private Date date;

	public ProjectDetailsId() {
	}

	public ProjectDetailsId(int projectId, Date date) {
		this.projectId = projectId;
		this.date = date;
	}

	public ProjectDetailsId(Serializable projectName, int projectId, Serializable marketAreaName, String domain,
			String subDomain, String technology, Integer subActivityId, String serviceArea, String subActivity,
			Date date) {
		this.projectName = projectName;
		this.projectId = projectId;
		this.marketAreaName = marketAreaName;
		this.domain = domain;
		this.subDomain = subDomain;
		this.technology = technology;
		this.subActivityId = subActivityId;
		this.serviceArea = serviceArea;
		this.subActivity = subActivity;
		this.date = date;
	}

	@Column(name = "ProjectName")
	public Serializable getProjectName() {
		return this.projectName;
	}

	public void setProjectName(Serializable projectName) {
		this.projectName = projectName;
	}

	@Column(name = "ProjectID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "MarketAreaName")
	public Serializable getMarketAreaName() {
		return this.marketAreaName;
	}

	public void setMarketAreaName(Serializable marketAreaName) {
		this.marketAreaName = marketAreaName;
	}

	@Column(name = "Domain", length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "SubDomain", length = 128)
	public String getSubDomain() {
		return this.subDomain;
	}

	public void setSubDomain(String subDomain) {
		this.subDomain = subDomain;
	}

	@Column(name = "Technology", length = 128)
	public String getTechnology() {
		return this.technology;
	}

	public void setTechnology(String technology) {
		this.technology = technology;
	}

	@Column(name = "SubActivityID")
	public Integer getSubActivityId() {
		return this.subActivityId;
	}

	public void setSubActivityId(Integer subActivityId) {
		this.subActivityId = subActivityId;
	}

	@Column(name = "ServiceArea", length = 128)
	public String getServiceArea() {
		return this.serviceArea;
	}

	public void setServiceArea(String serviceArea) {
		this.serviceArea = serviceArea;
	}

	@Column(name = "SubActivity", length = 899)
	public String getSubActivity() {
		return this.subActivity;
	}

	public void setSubActivity(String subActivity) {
		this.subActivity = subActivity;
	}

	@Column(name = "Date", nullable = false, length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectDetailsId))
			return false;
		ProjectDetailsId castOther = (ProjectDetailsId) other;

		return ((this.getProjectName() == castOther.getProjectName()) || (this.getProjectName() != null
				&& castOther.getProjectName() != null && this.getProjectName().equals(castOther.getProjectName())))
				&& (this.getProjectId() == castOther.getProjectId())
				&& ((this.getMarketAreaName() == castOther.getMarketAreaName())
						|| (this.getMarketAreaName() != null && castOther.getMarketAreaName() != null
								&& this.getMarketAreaName().equals(castOther.getMarketAreaName())))
				&& ((this.getDomain() == castOther.getDomain()) || (this.getDomain() != null
						&& castOther.getDomain() != null && this.getDomain().equals(castOther.getDomain())))
				&& ((this.getSubDomain() == castOther.getSubDomain()) || (this.getSubDomain() != null
						&& castOther.getSubDomain() != null && this.getSubDomain().equals(castOther.getSubDomain())))
				&& ((this.getTechnology() == castOther.getTechnology()) || (this.getTechnology() != null
						&& castOther.getTechnology() != null && this.getTechnology().equals(castOther.getTechnology())))
				&& ((this.getSubActivityId() == castOther.getSubActivityId())
						|| (this.getSubActivityId() != null && castOther.getSubActivityId() != null
								&& this.getSubActivityId().equals(castOther.getSubActivityId())))
				&& ((this.getServiceArea() == castOther.getServiceArea())
						|| (this.getServiceArea() != null && castOther.getServiceArea() != null
								&& this.getServiceArea().equals(castOther.getServiceArea())))
				&& ((this.getSubActivity() == castOther.getSubActivity())
						|| (this.getSubActivity() != null && castOther.getSubActivity() != null
								&& this.getSubActivity().equals(castOther.getSubActivity())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + this.getProjectId();
		result = 37 * result + (getMarketAreaName() == null ? 0 : this.getMarketAreaName().hashCode());
		result = 37 * result + (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result + (getSubDomain() == null ? 0 : this.getSubDomain().hashCode());
		result = 37 * result + (getTechnology() == null ? 0 : this.getTechnology().hashCode());
		result = 37 * result + (getSubActivityId() == null ? 0 : this.getSubActivityId().hashCode());
		result = 37 * result + (getServiceArea() == null ? 0 : this.getServiceArea().hashCode());
		result = 37 * result + (getSubActivity() == null ? 0 : this.getSubActivity().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
