package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectSubactivityDetails generated by hbm2java
 */
@Entity
@Table(name = "ProjectSubactivityDetails", schema = "refData")
public class ProjectSubactivityDetails implements java.io.Serializable {

	private ProjectSubactivityDetailsId id;

	public ProjectSubactivityDetails() {
	}

	public ProjectSubactivityDetails(ProjectSubactivityDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 1412)) })
	public ProjectSubactivityDetailsId getId() {
		return this.id;
	}

	public void setId(ProjectSubactivityDetailsId id) {
		this.id = id;
	}

}
