package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectDeatils generated by hbm2java
 */
@Entity
@Table(name = "ProjectDeatils", schema = "dbo")
public class ProjectDeatils implements java.io.Serializable {

	private ProjectDeatilsId id;

	public ProjectDeatils() {
	}

	public ProjectDeatils(ProjectDeatilsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator")),
			@AttributeOverride(name = "opportunityId", column = @Column(name = "OpportunityID")),
			@AttributeOverride(name = "opportunityName", column = @Column(name = "OpportunityName")),
			@AttributeOverride(name = "countryId", column = @Column(name = "CountryID")),
			@AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")) })
	public ProjectDeatilsId getId() {
		return this.id;
	}

	public void setId(ProjectDeatilsId id) {
		this.id = id;
	}

}
