package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectDetails generated by hbm2java
 */
@Entity
@Table(name = "ProjectDetails", schema = "refData")
public class ProjectDetails implements java.io.Serializable {

	private ProjectDetailsId id;

	public ProjectDetails() {
	}

	public ProjectDetails(ProjectDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 128)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 899)),
			@AttributeOverride(name = "date", column = @Column(name = "Date", nullable = false, length = 23)) })
	public ProjectDetailsId getId() {
		return this.id;
	}

	public void setId(ProjectDetailsId id) {
		this.id = id;
	}

}
