package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectWiseJson generated by hbm2java
 */
@Entity
@Table(name = "ProjectWiseJSON", schema = "dbo")
public class ProjectWiseJson implements java.io.Serializable {

	private ProjectWiseJsonId id;

	public ProjectWiseJson() {
	}

	public ProjectWiseJson(ProjectWiseJsonId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "flowChartJson", column = @Column(name = "FlowChartJSON")),
			@AttributeOverride(name = "versionNumber", column = @Column(name = "VersionNumber")),
			@AttributeOverride(name = "workFlowName", column = @Column(name = "WorkFlowName")) })
	public ProjectWiseJsonId getId() {
		return this.id;
	}

	public void setId(ProjectWiseJsonId id) {
		this.id = id;
	}

}
