package com.ericsson.isf.model.botstore;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TblAdhocBookingActivity generated by hbm2java
 */
@Entity(name="TblAdhocBookingActivityForIcons")
@Table(name = "TBL_ADHOC_BOOKING_ACTIVITY", schema = "refData")
public class TblAdhocBookingActivityForIcons implements java.io.Serializable {
	
	
	private int adhocBookingActivityId;
	private String activity;
	private String name;
	private String abbreviation;
	private Byte sequence;
	
	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "ADHOCBOOKINGACTIVITYID")
	public int getAdhocBookingActivityId() {
		return this.adhocBookingActivityId;
	}

	public void setAdhocBookingActivityId(int adhocBookingActivityId) {
		this.adhocBookingActivityId = adhocBookingActivityId;
	}


	@Column(name = "Activity")
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}
	
	@Column(name = "Name", nullable = false)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Abbreviation")
	public String getAbbreviation() {
		return abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public Byte getSequence() {
		return sequence;
	}

	public void setSequence(Byte sequence) {
		this.sequence = sequence;
	}

	
}
