package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAccessProfileRequest generated by hbm2java
 */
@Entity
@Table(name = "TBL_Access_Profile_Request", schema = "transactionalData")
public class TblAccessProfileRequest implements java.io.Serializable {

	private long id;
	private String signum;
	private int accessProfileId;
	private String approver;
	private Boolean approvalStatus;
	private String remark;
	private Date createdOn;
	private Date lastModifiedOn;

	public TblAccessProfileRequest() {
	}

	public TblAccessProfileRequest(long id, String signum, int accessProfileId) {
		this.id = id;
		this.signum = signum;
		this.accessProfileId = accessProfileId;
	}

	public TblAccessProfileRequest(long id, String signum, int accessProfileId, String approver, Boolean approvalStatus,
			String remark, Date createdOn, Date lastModifiedOn) {
		this.id = id;
		this.signum = signum;
		this.accessProfileId = accessProfileId;
		this.approver = approver;
		this.approvalStatus = approvalStatus;
		this.remark = remark;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Signum", nullable = false, length = 7)
	public String getSignum() {
		return this.signum;
	}

	public void setSignum(String signum) {
		this.signum = signum;
	}

	@Column(name = "AccessProfileID", nullable = false)
	public int getAccessProfileId() {
		return this.accessProfileId;
	}

	public void setAccessProfileId(int accessProfileId) {
		this.accessProfileId = accessProfileId;
	}

	@Column(name = "Approver", length = 50)
	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	@Column(name = "Approval Status")
	public Boolean getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(Boolean approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	@Column(name = "Remark", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

}
