package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblAcceptanceRating generated by hbm2java
 */
@Entity
@Table(name = "TBL_ACCEPTANCE_RATING", schema = "refData")
public class TblAcceptanceRating implements java.io.Serializable {

	private TblAcceptanceRatingId id;

	public TblAcceptanceRating() {
	}

	public TblAcceptanceRating(TblAcceptanceRatingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "rating", column = @Column(name = "Rating", length = 128)) })
	public TblAcceptanceRatingId getId() {
		return this.id;
	}

	public void setId(TblAcceptanceRatingId id) {
		this.id = id;
	}

}
