package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblAccessProfile generated by hbm2java
 */
@Entity
@Table(name = "TBL_ACCESS_PROFILE", schema = "refData")
public class TblAccessProfile implements java.io.Serializable {

	private TblAccessProfileId id;

	public TblAccessProfile() {
	}

	public TblAccessProfile(TblAccessProfileId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accessProfileId", column = @Column(name = "AccessProfileID", nullable = false)),
			@AttributeOverride(name = "accessProfileName", column = @Column(name = "AccessProfileName", length = 1024)),
			@AttributeOverride(name = "accessRoleId", column = @Column(name = "AccessRoleID")),
			@AttributeOverride(name = "organisationId", column = @Column(name = "OrganisationID")),
			@AttributeOverride(name = "active", column = @Column(name = "Active")) })
	public TblAccessProfileId getId() {
		return this.id;
	}

	public void setId(TblAccessProfileId id) {
		this.id = id;
	}

}
