package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblAccessRoleId generated by hbm2java
 */
@Embeddable
public class TblAccessRoleId implements java.io.Serializable {

	private int accessRoleId;
	private String role;
	private String alias;
	private Boolean active;

	public TblAccessRoleId() {
	}

	public TblAccessRoleId(int accessRoleId) {
		this.accessRoleId = accessRoleId;
	}

	public TblAccessRoleId(int accessRoleId, String role, String alias, Boolean active) {
		this.accessRoleId = accessRoleId;
		this.role = role;
		this.alias = alias;
		this.active = active;
	}

	@Column(name = "AccessRoleID", nullable = false)
	public int getAccessRoleId() {
		return this.accessRoleId;
	}

	public void setAccessRoleId(int accessRoleId) {
		this.accessRoleId = accessRoleId;
	}

	@Column(name = "Role", length = 512)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "Alias", length = 128)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblAccessRoleId))
			return false;
		TblAccessRoleId castOther = (TblAccessRoleId) other;

		return (this.getAccessRoleId() == castOther.getAccessRoleId())
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null && castOther.getRole() != null
						&& this.getRole().equals(castOther.getRole())))
				&& ((this.getAlias() == castOther.getAlias()) || (this.getAlias() != null
						&& castOther.getAlias() != null && this.getAlias().equals(castOther.getAlias())))
				&& ((this.getActive() == castOther.getActive()) || (this.getActive() != null
						&& castOther.getActive() != null && this.getActive().equals(castOther.getActive())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccessRoleId();
		result = 37 * result + (getRole() == null ? 0 : this.getRole().hashCode());
		result = 37 * result + (getAlias() == null ? 0 : this.getAlias().hashCode());
		result = 37 * result + (getActive() == null ? 0 : this.getActive().hashCode());
		return result;
	}

}
