package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblAccessRole generated by hbm2java
 */
@Entity
@Table(name = "TBL_ACCESS_ROLE", schema = "refData")
public class TblAccessRole implements java.io.Serializable {

	private TblAccessRoleId id;

	public TblAccessRole() {
	}

	public TblAccessRole(TblAccessRoleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accessRoleId", column = @Column(name = "AccessRoleID", nullable = false)),
			@AttributeOverride(name = "role", column = @Column(name = "Role", length = 512)),
			@AttributeOverride(name = "alias", column = @Column(name = "Alias", length = 128)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")) })
	public TblAccessRoleId getId() {
		return this.id;
	}

	public void setId(TblAccessRoleId id) {
		this.id = id;
	}

}
