package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblBacklogWithAgingTemp generated by hbm2java
 */
@Entity
@Table(name = "TBL_Backlog_With_Aging_temp", schema = "transactionalData")
public class TblBacklogWithAgingTemp implements java.io.Serializable {

	private TblBacklogWithAgingTempId id;

	public TblBacklogWithAgingTemp() {
	}

	public TblBacklogWithAgingTemp(TblBacklogWithAgingTempId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "subactivityid", column = @Column(name = "Subactivityid", nullable = false)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)),
			@AttributeOverride(name = "woname", column = @Column(name = "WOName")),
			@AttributeOverride(name = "assigned", column = @Column(name = "Assigned", length = 1525)),
			@AttributeOverride(name = "woStatus", column = @Column(name = "WO Status", length = 512)),
			@AttributeOverride(name = "derivedEndDate", column = @Column(name = "DerivedEndDate", length = 10)),
			@AttributeOverride(name = "plannedStartDate", column = @Column(name = "PlannedStartDate", length = 10)),
			@AttributeOverride(name = "date", column = @Column(name = "DATE", length = 10)),
			@AttributeOverride(name = "dated", column = @Column(name = "Dated", length = 29)),
			@AttributeOverride(name = "month", column = @Column(name = "Month")),
			@AttributeOverride(name = "week", column = @Column(name = "Week")),
			@AttributeOverride(name = "year", column = @Column(name = "YEAR")) })
	public TblBacklogWithAgingTempId getId() {
		return this.id;
	}

	public void setId(TblBacklogWithAgingTempId id) {
		this.id = id;
	}

}
