package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBulkWorkOrderCreationHistory generated by hbm2java
 */
@Entity
@Table(name = "TBL_BULK_WORK_ORDER_CREATION_HISTORY", schema = "transactionalData")
public class TblBulkWorkOrderCreationHistory implements java.io.Serializable {

	private long wohistoryId;
	private TblBulkWorkOrderCreation tblBulkWorkOrderCreationByWocreationFromId;
	private TblBulkWorkOrderCreation tblBulkWorkOrderCreationByWocreationToId;
	private String uploadedBy;
	private Date uploadedDate;
	private String uploadStatus;
	private Date processedOn;

	public TblBulkWorkOrderCreationHistory() {
	}

	public TblBulkWorkOrderCreationHistory(long wohistoryId) {
		this.wohistoryId = wohistoryId;
	}

	public TblBulkWorkOrderCreationHistory(long wohistoryId,
			TblBulkWorkOrderCreation tblBulkWorkOrderCreationByWocreationFromId,
			TblBulkWorkOrderCreation tblBulkWorkOrderCreationByWocreationToId, String uploadedBy, Date uploadedDate,
			String uploadStatus, Date processedOn) {
		this.wohistoryId = wohistoryId;
		this.tblBulkWorkOrderCreationByWocreationFromId = tblBulkWorkOrderCreationByWocreationFromId;
		this.tblBulkWorkOrderCreationByWocreationToId = tblBulkWorkOrderCreationByWocreationToId;
		this.uploadedBy = uploadedBy;
		this.uploadedDate = uploadedDate;
		this.uploadStatus = uploadStatus;
		this.processedOn = processedOn;
	}

	@Id

	@Column(name = "WOHistoryID", unique = true, nullable = false)
	public long getWohistoryId() {
		return this.wohistoryId;
	}

	public void setWohistoryId(long wohistoryId) {
		this.wohistoryId = wohistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WOCreationFromID")
	public TblBulkWorkOrderCreation getTblBulkWorkOrderCreationByWocreationFromId() {
		return this.tblBulkWorkOrderCreationByWocreationFromId;
	}

	public void setTblBulkWorkOrderCreationByWocreationFromId(
			TblBulkWorkOrderCreation tblBulkWorkOrderCreationByWocreationFromId) {
		this.tblBulkWorkOrderCreationByWocreationFromId = tblBulkWorkOrderCreationByWocreationFromId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WOCreationToID")
	public TblBulkWorkOrderCreation getTblBulkWorkOrderCreationByWocreationToId() {
		return this.tblBulkWorkOrderCreationByWocreationToId;
	}

	public void setTblBulkWorkOrderCreationByWocreationToId(
			TblBulkWorkOrderCreation tblBulkWorkOrderCreationByWocreationToId) {
		this.tblBulkWorkOrderCreationByWocreationToId = tblBulkWorkOrderCreationByWocreationToId;
	}

	@Column(name = "UploadedBy", length = 64)
	public String getUploadedBy() {
		return this.uploadedBy;
	}

	public void setUploadedBy(String uploadedBy) {
		this.uploadedBy = uploadedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UploadedDate", length = 23)
	public Date getUploadedDate() {
		return this.uploadedDate;
	}

	public void setUploadedDate(Date uploadedDate) {
		this.uploadedDate = uploadedDate;
	}

	@Column(name = "UploadStatus", length = 512)
	public String getUploadStatus() {
		return this.uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ProcessedON", length = 23)
	public Date getProcessedOn() {
		return this.processedOn;
	}

	public void setProcessedOn(Date processedOn) {
		this.processedOn = processedOn;
	}

}
