package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblBulkWorkOrderErrorTableId generated by hbm2java
 */
@Embeddable
public class TblBulkWorkOrderErrorTableId implements java.io.Serializable {

	private Long wocreationId;
	private Integer projectId;
	private String subserviceArea;
	private String domain;
	private String subDomain;
	private String technology;
	private Integer woid;
	private String scopeName;
	private Integer subActivityId;
	private String subActivityName;
	private String priority;
	private String slahours;
	private String assignTo;
	private Date startDate;
	private Date startTime;
	private String workOrderName;
	private String workFlowName;
	private String nodeType;
	private String nodeNames;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Integer externalSourceId;
	private String externalSourceName;
	private String uploadedBy;
	private Integer executionPlanId;
	private String errorCategory;
	private String errorDetails;

	public TblBulkWorkOrderErrorTableId() {
	}

	public TblBulkWorkOrderErrorTableId(Long wocreationId, Integer projectId, String subserviceArea, String domain,
			String subDomain, String technology, Integer woid, String scopeName, Integer subActivityId,
			String subActivityName, String priority, String slahours, String assignTo, Date startDate, Date startTime,
			String workOrderName, String workFlowName, String nodeType, String nodeNames, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate, Integer externalSourceId,
			String externalSourceName, String uploadedBy, Integer executionPlanId, String errorCategory,
			String errorDetails) {
		this.wocreationId = wocreationId;
		this.projectId = projectId;
		this.subserviceArea = subserviceArea;
		this.domain = domain;
		this.subDomain = subDomain;
		this.technology = technology;
		this.woid = woid;
		this.scopeName = scopeName;
		this.subActivityId = subActivityId;
		this.subActivityName = subActivityName;
		this.priority = priority;
		this.slahours = slahours;
		this.assignTo = assignTo;
		this.startDate = startDate;
		this.startTime = startTime;
		this.workOrderName = workOrderName;
		this.workFlowName = workFlowName;
		this.nodeType = nodeType;
		this.nodeNames = nodeNames;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.externalSourceId = externalSourceId;
		this.externalSourceName = externalSourceName;
		this.uploadedBy = uploadedBy;
		this.executionPlanId = executionPlanId;
		this.errorCategory = errorCategory;
		this.errorDetails = errorDetails;
	}

	@Column(name = "WOCreationID")
	public Long getWocreationId() {
		return this.wocreationId;
	}

	public void setWocreationId(Long wocreationId) {
		this.wocreationId = wocreationId;
	}

	@Column(name = "ProjectID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "SubserviceArea", length = 1024)
	public String getSubserviceArea() {
		return this.subserviceArea;
	}

	public void setSubserviceArea(String subserviceArea) {
		this.subserviceArea = subserviceArea;
	}

	@Column(name = "Domain", length = 1024)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "SubDomain", length = 1024)
	public String getSubDomain() {
		return this.subDomain;
	}

	public void setSubDomain(String subDomain) {
		this.subDomain = subDomain;
	}

	@Column(name = "Technology", length = 128)
	public String getTechnology() {
		return this.technology;
	}

	public void setTechnology(String technology) {
		this.technology = technology;
	}

	@Column(name = "WOID")
	public Integer getWoid() {
		return this.woid;
	}

	public void setWoid(Integer woid) {
		this.woid = woid;
	}

	@Column(name = "ScopeName", length = 1024)
	public String getScopeName() {
		return this.scopeName;
	}

	public void setScopeName(String scopeName) {
		this.scopeName = scopeName;
	}

	@Column(name = "SubActivityID")
	public Integer getSubActivityId() {
		return this.subActivityId;
	}

	public void setSubActivityId(Integer subActivityId) {
		this.subActivityId = subActivityId;
	}

	@Column(name = "SubActivityName", length = 1024)
	public String getSubActivityName() {
		return this.subActivityName;
	}

	public void setSubActivityName(String subActivityName) {
		this.subActivityName = subActivityName;
	}

	@Column(name = "Priority", length = 1024)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "SLAHours", length = 20)
	public String getSlahours() {
		return this.slahours;
	}

	public void setSlahours(String slahours) {
		this.slahours = slahours;
	}

	@Column(name = "AssignTo", length = 1024)
	public String getAssignTo() {
		return this.assignTo;
	}

	public void setAssignTo(String assignTo) {
		this.assignTo = assignTo;
	}

	@Column(name = "StartDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "StartTime", length = 16)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Column(name = "WorkOrderName", length = 1024)
	public String getWorkOrderName() {
		return this.workOrderName;
	}

	public void setWorkOrderName(String workOrderName) {
		this.workOrderName = workOrderName;
	}

	@Column(name = "WorkFlowName", length = 1024)
	public String getWorkFlowName() {
		return this.workFlowName;
	}

	public void setWorkFlowName(String workFlowName) {
		this.workFlowName = workFlowName;
	}

	@Column(name = "NodeType", length = 1024)
	public String getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	@Column(name = "NodeNames", length = 1024)
	public String getNodeNames() {
		return this.nodeNames;
	}

	public void setNodeNames(String nodeNames) {
		this.nodeNames = nodeNames;
	}

	@Column(name = "CreatedBy", length = 1024)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LastModifiedBy", length = 1024)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "ExternalSourceID")
	public Integer getExternalSourceId() {
		return this.externalSourceId;
	}

	public void setExternalSourceId(Integer externalSourceId) {
		this.externalSourceId = externalSourceId;
	}

	@Column(name = "ExternalSourceName", length = 1024)
	public String getExternalSourceName() {
		return this.externalSourceName;
	}

	public void setExternalSourceName(String externalSourceName) {
		this.externalSourceName = externalSourceName;
	}

	@Column(name = "UploadedBy", length = 1024)
	public String getUploadedBy() {
		return this.uploadedBy;
	}

	public void setUploadedBy(String uploadedBy) {
		this.uploadedBy = uploadedBy;
	}

	@Column(name = "ExecutionPlanID")
	public Integer getExecutionPlanId() {
		return this.executionPlanId;
	}

	public void setExecutionPlanId(Integer executionPlanId) {
		this.executionPlanId = executionPlanId;
	}

	@Column(name = "ErrorCategory", length = 1024)
	public String getErrorCategory() {
		return this.errorCategory;
	}

	public void setErrorCategory(String errorCategory) {
		this.errorCategory = errorCategory;
	}

	@Column(name = "ErrorDetails")
	public String getErrorDetails() {
		return this.errorDetails;
	}

	public void setErrorDetails(String errorDetails) {
		this.errorDetails = errorDetails;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblBulkWorkOrderErrorTableId))
			return false;
		TblBulkWorkOrderErrorTableId castOther = (TblBulkWorkOrderErrorTableId) other;

		return ((this.getWocreationId() == castOther.getWocreationId()) || (this.getWocreationId() != null
				&& castOther.getWocreationId() != null && this.getWocreationId().equals(castOther.getWocreationId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getSubserviceArea() == castOther.getSubserviceArea())
						|| (this.getSubserviceArea() != null && castOther.getSubserviceArea() != null
								&& this.getSubserviceArea().equals(castOther.getSubserviceArea())))
				&& ((this.getDomain() == castOther.getDomain()) || (this.getDomain() != null
						&& castOther.getDomain() != null && this.getDomain().equals(castOther.getDomain())))
				&& ((this.getSubDomain() == castOther.getSubDomain()) || (this.getSubDomain() != null
						&& castOther.getSubDomain() != null && this.getSubDomain().equals(castOther.getSubDomain())))
				&& ((this.getTechnology() == castOther.getTechnology()) || (this.getTechnology() != null
						&& castOther.getTechnology() != null && this.getTechnology().equals(castOther.getTechnology())))
				&& ((this.getWoid() == castOther.getWoid()) || (this.getWoid() != null && castOther.getWoid() != null
						&& this.getWoid().equals(castOther.getWoid())))
				&& ((this.getScopeName() == castOther.getScopeName()) || (this.getScopeName() != null
						&& castOther.getScopeName() != null && this.getScopeName().equals(castOther.getScopeName())))
				&& ((this.getSubActivityId() == castOther.getSubActivityId())
						|| (this.getSubActivityId() != null && castOther.getSubActivityId() != null
								&& this.getSubActivityId().equals(castOther.getSubActivityId())))
				&& ((this.getSubActivityName() == castOther.getSubActivityName())
						|| (this.getSubActivityName() != null && castOther.getSubActivityName() != null
								&& this.getSubActivityName().equals(castOther.getSubActivityName())))
				&& ((this.getPriority() == castOther.getPriority()) || (this.getPriority() != null
						&& castOther.getPriority() != null && this.getPriority().equals(castOther.getPriority())))
				&& ((this.getSlahours() == castOther.getSlahours()) || (this.getSlahours() != null
						&& castOther.getSlahours() != null && this.getSlahours().equals(castOther.getSlahours())))
				&& ((this.getAssignTo() == castOther.getAssignTo()) || (this.getAssignTo() != null
						&& castOther.getAssignTo() != null && this.getAssignTo().equals(castOther.getAssignTo())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this.getStartDate() != null
						&& castOther.getStartDate() != null && this.getStartDate().equals(castOther.getStartDate())))
				&& ((this.getStartTime() == castOther.getStartTime()) || (this.getStartTime() != null
						&& castOther.getStartTime() != null && this.getStartTime().equals(castOther.getStartTime())))
				&& ((this.getWorkOrderName() == castOther.getWorkOrderName())
						|| (this.getWorkOrderName() != null && castOther.getWorkOrderName() != null
								&& this.getWorkOrderName().equals(castOther.getWorkOrderName())))
				&& ((this.getWorkFlowName() == castOther.getWorkFlowName())
						|| (this.getWorkFlowName() != null && castOther.getWorkFlowName() != null
								&& this.getWorkFlowName().equals(castOther.getWorkFlowName())))
				&& ((this.getNodeType() == castOther.getNodeType()) || (this.getNodeType() != null
						&& castOther.getNodeType() != null && this.getNodeType().equals(castOther.getNodeType())))
				&& ((this.getNodeNames() == castOther.getNodeNames()) || (this.getNodeNames() != null
						&& castOther.getNodeNames() != null && this.getNodeNames().equals(castOther.getNodeNames())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate())
						|| (this.getCreatedDate() != null && castOther.getCreatedDate() != null
								&& this.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getLastModifiedBy() == castOther.getLastModifiedBy())
						|| (this.getLastModifiedBy() != null && castOther.getLastModifiedBy() != null
								&& this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
				&& ((this.getLastModifiedDate() == castOther.getLastModifiedDate())
						|| (this.getLastModifiedDate() != null && castOther.getLastModifiedDate() != null
								&& this.getLastModifiedDate().equals(castOther.getLastModifiedDate())))
				&& ((this.getExternalSourceId() == castOther.getExternalSourceId())
						|| (this.getExternalSourceId() != null && castOther.getExternalSourceId() != null
								&& this.getExternalSourceId().equals(castOther.getExternalSourceId())))
				&& ((this.getExternalSourceName() == castOther.getExternalSourceName())
						|| (this.getExternalSourceName() != null && castOther.getExternalSourceName() != null
								&& this.getExternalSourceName().equals(castOther.getExternalSourceName())))
				&& ((this.getUploadedBy() == castOther.getUploadedBy()) || (this.getUploadedBy() != null
						&& castOther.getUploadedBy() != null && this.getUploadedBy().equals(castOther.getUploadedBy())))
				&& ((this.getExecutionPlanId() == castOther.getExecutionPlanId())
						|| (this.getExecutionPlanId() != null && castOther.getExecutionPlanId() != null
								&& this.getExecutionPlanId().equals(castOther.getExecutionPlanId())))
				&& ((this.getErrorCategory() == castOther.getErrorCategory())
						|| (this.getErrorCategory() != null && castOther.getErrorCategory() != null
								&& this.getErrorCategory().equals(castOther.getErrorCategory())))
				&& ((this.getErrorDetails() == castOther.getErrorDetails())
						|| (this.getErrorDetails() != null && castOther.getErrorDetails() != null
								&& this.getErrorDetails().equals(castOther.getErrorDetails())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getWocreationId() == null ? 0 : this.getWocreationId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getSubserviceArea() == null ? 0 : this.getSubserviceArea().hashCode());
		result = 37 * result + (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result + (getSubDomain() == null ? 0 : this.getSubDomain().hashCode());
		result = 37 * result + (getTechnology() == null ? 0 : this.getTechnology().hashCode());
		result = 37 * result + (getWoid() == null ? 0 : this.getWoid().hashCode());
		result = 37 * result + (getScopeName() == null ? 0 : this.getScopeName().hashCode());
		result = 37 * result + (getSubActivityId() == null ? 0 : this.getSubActivityId().hashCode());
		result = 37 * result + (getSubActivityName() == null ? 0 : this.getSubActivityName().hashCode());
		result = 37 * result + (getPriority() == null ? 0 : this.getPriority().hashCode());
		result = 37 * result + (getSlahours() == null ? 0 : this.getSlahours().hashCode());
		result = 37 * result + (getAssignTo() == null ? 0 : this.getAssignTo().hashCode());
		result = 37 * result + (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37 * result + (getStartTime() == null ? 0 : this.getStartTime().hashCode());
		result = 37 * result + (getWorkOrderName() == null ? 0 : this.getWorkOrderName().hashCode());
		result = 37 * result + (getWorkFlowName() == null ? 0 : this.getWorkFlowName().hashCode());
		result = 37 * result + (getNodeType() == null ? 0 : this.getNodeType().hashCode());
		result = 37 * result + (getNodeNames() == null ? 0 : this.getNodeNames().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
		result = 37 * result + (getLastModifiedDate() == null ? 0 : this.getLastModifiedDate().hashCode());
		result = 37 * result + (getExternalSourceId() == null ? 0 : this.getExternalSourceId().hashCode());
		result = 37 * result + (getExternalSourceName() == null ? 0 : this.getExternalSourceName().hashCode());
		result = 37 * result + (getUploadedBy() == null ? 0 : this.getUploadedBy().hashCode());
		result = 37 * result + (getExecutionPlanId() == null ? 0 : this.getExecutionPlanId().hashCode());
		result = 37 * result + (getErrorCategory() == null ? 0 : this.getErrorCategory().hashCode());
		result = 37 * result + (getErrorDetails() == null ? 0 : this.getErrorDetails().hashCode());
		return result;
	}

}
