package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBookedResource generated by hbm2java
 */
@Entity
@Table(name = "TBL_Booked_Resource", schema = "transactionalData")
public class TblBookedResource implements java.io.Serializable {

	private long id;
	private TblProjects tblProjects;
	private TblResourcePosition tblResourcePosition;
	private TblWorkEffort tblWorkEffort;
	private String signum;
	private Date date;
	private Double blockedHrs;
	private Boolean active;

	public TblBookedResource() {
	}

	public TblBookedResource(long id, TblProjects tblProjects, TblResourcePosition tblResourcePosition,
			TblWorkEffort tblWorkEffort, String signum, Date date) {
		this.id = id;
		this.tblProjects = tblProjects;
		this.tblResourcePosition = tblResourcePosition;
		this.tblWorkEffort = tblWorkEffort;
		this.signum = signum;
		this.date = date;
	}

	public TblBookedResource(long id, TblProjects tblProjects, TblResourcePosition tblResourcePosition,
			TblWorkEffort tblWorkEffort, String signum, Date date, Double blockedHrs, Boolean active) {
		this.id = id;
		this.tblProjects = tblProjects;
		this.tblResourcePosition = tblResourcePosition;
		this.tblWorkEffort = tblWorkEffort;
		this.signum = signum;
		this.date = date;
		this.blockedHrs = blockedHrs;
		this.active = active;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID", nullable = false)
	public TblProjects getTblProjects() {
		return this.tblProjects;
	}

	public void setTblProjects(TblProjects tblProjects) {
		this.tblProjects = tblProjects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Positionid", nullable = false)
	public TblResourcePosition getTblResourcePosition() {
		return this.tblResourcePosition;
	}

	public void setTblResourcePosition(TblResourcePosition tblResourcePosition) {
		this.tblResourcePosition = tblResourcePosition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WFID", nullable = false)
	public TblWorkEffort getTblWorkEffort() {
		return this.tblWorkEffort;
	}

	public void setTblWorkEffort(TblWorkEffort tblWorkEffort) {
		this.tblWorkEffort = tblWorkEffort;
	}

	@Column(name = "Signum", nullable = false, length = 7)
	public String getSignum() {
		return this.signum;
	}

	public void setSignum(String signum) {
		this.signum = signum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "BlockedHrs", precision = 53, scale = 0)
	public Double getBlockedHrs() {
		return this.blockedHrs;
	}

	public void setBlockedHrs(Double blockedHrs) {
		this.blockedHrs = blockedHrs;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
