package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblCountries generated by hbm2java
 */
@Entity
@Table(name = "TBL_COUNTRIES", schema = "refData")
public class TblCountries implements java.io.Serializable {

	private int countryId;
	private TblMarketareas tblMarketareas;
	private Serializable countryName;
	private Serializable description;
	private Set<TblOpportunity> tblOpportunities = new HashSet<TblOpportunity>(0);

	public TblCountries() {
	}

	public TblCountries(int countryId) {
		this.countryId = countryId;
	}

	public TblCountries(int countryId, TblMarketareas tblMarketareas, Serializable countryName,
			Serializable description, Set<TblOpportunity> tblOpportunities) {
		this.countryId = countryId;
		this.tblMarketareas = tblMarketareas;
		this.countryName = countryName;
		this.description = description;
		this.tblOpportunities = tblOpportunities;
	}

	@Id

	@Column(name = "CountryID", unique = true, nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MarketAreaID")
	public TblMarketareas getTblMarketareas() {
		return this.tblMarketareas;
	}

	public void setTblMarketareas(TblMarketareas tblMarketareas) {
		this.tblMarketareas = tblMarketareas;
	}

	@Column(name = "CountryName")
	public Serializable getCountryName() {
		return this.countryName;
	}

	public void setCountryName(Serializable countryName) {
		this.countryName = countryName;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCountries")
	public Set<TblOpportunity> getTblOpportunities() {
		return this.tblOpportunities;
	}

	public void setTblOpportunities(Set<TblOpportunity> tblOpportunities) {
		this.tblOpportunities = tblOpportunities;
	}

}
