package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblCountryCustomerMapping generated by hbm2java
 */
@Entity
@Table(name = "TBL_CountryCustomerMapping", schema = "refData")
public class TblCountryCustomerMapping implements java.io.Serializable {

	private int id;
	private int customerId;
	private Integer countryId;

	public TblCountryCustomerMapping() {
	}

	public TblCountryCustomerMapping(int id, int customerId) {
		this.id = id;
		this.customerId = customerId;
	}

	public TblCountryCustomerMapping(int id, int customerId, Integer countryId) {
		this.id = id;
		this.customerId = customerId;
		this.countryId = countryId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CustomerID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CountryID")
	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

}
