package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblCustomers generated by hbm2java
 */
@Entity
@Table(name = "TBL_CUSTOMERS", schema = "refData")
public class TblCustomers implements java.io.Serializable {

	private int customerId;
	private Serializable customerName;
	private Serializable description;
	private Serializable country;
	private Set<TblOpportunity> tblOpportunities = new HashSet<TblOpportunity>(0);

	public TblCustomers() {
	}

	public TblCustomers(int customerId) {
		this.customerId = customerId;
	}

	public TblCustomers(int customerId, Serializable customerName, Serializable description, Serializable country,
			Set<TblOpportunity> tblOpportunities) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.description = description;
		this.country = country;
		this.tblOpportunities = tblOpportunities;
	}

	@Id

	@Column(name = "CustomerID", unique = true, nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CustomerName")
	public Serializable getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(Serializable customerName) {
		this.customerName = customerName;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "Country")
	public Serializable getCountry() {
		return this.country;
	}

	public void setCountry(Serializable country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCustomers")
	public Set<TblOpportunity> getTblOpportunities() {
		return this.tblOpportunities;
	}

	public void setTblOpportunities(Set<TblOpportunity> tblOpportunities) {
		this.tblOpportunities = tblOpportunities;
	}

}
