package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblCompanies generated by hbm2java
 */
@Entity
@Table(name = "TBL_COMPANIES", schema = "refData")
public class TblCompanies implements java.io.Serializable {

	private int companyId;
	private Serializable companyName;
	private Serializable description;
	private Set<TblOpportunity> tblOpportunities = new HashSet<TblOpportunity>(0);

	public TblCompanies() {
	}

	public TblCompanies(int companyId) {
		this.companyId = companyId;
	}

	public TblCompanies(int companyId, Serializable companyName, Serializable description,
			Set<TblOpportunity> tblOpportunities) {
		this.companyId = companyId;
		this.companyName = companyName;
		this.description = description;
		this.tblOpportunities = tblOpportunities;
	}

	@Id

	@Column(name = "CompanyID", unique = true, nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CompanyName")
	public Serializable getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(Serializable companyName) {
		this.companyName = companyName;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCompanies")
	public Set<TblOpportunity> getTblOpportunities() {
		return this.tblOpportunities;
	}

	public void setTblOpportunities(Set<TblOpportunity> tblOpportunities) {
		this.tblOpportunities = tblOpportunities;
	}

}
