package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblCapability generated by hbm2java
 */
@Entity
@Table(name = "TBL_CAPABILITY", schema = "refData")
public class TblCapability implements java.io.Serializable {

	private TblCapabilityId id;

	public TblCapability() {
	}

	public TblCapability(TblCapabilityId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "capabilityPageId", column = @Column(name = "CapabilityPageID", nullable = false)),
			@AttributeOverride(name = "capabilityPageGroup", column = @Column(name = "CapabilityPageGroup", length = 512)),
			@AttributeOverride(name = "capabilityPageName", column = @Column(name = "CapabilityPageName", length = 512)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "groupTitle", column = @Column(name = "GroupTitle", length = 100)),
			@AttributeOverride(name = "subMenuTitle", column = @Column(name = "SubMenuTitle", length = 100)),
			@AttributeOverride(name = "groupIcon", column = @Column(name = "GroupIcon", length = 100)),
			@AttributeOverride(name = "subMenuHref", column = @Column(name = "SubMenuHref", length = 100)),
			@AttributeOverride(name = "onClick", column = @Column(name = "OnClick")),
			@AttributeOverride(name = "groupHref", column = @Column(name = "GroupHref")),
			@AttributeOverride(name = "priority", column = @Column(name = "Priority")),
			@AttributeOverride(name = "groupOnClick", column = @Column(name = "GroupOnClick")) })
	public TblCapabilityId getId() {
		return this.id;
	}

	public void setId(TblCapabilityId id) {
		this.id = id;
	}

}
