package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblCalenderDb generated by hbm2java
 */
@Entity
@Table(name = "TBL_CALENDER_DB", schema = "refData")
public class TblCalenderDb implements java.io.Serializable {

	private TblCalenderDbId id;

	public TblCalenderDb() {
	}

	public TblCalenderDb(TblCalenderDbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "dt", column = @Column(name = "dt", nullable = false, length = 16)),
			@AttributeOverride(name = "isWeekday", column = @Column(name = "isWeekday")),
			@AttributeOverride(name = "isHoliday", column = @Column(name = "isHoliday")),
			@AttributeOverride(name = "y", column = @Column(name = "Y")),
			@AttributeOverride(name = "q", column = @Column(name = "Q")),
			@AttributeOverride(name = "m", column = @Column(name = "M")),
			@AttributeOverride(name = "d", column = @Column(name = "D")),
			@AttributeOverride(name = "dw", column = @Column(name = "DW")),
			@AttributeOverride(name = "monthname", column = @Column(name = "monthname", length = 9)),
			@AttributeOverride(name = "dayname", column = @Column(name = "dayname", length = 9)),
			@AttributeOverride(name = "w", column = @Column(name = "W")),
			@AttributeOverride(name = "holidayDescription", column = @Column(name = "HolidayDescription", length = 32)) })
	public TblCalenderDbId getId() {
		return this.id;
	}

	public void setId(TblCalenderDbId id) {
		this.id = id;
	}

}
