package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblCalenderDbId generated by hbm2java
 */
@Embeddable
public class TblCalenderDbId implements java.io.Serializable {

	private Date dt;
	private Boolean isWeekday;
	private Boolean isHoliday;
	private Short y;
	private Byte q;
	private Byte m;
	private Byte d;
	private Byte dw;
	private String monthname;
	private String dayname;
	private Byte w;
	private String holidayDescription;

	public TblCalenderDbId() {
	}

	public TblCalenderDbId(Date dt) {
		this.dt = dt;
	}

	public TblCalenderDbId(Date dt, Boolean isWeekday, Boolean isHoliday, Short y, Byte q, Byte m, Byte d, Byte dw,
			String monthname, String dayname, Byte w, String holidayDescription) {
		this.dt = dt;
		this.isWeekday = isWeekday;
		this.isHoliday = isHoliday;
		this.y = y;
		this.q = q;
		this.m = m;
		this.d = d;
		this.dw = dw;
		this.monthname = monthname;
		this.dayname = dayname;
		this.w = w;
		this.holidayDescription = holidayDescription;
	}

	@Column(name = "dt", nullable = false, length = 16)
	public Date getDt() {
		return this.dt;
	}

	public void setDt(Date dt) {
		this.dt = dt;
	}

	@Column(name = "isWeekday")
	public Boolean getIsWeekday() {
		return this.isWeekday;
	}

	public void setIsWeekday(Boolean isWeekday) {
		this.isWeekday = isWeekday;
	}

	@Column(name = "isHoliday")
	public Boolean getIsHoliday() {
		return this.isHoliday;
	}

	public void setIsHoliday(Boolean isHoliday) {
		this.isHoliday = isHoliday;
	}

	@Column(name = "Y")
	public Short getY() {
		return this.y;
	}

	public void setY(Short y) {
		this.y = y;
	}

	@Column(name = "Q")
	public Byte getQ() {
		return this.q;
	}

	public void setQ(Byte q) {
		this.q = q;
	}

	@Column(name = "M")
	public Byte getM() {
		return this.m;
	}

	public void setM(Byte m) {
		this.m = m;
	}

	@Column(name = "D")
	public Byte getD() {
		return this.d;
	}

	public void setD(Byte d) {
		this.d = d;
	}

	@Column(name = "DW")
	public Byte getDw() {
		return this.dw;
	}

	public void setDw(Byte dw) {
		this.dw = dw;
	}

	@Column(name = "monthname", length = 9)
	public String getMonthname() {
		return this.monthname;
	}

	public void setMonthname(String monthname) {
		this.monthname = monthname;
	}

	@Column(name = "dayname", length = 9)
	public String getDayname() {
		return this.dayname;
	}

	public void setDayname(String dayname) {
		this.dayname = dayname;
	}

	@Column(name = "W")
	public Byte getW() {
		return this.w;
	}

	public void setW(Byte w) {
		this.w = w;
	}

	@Column(name = "HolidayDescription", length = 32)
	public String getHolidayDescription() {
		return this.holidayDescription;
	}

	public void setHolidayDescription(String holidayDescription) {
		this.holidayDescription = holidayDescription;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblCalenderDbId))
			return false;
		TblCalenderDbId castOther = (TblCalenderDbId) other;

		return ((this.getDt() == castOther.getDt())
				|| (this.getDt() != null && castOther.getDt() != null && this.getDt().equals(castOther.getDt())))
				&& ((this.getIsWeekday() == castOther.getIsWeekday()) || (this.getIsWeekday() != null
						&& castOther.getIsWeekday() != null && this.getIsWeekday().equals(castOther.getIsWeekday())))
				&& ((this.getIsHoliday() == castOther.getIsHoliday()) || (this.getIsHoliday() != null
						&& castOther.getIsHoliday() != null && this.getIsHoliday().equals(castOther.getIsHoliday())))
				&& ((this.getY() == castOther.getY())
						|| (this.getY() != null && castOther.getY() != null && this.getY().equals(castOther.getY())))
				&& ((this.getQ() == castOther.getQ())
						|| (this.getQ() != null && castOther.getQ() != null && this.getQ().equals(castOther.getQ())))
				&& ((this.getM() == castOther.getM())
						|| (this.getM() != null && castOther.getM() != null && this.getM().equals(castOther.getM())))
				&& ((this.getD() == castOther.getD())
						|| (this.getD() != null && castOther.getD() != null && this.getD().equals(castOther.getD())))
				&& ((this.getDw() == castOther.getDw()) || (this.getDw() != null && castOther.getDw() != null
						&& this.getDw().equals(castOther.getDw())))
				&& ((this.getMonthname() == castOther.getMonthname()) || (this.getMonthname() != null
						&& castOther.getMonthname() != null && this.getMonthname().equals(castOther.getMonthname())))
				&& ((this.getDayname() == castOther.getDayname()) || (this.getDayname() != null
						&& castOther.getDayname() != null && this.getDayname().equals(castOther.getDayname())))
				&& ((this.getW() == castOther.getW())
						|| (this.getW() != null && castOther.getW() != null && this.getW().equals(castOther.getW())))
				&& ((this.getHolidayDescription() == castOther.getHolidayDescription())
						|| (this.getHolidayDescription() != null && castOther.getHolidayDescription() != null
								&& this.getHolidayDescription().equals(castOther.getHolidayDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDt() == null ? 0 : this.getDt().hashCode());
		result = 37 * result + (getIsWeekday() == null ? 0 : this.getIsWeekday().hashCode());
		result = 37 * result + (getIsHoliday() == null ? 0 : this.getIsHoliday().hashCode());
		result = 37 * result + (getY() == null ? 0 : this.getY().hashCode());
		result = 37 * result + (getQ() == null ? 0 : this.getQ().hashCode());
		result = 37 * result + (getM() == null ? 0 : this.getM().hashCode());
		result = 37 * result + (getD() == null ? 0 : this.getD().hashCode());
		result = 37 * result + (getDw() == null ? 0 : this.getDw().hashCode());
		result = 37 * result + (getMonthname() == null ? 0 : this.getMonthname().hashCode());
		result = 37 * result + (getDayname() == null ? 0 : this.getDayname().hashCode());
		result = 37 * result + (getW() == null ? 0 : this.getW().hashCode());
		result = 37 * result + (getHolidayDescription() == null ? 0 : this.getHolidayDescription().hashCode());
		return result;
	}

}
