package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblChartsDb generated by hbm2java
 */
@Entity
@Table(name = "TBL_CHARTS_DB", schema = "refData")
public class TblChartsDb implements java.io.Serializable {

	private TblChartsDbId id;

	public TblChartsDb() {
	}

	public TblChartsDb(TblChartsDbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "orderId", column = @Column(name = "OrderId", nullable = false)),
			@AttributeOverride(name = "chartType", column = @Column(name = "ChartType", nullable = false, length = 128)),
			@AttributeOverride(name = "chartTitle", column = @Column(name = "ChartTitle", nullable = false, length = 256)),
			@AttributeOverride(name = "tableOrder", column = @Column(name = "TableOrder", nullable = false, length = 64)),
			@AttributeOverride(name = "orientation", column = @Column(name = "Orientation", nullable = false, length = 64)),
			@AttributeOverride(name = "domainLabel", column = @Column(name = "DomainLabel", nullable = false, length = 256)),
			@AttributeOverride(name = "rangeLabel", column = @Column(name = "RangeLabel", nullable = false, length = 256)),
			@AttributeOverride(name = "legends", column = @Column(name = "Legends", nullable = false)),
			@AttributeOverride(name = "tooltips", column = @Column(name = "Tooltips", nullable = false)),
			@AttributeOverride(name = "urls", column = @Column(name = "URLs", nullable = false)),
			@AttributeOverride(name = "storedProcedure", column = @Column(name = "StoredProcedure", nullable = false, length = 256)),
			@AttributeOverride(name = "chartLevel", column = @Column(name = "ChartLevel", nullable = false, length = 128)),
			@AttributeOverride(name = "drillDownChartLevel", column = @Column(name = "DrillDownChartLevel", length = 128)),
			@AttributeOverride(name = "headerName", column = @Column(name = "HeaderName", length = 256)) })
	public TblChartsDbId getId() {
		return this.id;
	}

	public void setId(TblChartsDbId id) {
		this.id = id;
	}

}
