package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblCostPerSiteJobdone generated by hbm2java
 */
@Entity
@Table(name = "tbl_Cost_Per_Site_Jobdone", schema = "transactionalData")
public class TblCostPerSiteJobdone implements java.io.Serializable {

	private TblCostPerSiteJobdoneId id;

	public TblCostPerSiteJobdone() {
	}

	public TblCostPerSiteJobdone(TblCostPerSiteJobdoneId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "marketArea", column = @Column(name = "Market Area")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID", nullable = false)),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)),
			@AttributeOverride(name = "resourceName", column = @Column(name = "Resource Name", length = 1525)),
			@AttributeOverride(name = "workOrderId", column = @Column(name = "Work Order Id", nullable = false)),
			@AttributeOverride(name = "workOrderStatus", column = @Column(name = "Work Order Status", length = 512)),
			@AttributeOverride(name = "plannedStartDate", column = @Column(name = "Planned Start Date", length = 23)),
			@AttributeOverride(name = "plannedEndDate", column = @Column(name = "Planned End Date", length = 23)),
			@AttributeOverride(name = "actualStartDate", column = @Column(name = "Actual Start Date", length = 23)),
			@AttributeOverride(name = "actualEndDate", column = @Column(name = "Actual End Date", length = 23)),
			@AttributeOverride(name = "date", column = @Column(name = "Date", length = 10)),
			@AttributeOverride(name = "avgEstdEffort", column = @Column(name = "AvgEstdEffort", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "week", column = @Column(name = "Week")),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "mhr", column = @Column(name = "mhr")),
			@AttributeOverride(name = "avgEstCost", column = @Column(name = "avgEstCost", precision = 53, scale = 0)),
			@AttributeOverride(name = "woCost", column = @Column(name = "WO Cost", precision = 53, scale = 0)),
			@AttributeOverride(name = "siteName", column = @Column(name = "SiteName")) })
	public TblCostPerSiteJobdoneId getId() {
		return this.id;
	}

	public void setId(TblCostPerSiteJobdoneId id) {
		this.id = id;
	}

}
