package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblDomain generated by hbm2java
 */
@Entity
@Table(name = "TBL_DOMAIN", schema = "refData")
public class TblDomain implements java.io.Serializable {

	private int domainId;
	private String domain;
	private String subDomain;
	private Boolean active;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Short parentDomainId;
	private String domainCcm;
	private String subDomainCcm;
	private Set<TblSubactivity> tblSubactivities = new HashSet<TblSubactivity>(0);

	public TblDomain() {
	}

	public TblDomain(int domainId) {
		this.domainId = domainId;
	}

	public TblDomain(int domainId, String domain, String subDomain, Boolean active, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate, Short parentDomainId, String domainCcm, String subDomainCcm,
			Set<TblSubactivity> tblSubactivities) {
		this.domainId = domainId;
		this.domain = domain;
		this.subDomain = subDomain;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.parentDomainId = parentDomainId;
		this.domainCcm = domainCcm;
		this.subDomainCcm = subDomainCcm;
		this.tblSubactivities = tblSubactivities;
	}

	@Id

	@Column(name = "DomainID", unique = true, nullable = false)
	public int getDomainId() {
		return this.domainId;
	}

	public void setDomainId(int domainId) {
		this.domainId = domainId;
	}

	@Column(name = "Domain", length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "SubDomain", length = 128)
	public String getSubDomain() {
		return this.subDomain;
	}

	public void setSubDomain(String subDomain) {
		this.subDomain = subDomain;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "CreatedBy", length = 128)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LastModifiedBy", length = 128)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "parentDomainID")
	public Short getParentDomainId() {
		return this.parentDomainId;
	}

	public void setParentDomainId(Short parentDomainId) {
		this.parentDomainId = parentDomainId;
	}

	@Column(name = "DomainCCM", length = 128)
	public String getDomainCcm() {
		return this.domainCcm;
	}

	public void setDomainCcm(String domainCcm) {
		this.domainCcm = domainCcm;
	}

	@Column(name = "SubDomainCCM", length = 128)
	public String getSubDomainCcm() {
		return this.subDomainCcm;
	}

	public void setSubDomainCcm(String subDomainCcm) {
		this.subDomainCcm = subDomainCcm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDomain")
	public Set<TblSubactivity> getTblSubactivities() {
		return this.tblSubactivities;
	}

	public void setTblSubactivities(Set<TblSubactivity> tblSubactivities) {
		this.tblSubactivities = tblSubactivities;
	}

}
