package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblDomainSpocBackup generated by hbm2java
 */
@Entity
@Table(name = "TBL_DomainSpoc_backup", schema = "refData")
public class TblDomainSpocBackup implements java.io.Serializable {

	private TblDomainSpocBackupId id;

	public TblDomainSpocBackup() {
	}

	public TblDomainSpocBackup(TblDomainSpocBackupId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "domainSpocId", column = @Column(name = "DomainSpocID", nullable = false)),
			@AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID", nullable = false)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID", nullable = false)),
			@AttributeOverride(name = "servAreaId", column = @Column(name = "ServAreaID", nullable = false)),
			@AttributeOverride(name = "spoc", column = @Column(name = "Spoc", nullable = false, length = 250)),
			@AttributeOverride(name = "spocLevel", column = @Column(name = "SpocLevel", nullable = false, length = 20)),
			@AttributeOverride(name = "active", column = @Column(name = "Active", nullable = false)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", nullable = false, length = 7)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", nullable = false, length = 23)) })
	public TblDomainSpocBackupId getId() {
		return this.id;
	}

	public void setId(TblDomainSpocBackupId id) {
		this.id = id;
	}

}
