package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblDownTime generated by hbm2java
 */
@Entity
@Table(name = "TBL_DownTime", schema = "refData")
public class TblDownTime implements java.io.Serializable {

	private TblDownTimeId id;

	public TblDownTime() {
	}

	public TblDownTime(TblDownTimeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "isDown", column = @Column(name = "isDown", length = 100)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", length = 23)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", length = 23)),
			@AttributeOverride(name = "message", column = @Column(name = "Message")) })
	public TblDownTimeId getId() {
		return this.id;
	}

	public void setId(TblDownTimeId id) {
		this.id = id;
	}

}
