package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblExternalProjects generated by hbm2java
 */
@Entity
@Table(name = "TBL_EXTERNAL_PROJECTS", schema = "transactionalData")
public class TblExternalProjects implements java.io.Serializable {

	private int projectId;
	private String applicationName;
	private Serializable projectName;
	private Serializable projectType;
	private Serializable cpm;
	private Serializable projectCreator;
	private Integer opportunityId;
	private Date startDate;
	private Date endDate;
	private Serializable projectDescription;
	private Integer servAreaId;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;
	private Serializable status;
	private Serializable operationalManager;
	private Integer isDeleted;

	public TblExternalProjects() {
	}

	public TblExternalProjects(int projectId, Date startDate) {
		this.projectId = projectId;
		this.startDate = startDate;
	}

	public TblExternalProjects(int projectId, String applicationName, Serializable projectName,
			Serializable projectType, Serializable cpm, Serializable projectCreator, Integer opportunityId,
			Date startDate, Date endDate, Serializable projectDescription, Integer servAreaId, Serializable createdBy,
			Date createdOn, Serializable lastModifiedBy, Date lastModifiedOn, Serializable status,
			Serializable operationalManager, Integer isDeleted) {
		this.projectId = projectId;
		this.applicationName = applicationName;
		this.projectName = projectName;
		this.projectType = projectType;
		this.cpm = cpm;
		this.projectCreator = projectCreator;
		this.opportunityId = opportunityId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.projectDescription = projectDescription;
		this.servAreaId = servAreaId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
		this.status = status;
		this.operationalManager = operationalManager;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "ProjectID", unique = true, nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ApplicationName", length = 300)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "ProjectName")
	public Serializable getProjectName() {
		return this.projectName;
	}

	public void setProjectName(Serializable projectName) {
		this.projectName = projectName;
	}

	@Column(name = "ProjectType")
	public Serializable getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Serializable projectType) {
		this.projectType = projectType;
	}

	@Column(name = "CPM")
	public Serializable getCpm() {
		return this.cpm;
	}

	public void setCpm(Serializable cpm) {
		this.cpm = cpm;
	}

	@Column(name = "ProjectCreator")
	public Serializable getProjectCreator() {
		return this.projectCreator;
	}

	public void setProjectCreator(Serializable projectCreator) {
		this.projectCreator = projectCreator;
	}

	@Column(name = "OpportunityID")
	public Integer getOpportunityId() {
		return this.opportunityId;
	}

	public void setOpportunityId(Integer opportunityId) {
		this.opportunityId = opportunityId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "ProjectDescription")
	public Serializable getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(Serializable projectDescription) {
		this.projectDescription = projectDescription;
	}

	@Column(name = "ServAreaID")
	public Integer getServAreaId() {
		return this.servAreaId;
	}

	public void setServAreaId(Integer servAreaId) {
		this.servAreaId = servAreaId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "OperationalManager")
	public Serializable getOperationalManager() {
		return this.operationalManager;
	}

	public void setOperationalManager(Serializable operationalManager) {
		this.operationalManager = operationalManager;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
