package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TblExecutionPlanMaster generated by hbm2java
 */
@Entity
@Table(name = "TBL_ExecutionPlan_master", schema = "transactionalData")
public class TblExecutionPlanMaster implements java.io.Serializable {

	private int executionPlanId;
	private Integer version;
	private String planName;
	private int planSourceid;
	private String planExternalReference;
	private Integer projectId;
	private Boolean isactive;
	private String createdby;
	private Date createdOn;
	private String updatedBy;
	private Date lastupdatedon;
	private Serializable links;
	private Set<TblExecutionPlanDetails> tblExecutionPlanDetailses = new HashSet<TblExecutionPlanDetails>(0);

	public TblExecutionPlanMaster() {
	}

	public TblExecutionPlanMaster(int executionPlanId, String planName, int planSourceid, String planExternalReference,
			String createdby, String updatedBy) {
		this.executionPlanId = executionPlanId;
		this.planName = planName;
		this.planSourceid = planSourceid;
		this.planExternalReference = planExternalReference;
		this.createdby = createdby;
		this.updatedBy = updatedBy;
	}

	public TblExecutionPlanMaster(int executionPlanId, String planName, int planSourceid, String planExternalReference,
			Integer projectId, Boolean isactive, String createdby, Date createdOn, String updatedBy, Date lastupdatedon,
			Serializable links, Set<TblExecutionPlanDetails> tblExecutionPlanDetailses) {
		this.executionPlanId = executionPlanId;
		this.planName = planName;
		this.planSourceid = planSourceid;
		this.planExternalReference = planExternalReference;
		this.projectId = projectId;
		this.isactive = isactive;
		this.createdby = createdby;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.lastupdatedon = lastupdatedon;
		this.links = links;
		this.tblExecutionPlanDetailses = tblExecutionPlanDetailses;
	}

	@Id

	@Column(name = "executionPlanId", unique = true, nullable = false)
	public int getExecutionPlanId() {
		return this.executionPlanId;
	}

	public void setExecutionPlanId(int executionPlanId) {
		this.executionPlanId = executionPlanId;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "planName", nullable = false, length = 250)
	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	@Column(name = "planSourceid", nullable = false)
	public int getPlanSourceid() {
		return this.planSourceid;
	}

	public void setPlanSourceid(int planSourceid) {
		this.planSourceid = planSourceid;
	}

	@Column(name = "planExternalReference", nullable = false, length = 250)
	public String getPlanExternalReference() {
		return this.planExternalReference;
	}

	public void setPlanExternalReference(String planExternalReference) {
		this.planExternalReference = planExternalReference;
	}

	@Column(name = "projectId")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "isactive")
	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "createdby", nullable = false, length = 8)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updatedBy", nullable = false, length = 8)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdatedon", length = 23)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

	@Column(name = "links")
	public Serializable getLinks() {
		return this.links;
	}

	public void setLinks(Serializable links) {
		this.links = links;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblExecutionPlanMaster")
	public Set<TblExecutionPlanDetails> getTblExecutionPlanDetailses() {
		return this.tblExecutionPlanDetailses;
	}

	public void setTblExecutionPlanDetailses(Set<TblExecutionPlanDetails> tblExecutionPlanDetailses) {
		this.tblExecutionPlanDetailses = tblExecutionPlanDetailses;
	}

}
