package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblEmployeeFeedback generated by hbm2java
 */
@Entity
@Table(name = "TBL_EMPLOYEE_FEEDBACK", schema = "transactionalData")
public class TblEmployeeFeedback implements java.io.Serializable {

	private TblEmployeeFeedbackId id;

	public TblEmployeeFeedback() {
	}

	public TblEmployeeFeedback(TblEmployeeFeedbackId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 1024)),
			@AttributeOverride(name = "feedBack", column = @Column(name = "FeedBack")) })
	public TblEmployeeFeedbackId getId() {
		return this.id;
	}

	public void setId(TblEmployeeFeedbackId id) {
		this.id = id;
	}

}
