package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblExportedReportHistoryBk20180710 generated by hbm2java
 */
@Entity
@Table(name = "TBL_ExportedReportHistory_bk20180710", schema = "transactionalData")
public class TblExportedReportHistoryBk20180710 implements java.io.Serializable {

	private TblExportedReportHistoryBk20180710Id id;

	public TblExportedReportHistoryBk20180710() {
	}

	public TblExportedReportHistoryBk20180710(TblExportedReportHistoryBk20180710Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "exportedReportHistory", column = @Column(name = "ExportedReportHistory", nullable = false)),
			@AttributeOverride(name = "reportName", column = @Column(name = "ReportName", length = 100)),
			@AttributeOverride(name = "reportFile", column = @Column(name = "reportFile", length = 100)),
			@AttributeOverride(name = "fileUplodedOn", column = @Column(name = "FileUplodedON", length = 23)),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedON", length = 23)),
			@AttributeOverride(name = "isActive", column = @Column(name = "IsActive")),
			@AttributeOverride(name = "description", column = @Column(name = "description", length = 100)),
			@AttributeOverride(name = "query", column = @Column(name = "query")) })
	public TblExportedReportHistoryBk20180710Id getId() {
		return this.id;
	}

	public void setId(TblExportedReportHistoryBk20180710Id id) {
		this.id = id;
	}

}
