package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblEmployees generated by hbm2java
 */
@Entity
@Table(name = "TBL_Employees", schema = "refData")
public class TblEmployees implements java.io.Serializable {

	private TblEmployeesId id;

	public TblEmployees() {
	}

	public TblEmployees(TblEmployeesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeName", column = @Column(name = "EmployeeName", nullable = false, length = 500)),
			@AttributeOverride(name = "signum", column = @Column(name = "Signum", nullable = false, length = 8)),
			@AttributeOverride(name = "personnelNumber", column = @Column(name = "PersonnelNumber", nullable = false)),
			@AttributeOverride(name = "gender", column = @Column(name = "Gender", length = 8)),
			@AttributeOverride(name = "positionId", column = @Column(name = "PositionId")),
			@AttributeOverride(name = "costCenter", column = @Column(name = "CostCenter", nullable = false)),
			@AttributeOverride(name = "unit", column = @Column(name = "Unit", length = 100)),
			@AttributeOverride(name = "managerSignum", column = @Column(name = "ManagerSignum", length = 8)),
			@AttributeOverride(name = "isLineManager", column = @Column(name = "IsLineManager", length = 10)),
			@AttributeOverride(name = "employeeGroup", column = @Column(name = "EmployeeGroup", length = 30)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 100)),
			@AttributeOverride(name = "companyName", column = @Column(name = "CompanyName", length = 150)),
			@AttributeOverride(name = "fso", column = @Column(name = "FSO", length = 15)),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName", length = 100)),
			@AttributeOverride(name = "parentUnit", column = @Column(name = "ParentUnit", length = 150)),
			@AttributeOverride(name = "jobName", column = @Column(name = "JobName", length = 50)),
			@AttributeOverride(name = "jobStage", column = @Column(name = "JobStage", length = 50)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 100)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 100)),
			@AttributeOverride(name = "functionalArea", column = @Column(name = "FunctionalArea", length = 100)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 100)),
			@AttributeOverride(name = "industryVertical", column = @Column(name = "IndustryVertical", length = 100)),
			@AttributeOverride(name = "employeeEmailId", column = @Column(name = "EmployeeEmailID", length = 100)),
			@AttributeOverride(name = "contactNumber", column = @Column(name = "ContactNumber", length = 13)),
			@AttributeOverride(name = "jobRoleFamily", column = @Column(name = "JobRoleFamily", length = 50)),
			@AttributeOverride(name = "city", column = @Column(name = "City", length = 100)),
			@AttributeOverride(name = "hrlocation", column = @Column(name = "HRLocation", length = 100)),
			@AttributeOverride(name = "officeBuilding", column = @Column(name = "OfficeBuilding", length = 100)),
			@AttributeOverride(name = "floor", column = @Column(name = "Floor", length = 50)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", nullable = false, length = 8)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", nullable = false, length = 23)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", nullable = false, length = 8)),
			@AttributeOverride(name = "lastModifiedOn", column = @Column(name = "LastModifiedOn", nullable = false, length = 23)) })
	public TblEmployeesId getId() {
		return this.id;
	}

	public void setId(TblEmployeesId id) {
		this.id = id;
	}

}
