package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblEmployeesCertification generated by hbm2java
 */
@Entity
@Table(name = "TBL_EmployeesCertification", schema = "refData")
public class TblEmployeesCertification implements java.io.Serializable {

	private int id;
	private String signum;
	private String competenceDomain;
	private String competenceSubDomain;
	private Date certificationDate;
	private Date certificationEndDate;
	private int certificateextId;
	private Date uploadedOn;

	public TblEmployeesCertification() {
	}

	public TblEmployeesCertification(int id, String signum, int certificateextId, Date uploadedOn) {
		this.id = id;
		this.signum = signum;
		this.certificateextId = certificateextId;
		this.uploadedOn = uploadedOn;
	}

	public TblEmployeesCertification(int id, String signum, String competenceDomain, String competenceSubDomain,
			Date certificationDate, Date certificationEndDate, int certificateextId, Date uploadedOn) {
		this.id = id;
		this.signum = signum;
		this.competenceDomain = competenceDomain;
		this.competenceSubDomain = competenceSubDomain;
		this.certificationDate = certificationDate;
		this.certificationEndDate = certificationEndDate;
		this.certificateextId = certificateextId;
		this.uploadedOn = uploadedOn;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Signum", nullable = false, length = 7)
	public String getSignum() {
		return this.signum;
	}

	public void setSignum(String signum) {
		this.signum = signum;
	}

	@Column(name = "CompetenceDomain", length = 100)
	public String getCompetenceDomain() {
		return this.competenceDomain;
	}

	public void setCompetenceDomain(String competenceDomain) {
		this.competenceDomain = competenceDomain;
	}

	@Column(name = "CompetenceSubDomain", length = 100)
	public String getCompetenceSubDomain() {
		return this.competenceSubDomain;
	}

	public void setCompetenceSubDomain(String competenceSubDomain) {
		this.competenceSubDomain = competenceSubDomain;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CertificationDate", length = 10)
	public Date getCertificationDate() {
		return this.certificationDate;
	}

	public void setCertificationDate(Date certificationDate) {
		this.certificationDate = certificationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CertificationEndDate", length = 10)
	public Date getCertificationEndDate() {
		return this.certificationEndDate;
	}

	public void setCertificationEndDate(Date certificationEndDate) {
		this.certificationEndDate = certificationEndDate;
	}

	@Column(name = "CERTIFICATEExtID", nullable = false)
	public int getCertificateextId() {
		return this.certificateextId;
	}

	public void setCertificateextId(int certificateextId) {
		this.certificateextId = certificateextId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UploadedOn", nullable = false, length = 23)
	public Date getUploadedOn() {
		return this.uploadedOn;
	}

	public void setUploadedOn(Date uploadedOn) {
		this.uploadedOn = uploadedOn;
	}

}
