package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblExecutionPlanDetails generated by hbm2java
 */
@Entity
@Table(name = "TBL_ExecutionPlan_details", schema = "transactionalData")
public class TblExecutionPlanDetails implements java.io.Serializable {

	private int executionPlanDetailId;
	private TblExecutionPlanMaster tblExecutionPlanMaster;
	private int workFlowVersionNo;
	private String taskJson;
	private Long tasknumber;
	private Boolean isRoot;
	private Integer scopeid;
	private Integer subactivityId;
	private Integer duration;
	private Set<TblExecutionPlanFlow> tblExecutionPlanFlows = new HashSet<TblExecutionPlanFlow>(0);

	public TblExecutionPlanDetails() {
	}

	public TblExecutionPlanDetails(int executionPlanDetailId, TblExecutionPlanMaster tblExecutionPlanMaster,
			int workFlowVersionNo) {
		this.executionPlanDetailId = executionPlanDetailId;
		this.tblExecutionPlanMaster = tblExecutionPlanMaster;
		this.workFlowVersionNo = workFlowVersionNo;
	}

	public TblExecutionPlanDetails(int executionPlanDetailId, TblExecutionPlanMaster tblExecutionPlanMaster,
			int workFlowVersionNo, String taskJson, Long tasknumber, Boolean isRoot, Integer scopeid,
			Integer subactivityId, Integer duration, Set<TblExecutionPlanFlow> tblExecutionPlanFlows) {
		this.executionPlanDetailId = executionPlanDetailId;
		this.tblExecutionPlanMaster = tblExecutionPlanMaster;
		this.workFlowVersionNo = workFlowVersionNo;
		this.taskJson = taskJson;
		this.tasknumber = tasknumber;
		this.isRoot = isRoot;
		this.scopeid = scopeid;
		this.subactivityId = subactivityId;
		this.duration = duration;
		this.tblExecutionPlanFlows = tblExecutionPlanFlows;
	}

	@Id

	@Column(name = "executionPlanDetailId", unique = true, nullable = false)
	public int getExecutionPlanDetailId() {
		return this.executionPlanDetailId;
	}

	public void setExecutionPlanDetailId(int executionPlanDetailId) {
		this.executionPlanDetailId = executionPlanDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "executionPlanId", nullable = false)
	public TblExecutionPlanMaster getTblExecutionPlanMaster() {
		return this.tblExecutionPlanMaster;
	}

	public void setTblExecutionPlanMaster(TblExecutionPlanMaster tblExecutionPlanMaster) {
		this.tblExecutionPlanMaster = tblExecutionPlanMaster;
	}

	@Column(name = "workFlowVersionNo", nullable = false)
	public int getWorkFlowVersionNo() {
		return this.workFlowVersionNo;
	}

	public void setWorkFlowVersionNo(int workFlowVersionNo) {
		this.workFlowVersionNo = workFlowVersionNo;
	}

	@Column(name = "taskJson", length = 2000)
	public String getTaskJson() {
		return this.taskJson;
	}

	public void setTaskJson(String taskJson) {
		this.taskJson = taskJson;
	}

	@Column(name = "tasknumber")
	public Long getTasknumber() {
		return this.tasknumber;
	}

	public void setTasknumber(Long tasknumber) {
		this.tasknumber = tasknumber;
	}

	@Column(name = "isRoot")
	public Boolean getIsRoot() {
		return this.isRoot;
	}

	public void setIsRoot(Boolean isRoot) {
		this.isRoot = isRoot;
	}

	@Column(name = "scopeid")
	public Integer getScopeid() {
		return this.scopeid;
	}

	public void setScopeid(Integer scopeid) {
		this.scopeid = scopeid;
	}

	@Column(name = "subactivityId")
	public Integer getSubactivityId() {
		return this.subactivityId;
	}

	public void setSubactivityId(Integer subactivityId) {
		this.subactivityId = subactivityId;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblExecutionPlanDetails")
	public Set<TblExecutionPlanFlow> getTblExecutionPlanFlows() {
		return this.tblExecutionPlanFlows;
	}

	public void setTblExecutionPlanFlows(Set<TblExecutionPlanFlow> tblExecutionPlanFlows) {
		this.tblExecutionPlanFlows = tblExecutionPlanFlows;
	}

}
