package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblFlowchartStepDetails generated by hbm2java
 */
@Entity
@Table(name = "TBL_FLOWCHART_STEP_DETAILS", schema = "transactionalData")
public class TblFlowchartStepDetails implements java.io.Serializable {

	private TblFlowchartStepDetailsId id;

	public TblFlowchartStepDetails() {
	}

	public TblFlowchartStepDetails(TblFlowchartStepDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fcstepDetailsId", column = @Column(name = "FCStepDetailsID", nullable = false)),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID")),
			@AttributeOverride(name = "stepId", column = @Column(name = "StepID")),
			@AttributeOverride(name = "stepName", column = @Column(name = "StepName", length = 1024)),
			@AttributeOverride(name = "taskId", column = @Column(name = "TaskID")),
			@AttributeOverride(name = "task", column = @Column(name = "Task", length = 1024)),
			@AttributeOverride(name = "executionType", column = @Column(name = "ExecutionType", length = 1024)),
			@AttributeOverride(name = "avgEstdEffort", column = @Column(name = "AvgEstdEffort", precision = 53, scale = 0)),
			@AttributeOverride(name = "toolId", column = @Column(name = "ToolID")),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "taskReason", column = @Column(name = "TaskReason", length = 1024)),
			@AttributeOverride(name = "ordering", column = @Column(name = "Ordering")),
			@AttributeOverride(name = "versionNumber", column = @Column(name = "VersionNumber")),
			@AttributeOverride(name = "rpaId", column = @Column(name = "RpaID")),
			@AttributeOverride(name = "masterTask", column = @Column(name = "MasterTask", length = 1024)),
			@AttributeOverride(name = "isIssue", column = @Column(name = "isIssue")) })
	public TblFlowchartStepDetailsId getId() {
		return this.id;
	}

	public void setId(TblFlowchartStepDetailsId id) {
		this.id = id;
	}

}
