package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblFlowchartJsonUpdateStatus generated by hbm2java
 */
@Entity
@Table(name = "TBL_FLOWCHART_JSON_UPDATE_STATUS", schema = "transactionalData")
public class TblFlowchartJsonUpdateStatus implements java.io.Serializable {

	private TblFlowchartJsonUpdateStatusId id;

	public TblFlowchartJsonUpdateStatus() {
	}

	public TblFlowchartJsonUpdateStatus(TblFlowchartJsonUpdateStatusId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "statusId", column = @Column(name = "StatusID", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "subactivityFlowchartDefId", column = @Column(name = "SubactivityFlowchartDefID")),
			@AttributeOverride(name = "versionNumber", column = @Column(name = "VersionNumber")),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 64)) })
	public TblFlowchartJsonUpdateStatusId getId() {
		return this.id;
	}

	public void setId(TblFlowchartJsonUpdateStatusId id) {
		this.id = id;
	}

}
