package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblFlowchartStepDetailsDecision generated by hbm2java
 */
@Entity
@Table(name = "TBL_FLOWCHART_STEP_DETAILS_DECISION", schema = "transactionalData")
public class TblFlowchartStepDetailsDecision implements java.io.Serializable {

	private TblFlowchartStepDetailsDecisionId id;

	public TblFlowchartStepDetailsDecision() {
	}

	public TblFlowchartStepDetailsDecision(TblFlowchartStepDetailsDecisionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "Project_ID")),
			@AttributeOverride(name = "subactivityId", column = @Column(name = "Subactivity_ID")),
			@AttributeOverride(name = "subactivityFlowchartId", column = @Column(name = "Subactivity_Flowchart_ID")),
			@AttributeOverride(name = "flowchartVersion", column = @Column(name = "Flowchart_Version")),
			@AttributeOverride(name = "parentId", column = @Column(name = "Parent_id")),
			@AttributeOverride(name = "type", column = @Column(name = "Type")),
			@AttributeOverride(name = "text", column = @Column(name = "text")) })
	public TblFlowchartStepDetailsDecisionId getId() {
		return this.id;
	}

	public void setId(TblFlowchartStepDetailsDecisionId id) {
		this.id = id;
	}

}
