package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblHeatmapsDb generated by hbm2java
 */
@Entity
@Table(name = "TBL_HEATMAPS_DB", schema = "refData")
public class TblHeatmapsDb implements java.io.Serializable {

	private TblHeatmapsDbId id;

	public TblHeatmapsDb() {
	}

	public TblHeatmapsDb(TblHeatmapsDbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "orderId", column = @Column(name = "OrderId", nullable = false)),
			@AttributeOverride(name = "heatMapsLevel", column = @Column(name = "HeatMapsLevel", nullable = false, length = 128)),
			@AttributeOverride(name = "columnName", column = @Column(name = "ColumnName", nullable = false, length = 128)) })
	public TblHeatmapsDbId getId() {
		return this.id;
	}

	public void setId(TblHeatmapsDbId id) {
		this.id = id;
	}

}
