package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblIsfconnections generated by hbm2java
 */
@Entity
@Table(name = "TBL_ISFConnections", schema = "transactionalData")
public class TblIsfconnections implements java.io.Serializable {

	private long connectionId;
	private String clientConnectionId;
	private String clientType;
	private String signumId;
	private String clientPage;
	private Boolean isConnected;
	private Date transactionOn;

	public TblIsfconnections() {
	}

	public TblIsfconnections(long connectionId) {
		this.connectionId = connectionId;
	}

	public TblIsfconnections(long connectionId, String clientConnectionId, String clientType, String signumId,
			String clientPage, Boolean isConnected, Date transactionOn) {
		this.connectionId = connectionId;
		this.clientConnectionId = clientConnectionId;
		this.clientType = clientType;
		this.signumId = signumId;
		this.clientPage = clientPage;
		this.isConnected = isConnected;
		this.transactionOn = transactionOn;
	}

	@Id

	@Column(name = "ConnectionID", unique = true, nullable = false)
	public long getConnectionId() {
		return this.connectionId;
	}

	public void setConnectionId(long connectionId) {
		this.connectionId = connectionId;
	}

	@Column(name = "ClientConnectionID", length = 200)
	public String getClientConnectionId() {
		return this.clientConnectionId;
	}

	public void setClientConnectionId(String clientConnectionId) {
		this.clientConnectionId = clientConnectionId;
	}

	@Column(name = "ClientType", length = 50)
	public String getClientType() {
		return this.clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	@Column(name = "SignumID", length = 7)
	public String getSignumId() {
		return this.signumId;
	}

	public void setSignumId(String signumId) {
		this.signumId = signumId;
	}

	@Column(name = "ClientPage", length = 200)
	public String getClientPage() {
		return this.clientPage;
	}

	public void setClientPage(String clientPage) {
		this.clientPage = clientPage;
	}

	@Column(name = "IsConnected")
	public Boolean getIsConnected() {
		return this.isConnected;
	}

	public void setIsConnected(Boolean isConnected) {
		this.isConnected = isConnected;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TransactionOn", length = 23)
	public Date getTransactionOn() {
		return this.transactionOn;
	}

	public void setTransactionOn(Date transactionOn) {
		this.transactionOn = transactionOn;
	}

}
