package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblIntegrationSourcesId generated by hbm2java
 */
@Embeddable
public class TblIntegrationSourcesId implements java.io.Serializable {

	private int sourceId;
	private String sourceName;

	public TblIntegrationSourcesId() {
	}

	public TblIntegrationSourcesId(int sourceId, String sourceName) {
		this.sourceId = sourceId;
		this.sourceName = sourceName;
	}

	@Column(name = "sourceId", nullable = false)
	public int getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(int sourceId) {
		this.sourceId = sourceId;
	}

	@Column(name = "sourceName", nullable = false, length = 250)
	public String getSourceName() {
		return this.sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblIntegrationSourcesId))
			return false;
		TblIntegrationSourcesId castOther = (TblIntegrationSourcesId) other;

		return (this.getSourceId() == castOther.getSourceId()) && ((this.getSourceName() == castOther.getSourceName())
				|| (this.getSourceName() != null && castOther.getSourceName() != null
						&& this.getSourceName().equals(castOther.getSourceName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSourceId();
		result = 37 * result + (getSourceName() == null ? 0 : this.getSourceName().hashCode());
		return result;
	}

}
