package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblIntegrationSources generated by hbm2java
 */
@Entity
@Table(name = "TBL_IntegrationSources", schema = "refData")
public class TblIntegrationSources implements java.io.Serializable {

	private TblIntegrationSourcesId id;

	public TblIntegrationSources() {
	}

	public TblIntegrationSources(TblIntegrationSourcesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "sourceId", column = @Column(name = "sourceId", nullable = false)),
			@AttributeOverride(name = "sourceName", column = @Column(name = "sourceName", nullable = false, length = 250)) })
	public TblIntegrationSourcesId getId() {
		return this.id;
	}

	public void setId(TblIntegrationSourcesId id) {
		this.id = id;
	}

}
