package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblIsfdesktopUpdatesId generated by hbm2java
 */
@Embeddable
public class TblIsfdesktopUpdatesId implements java.io.Serializable {

	private int isfdesktopUpdatesId;
	private String updateType;
	private String version;
	private Date updatedOn;
	private Boolean active;

	public TblIsfdesktopUpdatesId() {
	}

	public TblIsfdesktopUpdatesId(int isfdesktopUpdatesId) {
		this.isfdesktopUpdatesId = isfdesktopUpdatesId;
	}

	public TblIsfdesktopUpdatesId(int isfdesktopUpdatesId, String updateType, String version, Date updatedOn,
			Boolean active) {
		this.isfdesktopUpdatesId = isfdesktopUpdatesId;
		this.updateType = updateType;
		this.version = version;
		this.updatedOn = updatedOn;
		this.active = active;
	}

	@Column(name = "ISFDesktopUpdatesID", nullable = false)
	public int getIsfdesktopUpdatesId() {
		return this.isfdesktopUpdatesId;
	}

	public void setIsfdesktopUpdatesId(int isfdesktopUpdatesId) {
		this.isfdesktopUpdatesId = isfdesktopUpdatesId;
	}

	@Column(name = "UpdateType", length = 10)
	public String getUpdateType() {
		return this.updateType;
	}

	public void setUpdateType(String updateType) {
		this.updateType = updateType;
	}

	@Column(name = "Version", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "UpdatedOn", length = 23)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblIsfdesktopUpdatesId))
			return false;
		TblIsfdesktopUpdatesId castOther = (TblIsfdesktopUpdatesId) other;

		return (this.getIsfdesktopUpdatesId() == castOther.getIsfdesktopUpdatesId())
				&& ((this.getUpdateType() == castOther.getUpdateType()) || (this.getUpdateType() != null
						&& castOther.getUpdateType() != null && this.getUpdateType().equals(castOther.getUpdateType())))
				&& ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())))
				&& ((this.getUpdatedOn() == castOther.getUpdatedOn()) || (this.getUpdatedOn() != null
						&& castOther.getUpdatedOn() != null && this.getUpdatedOn().equals(castOther.getUpdatedOn())))
				&& ((this.getActive() == castOther.getActive()) || (this.getActive() != null
						&& castOther.getActive() != null && this.getActive().equals(castOther.getActive())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIsfdesktopUpdatesId();
		result = 37 * result + (getUpdateType() == null ? 0 : this.getUpdateType().hashCode());
		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result + (getUpdatedOn() == null ? 0 : this.getUpdatedOn().hashCode());
		result = 37 * result + (getActive() == null ? 0 : this.getActive().hashCode());
		return result;
	}

}
