package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblJobStages generated by hbm2java
 */
@Entity
@Table(name = "TBL_JobStages", schema = "refData")
public class TblJobStages implements java.io.Serializable {

	private int jobStageId;
	private Serializable jobStageName;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;
	private boolean active;
	private Set<TblResourceRequests> tblResourceRequestses = new HashSet<TblResourceRequests>(0);

	public TblJobStages() {
	}

	public TblJobStages(int jobStageId, Date createdOn, Date lastModifiedOn, boolean active) {
		this.jobStageId = jobStageId;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
		this.active = active;
	}

	public TblJobStages(int jobStageId, Serializable jobStageName, Serializable createdBy, Date createdOn,
			Serializable lastModifiedBy, Date lastModifiedOn, boolean active,
			Set<TblResourceRequests> tblResourceRequestses) {
		this.jobStageId = jobStageId;
		this.jobStageName = jobStageName;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
		this.active = active;
		this.tblResourceRequestses = tblResourceRequestses;
	}

	@Id

	@Column(name = "JobStageID", unique = true, nullable = false)
	public int getJobStageId() {
		return this.jobStageId;
	}

	public void setJobStageId(int jobStageId) {
		this.jobStageId = jobStageId;
	}

	@Column(name = "JobStageName")
	public Serializable getJobStageName() {
		return this.jobStageName;
	}

	public void setJobStageName(Serializable jobStageName) {
		this.jobStageName = jobStageName;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", nullable = false, length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblJobStages")
	public Set<TblResourceRequests> getTblResourceRequestses() {
		return this.tblResourceRequestses;
	}

	public void setTblResourceRequestses(Set<TblResourceRequests> tblResourceRequestses) {
		this.tblResourceRequestses = tblResourceRequestses;
	}

}
