package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblJsonIssue generated by hbm2java
 */
@Entity
@Table(name = "TBL_JSON_ISSUE", schema = "transactionalData")
public class TblJsonIssue implements java.io.Serializable {

	private TblJsonIssueId id;

	public TblJsonIssue() {
	}

	public TblJsonIssue(TblJsonIssueId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectid", column = @Column(name = "projectid", nullable = false)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID", nullable = false)),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID", nullable = false)),
			@AttributeOverride(name = "active", column = @Column(name = "Active", nullable = false)),
			@AttributeOverride(name = "versionNumber", column = @Column(name = "VersionNumber", nullable = false)),
			@AttributeOverride(name = "workFlowName", column = @Column(name = "WorkFlowName", nullable = false, length = 100)),
			@AttributeOverride(name = "jsonStepCnt", column = @Column(name = "jsonStepCnt", nullable = false)),
			@AttributeOverride(name = "stepTableStepCnt", column = @Column(name = "stepTableStepCnt", nullable = false)),
			@AttributeOverride(name = "stepTableTotalStepCnt", column = @Column(name = "stepTableTotalStepCnt", nullable = false)) })
	public TblJsonIssueId getId() {
		return this.id;
	}

	public void setId(TblJsonIssueId id) {
		this.id = id;
	}

}
