package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblMarketareas generated by hbm2java
 */
@Entity
@Table(name = "TBL_MARKETAREAS", schema = "refData")
public class TblMarketareas implements java.io.Serializable {

	private int marketAreaId;
	private String marketAreaName;
	private String description;
	private Set<TblCountries> tblCountrieses = new HashSet<TblCountries>(0);
	private Set<TblOpportunity> tblOpportunities = new HashSet<TblOpportunity>(0);

	public TblMarketareas() {
	}

	public TblMarketareas(int marketAreaId) {
		this.marketAreaId = marketAreaId;
	}

	public TblMarketareas(int marketAreaId, String marketAreaName, String description,
			Set<TblCountries> tblCountrieses, Set<TblOpportunity> tblOpportunities) {
		this.marketAreaId = marketAreaId;
		this.marketAreaName = marketAreaName;
		this.description = description;
		this.tblCountrieses = tblCountrieses;
		this.tblOpportunities = tblOpportunities;
	}

	@Id

	@Column(name = "MarketAreaID", unique = true, nullable = false)
	public int getMarketAreaId() {
		return this.marketAreaId;
	}

	public void setMarketAreaId(int marketAreaId) {
		this.marketAreaId = marketAreaId;
	}

	@Column(name = "MarketAreaName")
	public String getMarketAreaName() {
		return this.marketAreaName;
	}

	public void setMarketAreaName(String marketAreaName) {
		this.marketAreaName = marketAreaName;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblMarketareas")
	public Set<TblCountries> getTblCountrieses() {
		return this.tblCountrieses;
	}

	public void setTblCountrieses(Set<TblCountries> tblCountrieses) {
		this.tblCountrieses = tblCountrieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblMarketareas")
	public Set<TblOpportunity> getTblOpportunities() {
		return this.tblOpportunities;
	}

	public void setTblOpportunities(Set<TblOpportunity> tblOpportunities) {
		this.tblOpportunities = tblOpportunities;
	}

}
