package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblMhr generated by hbm2java
 */
@Entity
@Table(name = "TBL_MHR", schema = "refData")
public class TblMhr implements java.io.Serializable {

	private String signum;
	private int id;
	private int mhr;

	public TblMhr() {
	}

	public TblMhr(String signum, int id, int mhr) {
		this.signum = signum;
		this.id = id;
		this.mhr = mhr;
	}

	@Id

	@Column(name = "signum", unique = true, nullable = false, length = 200)
	public String getSignum() {
		return this.signum;
	}

	public void setSignum(String signum) {
		this.signum = signum;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "mhr", nullable = false)
	public int getMhr() {
		return this.mhr;
	}

	public void setMhr(int mhr) {
		this.mhr = mhr;
	}

}
