package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblNetworkElementId generated by hbm2java
 */
@Embeddable
public class TblNetworkElementId implements java.io.Serializable {

	private int networkElementId;
	private Integer projectId;
	private Integer domainSubDomainId;
	private Integer technologyId;
	private Integer vendorId;
	private String elementType;
	private String type;
	private String name;
	private String softwareRelease;
	private String market;
	private String sector;
	private String latitude;
	private String longitude;

	public TblNetworkElementId() {
	}

	public TblNetworkElementId(int networkElementId) {
		this.networkElementId = networkElementId;
	}

	public TblNetworkElementId(int networkElementId, Integer projectId, Integer domainSubDomainId, Integer technologyId,
			Integer vendorId, String elementType, String type, String name, String softwareRelease, String market,
			String sector, String latitude, String longitude) {
		this.networkElementId = networkElementId;
		this.projectId = projectId;
		this.domainSubDomainId = domainSubDomainId;
		this.technologyId = technologyId;
		this.vendorId = vendorId;
		this.elementType = elementType;
		this.type = type;
		this.name = name;
		this.softwareRelease = softwareRelease;
		this.market = market;
		this.sector = sector;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Column(name = "NetworkElementID", nullable = false)
	public int getNetworkElementId() {
		return this.networkElementId;
	}

	public void setNetworkElementId(int networkElementId) {
		this.networkElementId = networkElementId;
	}

	@Column(name = "ProjectID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "DomainSubDomainID")
	public Integer getDomainSubDomainId() {
		return this.domainSubDomainId;
	}

	public void setDomainSubDomainId(Integer domainSubDomainId) {
		this.domainSubDomainId = domainSubDomainId;
	}

	@Column(name = "TechnologyID")
	public Integer getTechnologyId() {
		return this.technologyId;
	}

	public void setTechnologyId(Integer technologyId) {
		this.technologyId = technologyId;
	}

	@Column(name = "VendorID")
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "ElementType", length = 256)
	public String getElementType() {
		return this.elementType;
	}

	public void setElementType(String elementType) {
		this.elementType = elementType;
	}

	@Column(name = "Type", length = 256)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Name", length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Software_Release", length = 256)
	public String getSoftwareRelease() {
		return this.softwareRelease;
	}

	public void setSoftwareRelease(String softwareRelease) {
		this.softwareRelease = softwareRelease;
	}

	@Column(name = "Market", length = 1024)
	public String getMarket() {
		return this.market;
	}

	public void setMarket(String market) {
		this.market = market;
	}

	@Column(name = "Sector", length = 512)
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "Latitude", length = 256)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", length = 256)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblNetworkElementId))
			return false;
		TblNetworkElementId castOther = (TblNetworkElementId) other;

		return (this.getNetworkElementId() == castOther.getNetworkElementId())
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getDomainSubDomainId() == castOther.getDomainSubDomainId())
						|| (this.getDomainSubDomainId() != null && castOther.getDomainSubDomainId() != null
								&& this.getDomainSubDomainId().equals(castOther.getDomainSubDomainId())))
				&& ((this.getTechnologyId() == castOther.getTechnologyId())
						|| (this.getTechnologyId() != null && castOther.getTechnologyId() != null
								&& this.getTechnologyId().equals(castOther.getTechnologyId())))
				&& ((this.getVendorId() == castOther.getVendorId()) || (this.getVendorId() != null
						&& castOther.getVendorId() != null && this.getVendorId().equals(castOther.getVendorId())))
				&& ((this.getElementType() == castOther.getElementType())
						|| (this.getElementType() != null && castOther.getElementType() != null
								&& this.getElementType().equals(castOther.getElementType())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getSoftwareRelease() == castOther.getSoftwareRelease())
						|| (this.getSoftwareRelease() != null && castOther.getSoftwareRelease() != null
								&& this.getSoftwareRelease().equals(castOther.getSoftwareRelease())))
				&& ((this.getMarket() == castOther.getMarket()) || (this.getMarket() != null
						&& castOther.getMarket() != null && this.getMarket().equals(castOther.getMarket())))
				&& ((this.getSector() == castOther.getSector()) || (this.getSector() != null
						&& castOther.getSector() != null && this.getSector().equals(castOther.getSector())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this.getLatitude() != null
						&& castOther.getLatitude() != null && this.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this.getLongitude() != null
						&& castOther.getLongitude() != null && this.getLongitude().equals(castOther.getLongitude())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNetworkElementId();
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getDomainSubDomainId() == null ? 0 : this.getDomainSubDomainId().hashCode());
		result = 37 * result + (getTechnologyId() == null ? 0 : this.getTechnologyId().hashCode());
		result = 37 * result + (getVendorId() == null ? 0 : this.getVendorId().hashCode());
		result = 37 * result + (getElementType() == null ? 0 : this.getElementType().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getSoftwareRelease() == null ? 0 : this.getSoftwareRelease().hashCode());
		result = 37 * result + (getMarket() == null ? 0 : this.getMarket().hashCode());
		result = 37 * result + (getSector() == null ? 0 : this.getSector().hashCode());
		result = 37 * result + (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result + (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		return result;
	}

}
