package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblNetworkElement generated by hbm2java
 */
@Entity
@Table(name = "TBL_NETWORK_ELEMENT", schema = "transactionalData")
public class TblNetworkElement implements java.io.Serializable {

	private TblNetworkElementId id;

	public TblNetworkElement() {
	}

	public TblNetworkElement(TblNetworkElementId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "networkElementId", column = @Column(name = "NetworkElementID", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "domainSubDomainId", column = @Column(name = "DomainSubDomainID")),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "vendorId", column = @Column(name = "VendorID")),
			@AttributeOverride(name = "elementType", column = @Column(name = "ElementType", length = 256)),
			@AttributeOverride(name = "type", column = @Column(name = "Type", length = 256)),
			@AttributeOverride(name = "name", column = @Column(name = "Name", length = 256)),
			@AttributeOverride(name = "softwareRelease", column = @Column(name = "Software_Release", length = 256)),
			@AttributeOverride(name = "market", column = @Column(name = "Market", length = 1024)),
			@AttributeOverride(name = "sector", column = @Column(name = "Sector", length = 512)),
			@AttributeOverride(name = "latitude", column = @Column(name = "Latitude", length = 256)),
			@AttributeOverride(name = "longitude", column = @Column(name = "Longitude", length = 256)) })
	public TblNetworkElementId getId() {
		return this.id;
	}

	public void setId(TblNetworkElementId id) {
		this.id = id;
	}

}
