package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblNotificationsConfig generated by hbm2java
 */
@Entity
@Table(name = "TBL_NOTIFICATIONS_CONFIG", schema = "transactionalData")
public class TblNotificationsConfig implements java.io.Serializable {

	private int templateId;
	private String templateName;
	private String templateText;
	private String subject;
	private String to;
	private String cc;

	public TblNotificationsConfig() {
	}

	public TblNotificationsConfig(int templateId, String templateName, String templateText) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.templateText = templateText;
	}

	public TblNotificationsConfig(int templateId, String templateName, String templateText, String subject, String to,
			String cc) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.templateText = templateText;
		this.subject = subject;
		this.to = to;
		this.cc = cc;
	}

	@Id

	@Column(name = "templateId", unique = true, nullable = false)
	public int getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(int templateId) {
		this.templateId = templateId;
	}

	@Column(name = "templateName", nullable = false, length = 300)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "templateText", nullable = false, length = 4000)
	public String getTemplateText() {
		return this.templateText;
	}

	public void setTemplateText(String templateText) {
		this.templateText = templateText;
	}

	@Column(name = "subject", length = 300)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "to", length = 300)
	public String getTo() {
		return this.to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	@Column(name = "cc", length = 100)
	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

}
