package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblNetworkElementFilePath generated by hbm2java
 */
@Entity
@Table(name = "TBL_NETWORK_ELEMENT_FILE_PATH", schema = "transactionalData")
public class TblNetworkElementFilePath implements java.io.Serializable {

	private TblNetworkElementFilePathId id;

	public TblNetworkElementFilePath() {
	}

	public TblNetworkElementFilePath(TblNetworkElementFilePathId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "filePath", column = @Column(name = "FilePath")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 1024)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", length = 1024)) })
	public TblNetworkElementFilePathId getId() {
		return this.id;
	}

	public void setId(TblNetworkElementFilePathId id) {
		this.id = id;
	}

}
