package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblOrganisation generated by hbm2java
 */
@Entity
@Table(name = "TBL_ORGANISATION", schema = "refData")
public class TblOrganisation implements java.io.Serializable {

	private TblOrganisationId id;

	public TblOrganisation() {
	}

	public TblOrganisation(TblOrganisationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "organisationId", column = @Column(name = "OrganisationID", nullable = false)),
			@AttributeOverride(name = "organisation", column = @Column(name = "Organisation", length = 1024)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")) })
	public TblOrganisationId getId() {
		return this.id;
	}

	public void setId(TblOrganisationId id) {
		this.id = id;
	}

}
