package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TblOpportunity generated by hbm2java
 */
@Entity
@Table(name = "TBL_OPPORTUNITY", schema = "transactionalData", uniqueConstraints = @UniqueConstraint(columnNames = "OpportunityCode"))
public class TblOpportunity implements java.io.Serializable {

	private int opportunityId;
	private TblCompanies tblCompanies;
	private TblCountries tblCountries;
	private TblCustomers tblCustomers;
	private TblMarketareas tblMarketareas;
	private String opportunityName;
	private String opportunityCode;
	private Boolean active;
	private Set<TblProjects> tblProjectses = new HashSet<TblProjects>(0);

	public TblOpportunity() {
	}

	public TblOpportunity(int opportunityId, String opportunityCode) {
		this.opportunityId = opportunityId;
		this.opportunityCode = opportunityCode;
	}

	public TblOpportunity(int opportunityId, TblCompanies tblCompanies, TblCountries tblCountries,
			TblCustomers tblCustomers, TblMarketareas tblMarketareas, String opportunityName,
			String opportunityCode, Boolean active, Set<TblProjects> tblProjectses) {
		this.opportunityId = opportunityId;
		this.tblCompanies = tblCompanies;
		this.tblCountries = tblCountries;
		this.tblCustomers = tblCustomers;
		this.tblMarketareas = tblMarketareas;
		this.opportunityName = opportunityName;
		this.opportunityCode = opportunityCode;
		this.active = active;
		this.tblProjectses = tblProjectses;
	}

	@Id

	@Column(name = "OpportunityID", unique = true, nullable = false)
	public int getOpportunityId() {
		return this.opportunityId;
	}

	public void setOpportunityId(int opportunityId) {
		this.opportunityId = opportunityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CompanyID")
	public TblCompanies getTblCompanies() {
		return this.tblCompanies;
	}

	public void setTblCompanies(TblCompanies tblCompanies) {
		this.tblCompanies = tblCompanies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CountryID")
	public TblCountries getTblCountries() {
		return this.tblCountries;
	}

	public void setTblCountries(TblCountries tblCountries) {
		this.tblCountries = tblCountries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID")
	public TblCustomers getTblCustomers() {
		return this.tblCustomers;
	}

	public void setTblCustomers(TblCustomers tblCustomers) {
		this.tblCustomers = tblCustomers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MarketAreaID")
	public TblMarketareas getTblMarketareas() {
		return this.tblMarketareas;
	}

	public void setTblMarketareas(TblMarketareas tblMarketareas) {
		this.tblMarketareas = tblMarketareas;
	}

	@Column(name = "OpportunityName")
	public String getOpportunityName() {
		return this.opportunityName;
	}

	public void setOpportunityName(String opportunityName) {
		this.opportunityName = opportunityName;
	}

	@Column(name = "OpportunityCode", unique = true, nullable = false, length = 100)
	public String getOpportunityCode() {
		return this.opportunityCode;
	}

	public void setOpportunityCode(String opportunityCode) {
		this.opportunityCode = opportunityCode;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOpportunity")
	public Set<TblProjects> getTblProjectses() {
		return this.tblProjectses;
	}

	public void setTblProjectses(Set<TblProjects> tblProjectses) {
		this.tblProjectses = tblProjectses;
	}

}
