package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOnsiteLocations generated by hbm2java
 */
@Entity
@Table(name = "TBL_OnsiteLocations", schema = "refData")
public class TblOnsiteLocations implements java.io.Serializable {

	private int onsiteLocationId;
	private Serializable locationName;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;
	private Set<TblResourceRequests> tblResourceRequestses = new HashSet<TblResourceRequests>(0);

	public TblOnsiteLocations() {
	}

	public TblOnsiteLocations(int onsiteLocationId, Date createdOn, Date lastModifiedOn) {
		this.onsiteLocationId = onsiteLocationId;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
	}

	public TblOnsiteLocations(int onsiteLocationId, Serializable locationName, Serializable createdBy, Date createdOn,
			Serializable lastModifiedBy, Date lastModifiedOn, Set<TblResourceRequests> tblResourceRequestses) {
		this.onsiteLocationId = onsiteLocationId;
		this.locationName = locationName;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
		this.tblResourceRequestses = tblResourceRequestses;
	}

	@Id

	@Column(name = "OnsiteLocationID", unique = true, nullable = false)
	public int getOnsiteLocationId() {
		return this.onsiteLocationId;
	}

	public void setOnsiteLocationId(int onsiteLocationId) {
		this.onsiteLocationId = onsiteLocationId;
	}

	@Column(name = "LocationName")
	public Serializable getLocationName() {
		return this.locationName;
	}

	public void setLocationName(Serializable locationName) {
		this.locationName = locationName;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", nullable = false, length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOnsiteLocations")
	public Set<TblResourceRequests> getTblResourceRequestses() {
		return this.tblResourceRequestses;
	}

	public void setTblResourceRequestses(Set<TblResourceRequests> tblResourceRequestses) {
		this.tblResourceRequestses = tblResourceRequestses;
	}

}
