package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProjectdocuments generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROJECTDOCUMENTS", schema = "transactionalData")
public class TblProjectdocuments implements java.io.Serializable {

	private int projectDocumentId;
	private TblProjects tblProjects;
	private Serializable documentType;
	private Serializable documentLinks;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;
	private Boolean isActive;

	public TblProjectdocuments() {
	}

	public TblProjectdocuments(int projectDocumentId) {
		this.projectDocumentId = projectDocumentId;
	}

	public TblProjectdocuments(int projectDocumentId, TblProjects tblProjects, Serializable documentType,
			Serializable documentLinks, Serializable createdBy, Date createdOn, Serializable lastModifiedBy,
			Date lastModifiedOn, Boolean isActive) {
		this.projectDocumentId = projectDocumentId;
		this.tblProjects = tblProjects;
		this.documentType = documentType;
		this.documentLinks = documentLinks;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
		this.isActive = isActive;
	}

	@Id

	@Column(name = "ProjectDocumentID", unique = true, nullable = false)
	public int getProjectDocumentId() {
		return this.projectDocumentId;
	}

	public void setProjectDocumentId(int projectDocumentId) {
		this.projectDocumentId = projectDocumentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID")
	public TblProjects getTblProjects() {
		return this.tblProjects;
	}

	public void setTblProjects(TblProjects tblProjects) {
		this.tblProjects = tblProjects;
	}

	@Column(name = "DocumentType")
	public Serializable getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(Serializable documentType) {
		this.documentType = documentType;
	}

	@Column(name = "DocumentLinks")
	public Serializable getDocumentLinks() {
		return this.documentLinks;
	}

	public void setDocumentLinks(Serializable documentLinks) {
		this.documentLinks = documentLinks;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
