package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblParallelTaskConfigId generated by hbm2java
 */
@Embeddable
public class TblParallelTaskConfigId implements java.io.Serializable {

	private int id;
	private Integer projectId;
	private Integer maxManualTask;
	private Integer maxAutomaticTask;
	private Date lastModifiedDate;
	private String signumId;

	public TblParallelTaskConfigId() {
	}

	public TblParallelTaskConfigId(int id) {
		this.id = id;
	}

	public TblParallelTaskConfigId(int id, Integer projectId, Integer maxManualTask, Integer maxAutomaticTask,
			Date lastModifiedDate, String signumId) {
		this.id = id;
		this.projectId = projectId;
		this.maxManualTask = maxManualTask;
		this.maxAutomaticTask = maxAutomaticTask;
		this.lastModifiedDate = lastModifiedDate;
		this.signumId = signumId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ProjectID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "MaxManualTask")
	public Integer getMaxManualTask() {
		return this.maxManualTask;
	}

	public void setMaxManualTask(Integer maxManualTask) {
		this.maxManualTask = maxManualTask;
	}

	@Column(name = "MaxAutomaticTask")
	public Integer getMaxAutomaticTask() {
		return this.maxAutomaticTask;
	}

	public void setMaxAutomaticTask(Integer maxAutomaticTask) {
		this.maxAutomaticTask = maxAutomaticTask;
	}

	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "SignumID", length = 512)
	public String getSignumId() {
		return this.signumId;
	}

	public void setSignumId(String signumId) {
		this.signumId = signumId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblParallelTaskConfigId))
			return false;
		TblParallelTaskConfigId castOther = (TblParallelTaskConfigId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getMaxManualTask() == castOther.getMaxManualTask())
						|| (this.getMaxManualTask() != null && castOther.getMaxManualTask() != null
								&& this.getMaxManualTask().equals(castOther.getMaxManualTask())))
				&& ((this.getMaxAutomaticTask() == castOther.getMaxAutomaticTask())
						|| (this.getMaxAutomaticTask() != null && castOther.getMaxAutomaticTask() != null
								&& this.getMaxAutomaticTask().equals(castOther.getMaxAutomaticTask())))
				&& ((this.getLastModifiedDate() == castOther.getLastModifiedDate())
						|| (this.getLastModifiedDate() != null && castOther.getLastModifiedDate() != null
								&& this.getLastModifiedDate().equals(castOther.getLastModifiedDate())))
				&& ((this.getSignumId() == castOther.getSignumId()) || (this.getSignumId() != null
						&& castOther.getSignumId() != null && this.getSignumId().equals(castOther.getSignumId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getMaxManualTask() == null ? 0 : this.getMaxManualTask().hashCode());
		result = 37 * result + (getMaxAutomaticTask() == null ? 0 : this.getMaxAutomaticTask().hashCode());
		result = 37 * result + (getLastModifiedDate() == null ? 0 : this.getLastModifiedDate().hashCode());
		result = 37 * result + (getSignumId() == null ? 0 : this.getSignumId().hashCode());
		return result;
	}

}
