package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProjectApprovals generated by hbm2java
 */
@Entity
@Table(name = "TBL_ProjectApprovals", schema = "transactionalData")
public class TblProjectApprovals implements java.io.Serializable {

	private int projectApprovalId;
	private TblProjects tblProjects;
	private Serializable approverSignum;
	private Integer approvedOrRejected;
	private Date approvedOrRejectedOn;
	private Serializable requestedBy;
	private Date requestedOn;

	public TblProjectApprovals() {
	}

	public TblProjectApprovals(int projectApprovalId) {
		this.projectApprovalId = projectApprovalId;
	}

	public TblProjectApprovals(int projectApprovalId, TblProjects tblProjects, Serializable approverSignum,
			Integer approvedOrRejected, Date approvedOrRejectedOn, Serializable requestedBy, Date requestedOn) {
		this.projectApprovalId = projectApprovalId;
		this.tblProjects = tblProjects;
		this.approverSignum = approverSignum;
		this.approvedOrRejected = approvedOrRejected;
		this.approvedOrRejectedOn = approvedOrRejectedOn;
		this.requestedBy = requestedBy;
		this.requestedOn = requestedOn;
	}

	@Id

	@Column(name = "ProjectApprovalID", unique = true, nullable = false)
	public int getProjectApprovalId() {
		return this.projectApprovalId;
	}

	public void setProjectApprovalId(int projectApprovalId) {
		this.projectApprovalId = projectApprovalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID")
	public TblProjects getTblProjects() {
		return this.tblProjects;
	}

	public void setTblProjects(TblProjects tblProjects) {
		this.tblProjects = tblProjects;
	}

	@Column(name = "ApproverSignum")
	public Serializable getApproverSignum() {
		return this.approverSignum;
	}

	public void setApproverSignum(Serializable approverSignum) {
		this.approverSignum = approverSignum;
	}

	@Column(name = "ApprovedOrRejected")
	public Integer getApprovedOrRejected() {
		return this.approvedOrRejected;
	}

	public void setApprovedOrRejected(Integer approvedOrRejected) {
		this.approvedOrRejected = approvedOrRejected;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ApprovedOrRejectedOn", length = 23)
	public Date getApprovedOrRejectedOn() {
		return this.approvedOrRejectedOn;
	}

	public void setApprovedOrRejectedOn(Date approvedOrRejectedOn) {
		this.approvedOrRejectedOn = approvedOrRejectedOn;
	}

	@Column(name = "RequestedBy")
	public Serializable getRequestedBy() {
		return this.requestedBy;
	}

	public void setRequestedBy(Serializable requestedBy) {
		this.requestedBy = requestedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RequestedOn", length = 23)
	public Date getRequestedOn() {
		return this.requestedOn;
	}

	public void setRequestedOn(Date requestedOn) {
		this.requestedOn = requestedOn;
	}

}
