package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblParallelTaskConfig generated by hbm2java
 */
@Entity
@Table(name = "TBL_PARALLEL_TASK_CONFIG", schema = "transactionalData")
public class TblParallelTaskConfig implements java.io.Serializable {

	private TblParallelTaskConfigId id;

	public TblParallelTaskConfig() {
	}

	public TblParallelTaskConfig(TblParallelTaskConfigId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "maxManualTask", column = @Column(name = "MaxManualTask")),
			@AttributeOverride(name = "maxAutomaticTask", column = @Column(name = "MaxAutomaticTask")),
			@AttributeOverride(name = "lastModifiedDate", column = @Column(name = "LastModifiedDate", length = 23)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 512)) })
	public TblParallelTaskConfigId getId() {
		return this.id;
	}

	public void setId(TblParallelTaskConfigId id) {
		this.id = id;
	}

}
