package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblProposedWorkEfforts generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROPOSED_WORK_EFFORTS", schema = "transactionalData")
public class TblProposedWorkEfforts implements java.io.Serializable {

	private TblProposedWorkEffortsId id;

	public TblProposedWorkEfforts() {
	}

	public TblProposedWorkEfforts(TblProposedWorkEffortsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "workEffortId", column = @Column(name = "WorkEffortID")),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", precision = 53, scale = 0)),
			@AttributeOverride(name = "duration", column = @Column(name = "Duration", precision = 53, scale = 0)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", length = 10)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", length = 10)) })
	public TblProposedWorkEffortsId getId() {
		return this.id;
	}

	public void setId(TblProposedWorkEffortsId id) {
		this.id = id;
	}

}
