package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProjectscope generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROJECTSCOPE", schema = "transactionalData")
public class TblProjectscope implements java.io.Serializable {

	private int projectScopeId;
	private TblProjects tblProjects;
	private Serializable scopeName;
	private Date startDate;
	private Date endDate;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Boolean active;
	private String requestType;
	private Set<TblProjectscopedetail> tblProjectscopedetails = new HashSet<TblProjectscopedetail>(0);

	public TblProjectscope() {
	}

	public TblProjectscope(int projectScopeId, Date startDate, Date endDate, String requestType) {
		this.projectScopeId = projectScopeId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.requestType = requestType;
	}

	public TblProjectscope(int projectScopeId, TblProjects tblProjects, Serializable scopeName, Date startDate,
			Date endDate, String createdBy, Date createdDate, String lastModifiedBy, Date lastModifiedDate,
			Boolean active, String requestType, Set<TblProjectscopedetail> tblProjectscopedetails) {
		this.projectScopeId = projectScopeId;
		this.tblProjects = tblProjects;
		this.scopeName = scopeName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.active = active;
		this.requestType = requestType;
		this.tblProjectscopedetails = tblProjectscopedetails;
	}

	@Id

	@Column(name = "ProjectScopeID", unique = true, nullable = false)
	public int getProjectScopeId() {
		return this.projectScopeId;
	}

	public void setProjectScopeId(int projectScopeId) {
		this.projectScopeId = projectScopeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID")
	public TblProjects getTblProjects() {
		return this.tblProjects;
	}

	public void setTblProjects(TblProjects tblProjects) {
		this.tblProjects = tblProjects;
	}

	@Column(name = "ScopeName")
	public Serializable getScopeName() {
		return this.scopeName;
	}

	public void setScopeName(Serializable scopeName) {
		this.scopeName = scopeName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", nullable = false, length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "CreatedBy", length = 256)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LastModifiedBy", length = 256)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "requestType", nullable = false, length = 100)
	public String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjectscope")
	public Set<TblProjectscopedetail> getTblProjectscopedetails() {
		return this.tblProjectscopedetails;
	}

	public void setTblProjectscopedetails(Set<TblProjectscopedetail> tblProjectscopedetails) {
		this.tblProjectscopedetails = tblProjectscopedetails;
	}

}
