package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblProjectNodetypeDb generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROJECT_NODETYPE_DB", schema = "transactionalData")
public class TblProjectNodetypeDb implements java.io.Serializable {

	private TblProjectNodetypeDbId id;

	public TblProjectNodetypeDb() {
	}

	public TblProjectNodetypeDb(TblProjectNodetypeDbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectNodeTypeId", column = @Column(name = "ProjectNodeTypeID", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "nodeType", column = @Column(name = "NodeType", length = 1024)) })
	public TblProjectNodetypeDbId getId() {
		return this.id;
	}

	public void setId(TblProjectNodetypeDbId id) {
		this.id = id;
	}

}
