package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProjects generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROJECTS", schema = "transactionalData")
public class TblProjects implements java.io.Serializable {

	private Integer projectId;
	private TblOpportunity tblOpportunity;
	private String projectName;
	private String projectType;
	private String cpm;
	private String projectCreator;
	private Date startDate;
	private Date endDate;
	private String projectDescription;
	private Integer servAreaId;
	private String createdBy;
	private Date createdOn;
	private String lastModifiedBy;
	private Date lastModifiedOn;
	private String status;
	private String operationalManager;
	private Integer isDeleted;
	private Set<TblRpaRequest> tblRpaRequests = new HashSet<TblRpaRequest>(0);
	private Set<TblResourceRequests> tblResourceRequestses = new HashSet<TblResourceRequests>(0);
	private Set<TblProjectdocuments> tblProjectdocumentses = new HashSet<TblProjectdocuments>(0);
	private Set<TblProjectscope> tblProjectscopes = new HashSet<TblProjectscope>(0);
	private Set<TblWorkFlowUserProficiency> tblWorkFlowUserProficiencies = new HashSet<TblWorkFlowUserProficiency>(0);
	private Set<TblBookedResource> tblBookedResources = new HashSet<TblBookedResource>(0);
	private Set<TblProjectApprovals> tblProjectApprovalses = new HashSet<TblProjectApprovals>(0);

	
	public TblProjects() {
	}

	public TblProjects(Integer projectId, Date startDate) {
		this.projectId = projectId;
		this.startDate = startDate;
	}

	public TblProjects(Integer projectId, TblOpportunity tblOpportunity, String projectName, String projectType,
			String cpm, String projectCreator, Date startDate, Date endDate,
			String projectDescription, Integer servAreaId, String createdBy, Date createdOn,
			String lastModifiedBy, Date lastModifiedOn, String status, String operationalManager,
			Integer isDeleted, Set<TblRpaRequest> tblRpaRequests, Set<TblResourceRequests> tblResourceRequestses,
			Set<TblProjectdocuments> tblProjectdocumentses, Set<TblProjectscope> tblProjectscopes,
			Set<TblWorkFlowUserProficiency> tblWorkFlowUserProficiencies, Set<TblBookedResource> tblBookedResources,
			Set<TblProjectApprovals> tblProjectApprovalses,
			Set<TblWorkOrder> tblWorkOrder,
			Set<TblSubactivityFlowchartDef> tblSubactivityFlowchartDef) {
		this.projectId = projectId;
		this.tblOpportunity = tblOpportunity;
		this.projectName = projectName;
		this.projectType = projectType;
		this.cpm = cpm;
		this.projectCreator = projectCreator;
		this.startDate = startDate;
		this.endDate = endDate;
		this.projectDescription = projectDescription;
		this.servAreaId = servAreaId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
		this.status = status;
		this.operationalManager = operationalManager;
		this.isDeleted = isDeleted;
		this.tblRpaRequests = tblRpaRequests;
		this.tblResourceRequestses = tblResourceRequestses;
		this.tblProjectdocumentses = tblProjectdocumentses;
		this.tblProjectscopes = tblProjectscopes;
		this.tblWorkFlowUserProficiencies = tblWorkFlowUserProficiencies;
		this.tblBookedResources = tblBookedResources;
		this.tblProjectApprovalses = tblProjectApprovalses;

	}

	@Id

	@Column(name = "ProjectID", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityID")
	public TblOpportunity getTblOpportunity() {
		return this.tblOpportunity;
	}

	public void setTblOpportunity(TblOpportunity tblOpportunity) {
		this.tblOpportunity = tblOpportunity;
	}

	@Column(name = "ProjectName")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "ProjectType")
	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	@Column(name = "CPM")
	public String getCpm() {
		return this.cpm;
	}

	public void setCpm(String cpm) {
		this.cpm = cpm;
	}

	@Column(name = "ProjectCreator")
	public String getProjectCreator() {
		return this.projectCreator;
	}

	public void setProjectCreator(String projectCreator) {
		this.projectCreator = projectCreator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "ProjectDescription")
	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	@Column(name = "ServAreaID")
	public Integer getServAreaId() {
		return this.servAreaId;
	}

	public void setServAreaId(Integer servAreaId) {
		this.servAreaId = servAreaId;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@Column(name = "Status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "OperationalManager")
	public String getOperationalManager() {
		return this.operationalManager;
	}

	public void setOperationalManager(String operationalManager) {
		this.operationalManager = operationalManager;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjects")
	public Set<TblRpaRequest> getTblRpaRequests() {
		return this.tblRpaRequests;
	}

	public void setTblRpaRequests(Set<TblRpaRequest> tblRpaRequests) {
		this.tblRpaRequests = tblRpaRequests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjects")
	public Set<TblResourceRequests> getTblResourceRequestses() {
		return this.tblResourceRequestses;
	}

	public void setTblResourceRequestses(Set<TblResourceRequests> tblResourceRequestses) {
		this.tblResourceRequestses = tblResourceRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjects")
	public Set<TblProjectdocuments> getTblProjectdocumentses() {
		return this.tblProjectdocumentses;
	}

	public void setTblProjectdocumentses(Set<TblProjectdocuments> tblProjectdocumentses) {
		this.tblProjectdocumentses = tblProjectdocumentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjects")
	public Set<TblProjectscope> getTblProjectscopes() {
		return this.tblProjectscopes;
	}

	public void setTblProjectscopes(Set<TblProjectscope> tblProjectscopes) {
		this.tblProjectscopes = tblProjectscopes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjects")
	public Set<TblWorkFlowUserProficiency> getTblWorkFlowUserProficiencies() {
		return this.tblWorkFlowUserProficiencies;
	}

	public void setTblWorkFlowUserProficiencies(Set<TblWorkFlowUserProficiency> tblWorkFlowUserProficiencies) {
		this.tblWorkFlowUserProficiencies = tblWorkFlowUserProficiencies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjects")
	public Set<TblBookedResource> getTblBookedResources() {
		return this.tblBookedResources;
	}

	public void setTblBookedResources(Set<TblBookedResource> tblBookedResources) {
		this.tblBookedResources = tblBookedResources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProjects")
	public Set<TblProjectApprovals> getTblProjectApprovalses() {
		return this.tblProjectApprovalses;
	}

	public void setTblProjectApprovalses(Set<TblProjectApprovals> tblProjectApprovalses) {
		this.tblProjectApprovalses = tblProjectApprovalses;
	}



}
