package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblResourceRequests generated by hbm2java
 */
@Entity
@Table(name = "TBL_ResourceRequests", schema = "transactionalData")
public class TblResourceRequests implements java.io.Serializable {

	private int resourceRequestId;
	private TblJobRoles tblJobRoles;
	private TblJobStages tblJobStages;
	private TblOnsiteLocations tblOnsiteLocations;
	private TblProjects tblProjects;
	private TblProjectscopedetail tblProjectscopedetail;
	private Serializable resourceType;
	private Serializable requestType;
	private int onsiteCount;
	private int remoteCount;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;
	private Boolean active;
	private Serializable resourceDescription;
	private Serializable onsiteLocation;
	private Serializable remoteLocation;
	private String city;
	private String country;
	private Double longitude;
	private Double latitude;
	private String timeZone;
	private Set<TblResourceRequestWorkEfforts> tblResourceRequestWorkEffortses = new HashSet<TblResourceRequestWorkEfforts>(
			0);
	private Set<TblResourceRequestCertifications> tblResourceRequestCertificationses = new HashSet<TblResourceRequestCertifications>(
			0);
	private Set<TblResourcePosition> tblResourcePositions = new HashSet<TblResourcePosition>(0);
	private Set<TblResourceRequestCompetences> tblResourceRequestCompetenceses = new HashSet<TblResourceRequestCompetences>(
			0);

	public TblResourceRequests() {
	}

	public TblResourceRequests(int resourceRequestId, int onsiteCount, int remoteCount, Date createdOn,
			Date lastModifiedOn) {
		this.resourceRequestId = resourceRequestId;
		this.onsiteCount = onsiteCount;
		this.remoteCount = remoteCount;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
	}

	public TblResourceRequests(int resourceRequestId, TblJobRoles tblJobRoles, TblJobStages tblJobStages,
			TblOnsiteLocations tblOnsiteLocations, TblProjects tblProjects, TblProjectscopedetail tblProjectscopedetail,
			Serializable resourceType, Serializable requestType, int onsiteCount, int remoteCount,
			Serializable createdBy, Date createdOn, Serializable lastModifiedBy, Date lastModifiedOn, Boolean active,
			Serializable resourceDescription, Serializable onsiteLocation, Serializable remoteLocation, String city,
			String country, Double longitude, Double latitude, String timeZone,
			Set<TblResourceRequestWorkEfforts> tblResourceRequestWorkEffortses,
			Set<TblResourceRequestCertifications> tblResourceRequestCertificationses,
			Set<TblResourcePosition> tblResourcePositions,
			Set<TblResourceRequestCompetences> tblResourceRequestCompetenceses) {
		this.resourceRequestId = resourceRequestId;
		this.tblJobRoles = tblJobRoles;
		this.tblJobStages = tblJobStages;
		this.tblOnsiteLocations = tblOnsiteLocations;
		this.tblProjects = tblProjects;
		this.tblProjectscopedetail = tblProjectscopedetail;
		this.resourceType = resourceType;
		this.requestType = requestType;
		this.onsiteCount = onsiteCount;
		this.remoteCount = remoteCount;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
		this.active = active;
		this.resourceDescription = resourceDescription;
		this.onsiteLocation = onsiteLocation;
		this.remoteLocation = remoteLocation;
		this.city = city;
		this.country = country;
		this.longitude = longitude;
		this.latitude = latitude;
		this.timeZone = timeZone;
		this.tblResourceRequestWorkEffortses = tblResourceRequestWorkEffortses;
		this.tblResourceRequestCertificationses = tblResourceRequestCertificationses;
		this.tblResourcePositions = tblResourcePositions;
		this.tblResourceRequestCompetenceses = tblResourceRequestCompetenceses;
	}

	@Id

	@Column(name = "ResourceRequestID", unique = true, nullable = false)
	public int getResourceRequestId() {
		return this.resourceRequestId;
	}

	public void setResourceRequestId(int resourceRequestId) {
		this.resourceRequestId = resourceRequestId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JobRoleID")
	public TblJobRoles getTblJobRoles() {
		return this.tblJobRoles;
	}

	public void setTblJobRoles(TblJobRoles tblJobRoles) {
		this.tblJobRoles = tblJobRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JobStageID")
	public TblJobStages getTblJobStages() {
		return this.tblJobStages;
	}

	public void setTblJobStages(TblJobStages tblJobStages) {
		this.tblJobStages = tblJobStages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OnsiteLocationID")
	public TblOnsiteLocations getTblOnsiteLocations() {
		return this.tblOnsiteLocations;
	}

	public void setTblOnsiteLocations(TblOnsiteLocations tblOnsiteLocations) {
		this.tblOnsiteLocations = tblOnsiteLocations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID")
	public TblProjects getTblProjects() {
		return this.tblProjects;
	}

	public void setTblProjects(TblProjects tblProjects) {
		this.tblProjects = tblProjects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectScopeDetailID")
	public TblProjectscopedetail getTblProjectscopedetail() {
		return this.tblProjectscopedetail;
	}

	public void setTblProjectscopedetail(TblProjectscopedetail tblProjectscopedetail) {
		this.tblProjectscopedetail = tblProjectscopedetail;
	}

	@Column(name = "ResourceType")
	public Serializable getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(Serializable resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "RequestType")
	public Serializable getRequestType() {
		return this.requestType;
	}

	public void setRequestType(Serializable requestType) {
		this.requestType = requestType;
	}

	@Column(name = "OnsiteCount", nullable = false)
	public int getOnsiteCount() {
		return this.onsiteCount;
	}

	public void setOnsiteCount(int onsiteCount) {
		this.onsiteCount = onsiteCount;
	}

	@Column(name = "RemoteCount", nullable = false)
	public int getRemoteCount() {
		return this.remoteCount;
	}

	public void setRemoteCount(int remoteCount) {
		this.remoteCount = remoteCount;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", nullable = false, length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "ResourceDescription")
	public Serializable getResourceDescription() {
		return this.resourceDescription;
	}

	public void setResourceDescription(Serializable resourceDescription) {
		this.resourceDescription = resourceDescription;
	}

	@Column(name = "OnsiteLocation")
	public Serializable getOnsiteLocation() {
		return this.onsiteLocation;
	}

	public void setOnsiteLocation(Serializable onsiteLocation) {
		this.onsiteLocation = onsiteLocation;
	}

	@Column(name = "RemoteLocation")
	public Serializable getRemoteLocation() {
		return this.remoteLocation;
	}

	public void setRemoteLocation(Serializable remoteLocation) {
		this.remoteLocation = remoteLocation;
	}

	@Column(name = "City")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "Latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "TimeZone")
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblResourceRequests")
	public Set<TblResourceRequestWorkEfforts> getTblResourceRequestWorkEffortses() {
		return this.tblResourceRequestWorkEffortses;
	}

	public void setTblResourceRequestWorkEffortses(Set<TblResourceRequestWorkEfforts> tblResourceRequestWorkEffortses) {
		this.tblResourceRequestWorkEffortses = tblResourceRequestWorkEffortses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblResourceRequests")
	public Set<TblResourceRequestCertifications> getTblResourceRequestCertificationses() {
		return this.tblResourceRequestCertificationses;
	}

	public void setTblResourceRequestCertificationses(
			Set<TblResourceRequestCertifications> tblResourceRequestCertificationses) {
		this.tblResourceRequestCertificationses = tblResourceRequestCertificationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblResourceRequests")
	public Set<TblResourcePosition> getTblResourcePositions() {
		return this.tblResourcePositions;
	}

	public void setTblResourcePositions(Set<TblResourcePosition> tblResourcePositions) {
		this.tblResourcePositions = tblResourcePositions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblResourceRequests")
	public Set<TblResourceRequestCompetences> getTblResourceRequestCompetenceses() {
		return this.tblResourceRequestCompetenceses;
	}

	public void setTblResourceRequestCompetenceses(Set<TblResourceRequestCompetences> tblResourceRequestCompetenceses) {
		this.tblResourceRequestCompetenceses = tblResourceRequestCompetenceses;
	}

}
