package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblRoleCapability generated by hbm2java
 */
@Entity
@Table(name = "TBL_ROLE_CAPABILITY", schema = "refData")
public class TblRoleCapability implements java.io.Serializable {

	private TblRoleCapabilityId id;

	public TblRoleCapability() {
	}

	public TblRoleCapability(TblRoleCapabilityId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roleCapabilityId", column = @Column(name = "RoleCapabilityID", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "RoleID")),
			@AttributeOverride(name = "capabilityPageId", column = @Column(name = "CapabilityPageID")),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "permission", column = @Column(name = "permission")) })
	public TblRoleCapabilityId getId() {
		return this.id;
	}

	public void setId(TblRoleCapabilityId id) {
		this.id = id;
	}

}
