package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRpaBotrequirement generated by hbm2java
 */
@Entity
@Table(name = "TBL_RPA_BOTTesting", schema = "transactionalData")
public class TblRpaBottesting implements java.io.Serializable {

	private int testId;
	private TblRpaRequest tblRpaRequest;
	private int isTestingSuccessful;
	private String status;
	private String createdBy;
	private Date createdOn;
	
	public TblRpaBottesting() {
	}

	public TblRpaBottesting(int testId, TblRpaRequest tblRpaRequest, String createdBy, Date createdOn, int isTestingSuccessful, String status) {
		this.testId = testId;
		this.tblRpaRequest = tblRpaRequest;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isTestingSuccessful= isTestingSuccessful;
		this.status= status;
	}

	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "TestId", unique = true, nullable = false)
	public int getTestId() {
		return this.testId;
	}

	public void setTestId(int testId) {
		this.testId = testId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "rpaRequestID", referencedColumnName = "rpaRequestID")	
	public TblRpaRequest getTblRpaRequest() {
		return this.tblRpaRequest;
	}

	public void setTblRpaRequest(TblRpaRequest tblRpaRequest) {
		this.tblRpaRequest = tblRpaRequest;
	}

	@Column(name = "CreatedBY", nullable = false, length = 10)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedON", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "isTestingSuccessful", nullable = false)
	public int getIsTestingSuccessful() {
		return this.isTestingSuccessful;
	}

	public void setIsTestingSuccessful(int isTestingSuccessful) {
		this.isTestingSuccessful = isTestingSuccessful;
	}

	@Column(name = "Status", nullable = false, length = 20)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
