package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblResourcePosition generated by hbm2java
 */
@Entity
@Table(name = "TBL_ResourcePosition", schema = "transactionalData")
public class TblResourcePosition implements java.io.Serializable {

	private int resourcePositionId;
	private TblResourceRequests tblResourceRequests;
	private String positionStatus;
	private Boolean isActivie;
	private Date inActivatedOn;
	private String crstatus;
	private String requestedBy;
	private Date requestedOn;
	private Date lastModifiedOn;
	private String lastModifiedBy;
	private Serializable remoteOnsite;
	private String comments;
	private Set<TblBookedResource> tblBookedResources = new HashSet<TblBookedResource>(0);

	public TblResourcePosition() {
	}

	public TblResourcePosition(int resourcePositionId, TblResourceRequests tblResourceRequests, String requestedBy,
			Date requestedOn) {
		this.resourcePositionId = resourcePositionId;
		this.tblResourceRequests = tblResourceRequests;
		this.requestedBy = requestedBy;
		this.requestedOn = requestedOn;
	}

	public TblResourcePosition(int resourcePositionId, TblResourceRequests tblResourceRequests, String positionStatus,
			Boolean isActivie, Date inActivatedOn, String crstatus, String requestedBy, Date requestedOn,
			Date lastModifiedOn, String lastModifiedBy, Serializable remoteOnsite, String comments,
			Set<TblBookedResource> tblBookedResources) {
		this.resourcePositionId = resourcePositionId;
		this.tblResourceRequests = tblResourceRequests;
		this.positionStatus = positionStatus;
		this.isActivie = isActivie;
		this.inActivatedOn = inActivatedOn;
		this.crstatus = crstatus;
		this.requestedBy = requestedBy;
		this.requestedOn = requestedOn;
		this.lastModifiedOn = lastModifiedOn;
		this.lastModifiedBy = lastModifiedBy;
		this.remoteOnsite = remoteOnsite;
		this.comments = comments;
		this.tblBookedResources = tblBookedResources;
	}

	@Id

	@Column(name = "ResourcePositionID", unique = true, nullable = false)
	public int getResourcePositionId() {
		return this.resourcePositionId;
	}

	public void setResourcePositionId(int resourcePositionId) {
		this.resourcePositionId = resourcePositionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ResourceRequestID", nullable = false)
	public TblResourceRequests getTblResourceRequests() {
		return this.tblResourceRequests;
	}

	public void setTblResourceRequests(TblResourceRequests tblResourceRequests) {
		this.tblResourceRequests = tblResourceRequests;
	}

	@Column(name = "PositionStatus", length = 100)
	public String getPositionStatus() {
		return this.positionStatus;
	}

	public void setPositionStatus(String positionStatus) {
		this.positionStatus = positionStatus;
	}

	@Column(name = "IsActivie")
	public Boolean getIsActivie() {
		return this.isActivie;
	}

	public void setIsActivie(Boolean isActivie) {
		this.isActivie = isActivie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "InActivatedOn", length = 10)
	public Date getInActivatedOn() {
		return this.inActivatedOn;
	}

	public void setInActivatedOn(Date inActivatedOn) {
		this.inActivatedOn = inActivatedOn;
	}

	@Column(name = "CRStatus", length = 100)
	public String getCrstatus() {
		return this.crstatus;
	}

	public void setCrstatus(String crstatus) {
		this.crstatus = crstatus;
	}

	@Column(name = "RequestedBy", nullable = false, length = 8)
	public String getRequestedBy() {
		return this.requestedBy;
	}

	public void setRequestedBy(String requestedBy) {
		this.requestedBy = requestedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RequestedOn", nullable = false, length = 23)
	public Date getRequestedOn() {
		return this.requestedOn;
	}

	public void setRequestedOn(Date requestedOn) {
		this.requestedOn = requestedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@Column(name = "LastModifiedBy", length = 8)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "Remote_Onsite")
	public Serializable getRemoteOnsite() {
		return this.remoteOnsite;
	}

	public void setRemoteOnsite(Serializable remoteOnsite) {
		this.remoteOnsite = remoteOnsite;
	}

	@Column(name = "Comments", length = 1000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblResourcePosition")
	public Set<TblBookedResource> getTblBookedResources() {
		return this.tblBookedResources;
	}

	public void setTblBookedResources(Set<TblBookedResource> tblBookedResources) {
		this.tblBookedResources = tblBookedResources;
	}

}
