package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import org.hibernate.annotations.NaturalId;

/**
 * TblRpaRequest generated by hbm2java
 */
@Entity
@Table(name = "TBL_RPA_REQUEST", schema = "transactionalData")
public class TblRpaRequest implements Serializable {


	private static final long serialVersionUID = 1L;
	private int systemId;
	@NaturalId
	private int rpaRequestId;
	private TblProjects tblProjects;
	private int workflowDefid;//
	private String wfstepid;
	private int subactivityId;//
	private int taskId;
	private String requestName;
	private String spocsignum;
	private String description;
	private int currentExecutioncountWeekly;
	private int currentAvgExecutiontime;
	private String requestStatus;
	private String createdBy;
	private Date createdOn;
	private String modifiedBy;
	private Date modifiedOn;
	private int isActive;
	private Set<TblRpaDeployedBot> tblRpaDeployedBot = new HashSet<TblRpaDeployedBot>(0);
	private Set<TblRpaBotstaging> tblRpaBotstagings = new HashSet<TblRpaBotstaging>(0);
	private Set<TblRpaBotrequirement> tblRpaBotrequirements = new HashSet<TblRpaBotrequirement>(0);
	private Set<TblRpaBottesting> tblRpaBottesting= new HashSet<TblRpaBottesting>(0);

	private String workFlowName;
	private String subactivityName;
	private String taskName;
	private Integer referenceBotId;
	private String videoURL;
	private boolean isInputRequired;
	private String stepID;
	private String stepName;
	private int wFID;

	
	@Transient
	public String getStepID() {
		return stepID;
	}

	public void setStepID(String stepID) {
		this.stepID = stepID;
	}

	@Transient
	public String getStepName() {
		return stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}
    
	@Transient
	public int getwFID() {
		return wFID;
	}

	public void setwFID(int wFID) {
		this.wFID = wFID;
	}

	public TblRpaRequest() {
	}

	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "SystemID", unique = true, nullable = false)
	public int getSystemId() {
		return systemId;
	}

	public TblRpaRequest(int systemId, int rpaRequestId, TblProjects tblProjects, int workflowDefid, String wfstepid,
			int subactivityId, int taskId, String requestName, String spocsignum, String description,
			int currentExecutioncountWeekly, int currentAvgExecutiontime, String requestStatus, String createdBy,
			Date createdOn, String modifiedBy, Date modifiedOn, int isActive, Set<TblRpaDeployedBot> tblRpaDeployedBot,
			Set<TblRpaBotstaging> tblRpaBotstagings, Set<TblRpaBotrequirement> tblRpaBotrequirements,
			Set<TblRpaBottesting> tblRpaBottesting, String workFlowName, String subactivityName, String taskName,
			Integer referenceBotId, String videoURL) {
		this.systemId = systemId;
		this.rpaRequestId = rpaRequestId;
		this.tblProjects = tblProjects;
		this.workflowDefid = workflowDefid;
		this.wfstepid = wfstepid;
		this.subactivityId = subactivityId;
		this.taskId = taskId;
		this.requestName = requestName;
		this.spocsignum = spocsignum;
		this.description = description;
		this.currentExecutioncountWeekly = currentExecutioncountWeekly;
		this.currentAvgExecutiontime = currentAvgExecutiontime;
		this.requestStatus = requestStatus;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isActive = isActive;
		this.tblRpaDeployedBot = tblRpaDeployedBot;
		this.tblRpaBotstagings = tblRpaBotstagings;
		this.tblRpaBotrequirements = tblRpaBotrequirements;
		this.tblRpaBottesting = tblRpaBottesting;
		this.workFlowName = workFlowName;
		this.subactivityName = subactivityName;
		this.taskName = taskName;
		this.referenceBotId = referenceBotId;
		this.videoURL = videoURL;
	}

	public void setSystemId(int systemId) {
		this.systemId = systemId;
	}
	
	
	@Generated( value = GenerationTime.ALWAYS ) 
	@Column(name = "rpaRequestID", unique = true, nullable = false)
	public int getRpaRequestId() {
		return this.rpaRequestId;
	}

	public void setRpaRequestId(int rpaRequestId) {
		this.rpaRequestId = rpaRequestId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID", nullable = false)
	public TblProjects getTblProjects() {
		return this.tblProjects;
	}

	public void setTblProjects(TblProjects tblProjects) {
		this.tblProjects = tblProjects;
	}

	@Column(name = "WorkflowDEFID", nullable = false)
	public int getWorkflowDefid() {
		return this.workflowDefid;
	}

	public void setWorkflowDefid(int workflowDefid) {
		this.workflowDefid = workflowDefid;
	}

	@Column(name = "WFSTEPID", nullable = false)
	public String getWfstepid() {
		return this.wfstepid;
	}

	public void setWfstepid(String wfstepid) {
		this.wfstepid = wfstepid;
	}

	@Column(name = "SubactivityID", nullable = false)
	public int getSubactivityId() {
		return this.subactivityId;
	}

	public void setSubactivityId(int subactivityId) {
		this.subactivityId = subactivityId;
	}

	@Column(name = "TaskID", nullable = false)
	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	@Column(name = "SPOCSignum", nullable = false, length = 10)
	public String getSpocsignum() {
		return this.spocsignum;
	}

	public void setSpocsignum(String spocsignum) {
		this.spocsignum = spocsignum;
	}

	@Column(name = "requestName", nullable = false, length = 100)
	public String getRequestName() {
		return this.requestName;
	}

	public void setRequestName(String requestName) {
		this.requestName = requestName;
	}

	@Column(name = "Description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CurrentExecutioncountWeekly", nullable = false)
	public int getCurrentExecutioncountWeekly() {
		return this.currentExecutioncountWeekly;
	}

	public void setCurrentExecutioncountWeekly(int currentExecutioncountWeekly) {
		this.currentExecutioncountWeekly = currentExecutioncountWeekly;
	}

	@Column(name = "CurrentAvgExecutiontime", nullable = false)
	public int getCurrentAvgExecutiontime() {
		return this.currentAvgExecutiontime;
	}

	public void setCurrentAvgExecutiontime(int currentAvgExecutiontime) {
		this.currentAvgExecutiontime = currentAvgExecutiontime;
	}

	@Column(name = "RequestStatus", nullable = false, length = 10)
	public String getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(String requestStatus) {
		this.requestStatus = requestStatus;
	}

	@Column(name = "CreatedBY", nullable = false, length = 10)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy", length = 10)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isActive", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRpaRequest")
	public Set<TblRpaBotstaging> getTblRpaBotstagings() {
		return this.tblRpaBotstagings;
	}

	public void setTblRpaBotstagings(Set<TblRpaBotstaging> tblRpaBotstagings) {
		this.tblRpaBotstagings = tblRpaBotstagings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRpaRequest")
	public Set<TblRpaBotrequirement> getTblRpaBotrequirements() {
		return this.tblRpaBotrequirements;
	}

	public void setTblRpaBotrequirements(Set<TblRpaBotrequirement> tblRpaBotrequirements) {
		this.tblRpaBotrequirements = tblRpaBotrequirements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRpaRequest")
	public Set<TblRpaBottesting> getTblRpaBottesting() {
		return this.tblRpaBottesting;
	}

	public void setTblRpaBottesting(Set<TblRpaBottesting> tblRpaBottesting) {
		this.tblRpaBottesting = tblRpaBottesting;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRpaRequest")
	public Set<TblRpaDeployedBot> getTblRpaDeployedBot() {
		return tblRpaDeployedBot;
	}

	public void setTblRpaDeployedBot(Set<TblRpaDeployedBot> tblRpaDeployedBot) {
		this.tblRpaDeployedBot = tblRpaDeployedBot;
	}

	@Column(name = "WorkFlowName", nullable = true)
	public String getWorkFlowName() {
		return workFlowName;
	}

	public void setWorkFlowName(String workFlowName) {
		this.workFlowName = workFlowName;
	}

	@Column(name = "SubactivityName", nullable = true)
	public String getSubactivityName() {
		return subactivityName;
	}

	public void setSubactivityName(String subactivityName) {
		this.subactivityName = subactivityName;
	}

	@Column(name = "TaskName", nullable = true)
	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "referenceBotId", nullable = true)
	public Integer getReferenceBotId() {
		return referenceBotId;
	}

	public void setReferenceBotId(Integer referenceBotId) {
		this.referenceBotId = referenceBotId;
	}

	@Column(name = "videoURL", nullable = true)
	public String getVideoURL() {
		return videoURL;
	}

	public void setVideoURL(String videoURL) {
		this.videoURL = videoURL;
	}

	@Column(name = "isInputRequired", nullable = false)
	public boolean getIsInputRequired() {
		return isInputRequired;
	}

	public void setIsInputRequired(boolean isInputRequired) {
		this.isInputRequired = isInputRequired;
	}
	
	
}
