package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblResourceStatus generated by hbm2java
 */
@Entity
@Table(name = "TBL_ResourceStatus", schema = "transactionalData")
public class TblResourceStatus implements java.io.Serializable {

	private int resourceStatusId;
	private Serializable resourceStatusName;
	private Serializable signum;
	private Date resignedOrTransferredDate;
	private Date releaseDate;
	private Serializable reason;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;

	public TblResourceStatus() {
	}

	public TblResourceStatus(int resourceStatusId, Date resignedOrTransferredDate, Date releaseDate, Date createdOn,
			Date lastModifiedOn) {
		this.resourceStatusId = resourceStatusId;
		this.resignedOrTransferredDate = resignedOrTransferredDate;
		this.releaseDate = releaseDate;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
	}

	public TblResourceStatus(int resourceStatusId, Serializable resourceStatusName, Serializable signum,
			Date resignedOrTransferredDate, Date releaseDate, Serializable reason, Serializable createdBy,
			Date createdOn, Serializable lastModifiedBy, Date lastModifiedOn) {
		this.resourceStatusId = resourceStatusId;
		this.resourceStatusName = resourceStatusName;
		this.signum = signum;
		this.resignedOrTransferredDate = resignedOrTransferredDate;
		this.releaseDate = releaseDate;
		this.reason = reason;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
	}

	@Id

	@Column(name = "ResourceStatusID", unique = true, nullable = false)
	public int getResourceStatusId() {
		return this.resourceStatusId;
	}

	public void setResourceStatusId(int resourceStatusId) {
		this.resourceStatusId = resourceStatusId;
	}

	@Column(name = "ResourceStatusName")
	public Serializable getResourceStatusName() {
		return this.resourceStatusName;
	}

	public void setResourceStatusName(Serializable resourceStatusName) {
		this.resourceStatusName = resourceStatusName;
	}

	@Column(name = "Signum")
	public Serializable getSignum() {
		return this.signum;
	}

	public void setSignum(Serializable signum) {
		this.signum = signum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ResignedOrTransferredDate", nullable = false, length = 23)
	public Date getResignedOrTransferredDate() {
		return this.resignedOrTransferredDate;
	}

	public void setResignedOrTransferredDate(Date resignedOrTransferredDate) {
		this.resignedOrTransferredDate = resignedOrTransferredDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReleaseDate", nullable = false, length = 23)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "Reason")
	public Serializable getReason() {
		return this.reason;
	}

	public void setReason(Serializable reason) {
		this.reason = reason;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", nullable = false, length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

}
