package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblReportsModuleSubModule generated by hbm2java
 */
@Entity
@Table(name = "TBL_Reports_Module_SubModule", schema = "refData")
public class TblReportsModuleSubModule implements java.io.Serializable {

	private int id;
	private String moduleName;
	private String subModuleName;
	private Set<TblReports> tblReportses = new HashSet<TblReports>(0);

	public TblReportsModuleSubModule() {
	}

	public TblReportsModuleSubModule(int id, String moduleName, String subModuleName) {
		this.id = id;
		this.moduleName = moduleName;
		this.subModuleName = subModuleName;
	}

	public TblReportsModuleSubModule(int id, String moduleName, String subModuleName, Set<TblReports> tblReportses) {
		this.id = id;
		this.moduleName = moduleName;
		this.subModuleName = subModuleName;
		this.tblReportses = tblReportses;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "moduleName", nullable = false, length = 300)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "subModuleName", nullable = false, length = 300)
	public String getSubModuleName() {
		return this.subModuleName;
	}

	public void setSubModuleName(String subModuleName) {
		this.subModuleName = subModuleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblReportsModuleSubModule")
	public Set<TblReports> getTblReportses() {
		return this.tblReportses;
	}

	public void setTblReportses(Set<TblReports> tblReportses) {
		this.tblReportses = tblReportses;
	}

}
