package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblResourceRequestWorkEfforts generated by hbm2java
 */
@Entity
@Table(name = "TBL_ResourceRequestWorkEfforts", schema = "transactionalData")
public class TblResourceRequestWorkEfforts implements java.io.Serializable {

	private int resourceRequestWorkEffortId;
	private TblResourceRequests tblResourceRequests;
	private Date startDate;
	private Date endDate;
	private int duration;
	private float ftepercent;
	private float hours;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;

	public TblResourceRequestWorkEfforts() {
	}

	public TblResourceRequestWorkEfforts(int resourceRequestWorkEffortId, Date startDate, Date endDate, int duration,
			float ftepercent, float hours, Date createdOn, Date lastModifiedOn) {
		this.resourceRequestWorkEffortId = resourceRequestWorkEffortId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.duration = duration;
		this.ftepercent = ftepercent;
		this.hours = hours;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
	}

	public TblResourceRequestWorkEfforts(int resourceRequestWorkEffortId, TblResourceRequests tblResourceRequests,
			Date startDate, Date endDate, int duration, float ftepercent, float hours, Serializable createdBy,
			Date createdOn, Serializable lastModifiedBy, Date lastModifiedOn) {
		this.resourceRequestWorkEffortId = resourceRequestWorkEffortId;
		this.tblResourceRequests = tblResourceRequests;
		this.startDate = startDate;
		this.endDate = endDate;
		this.duration = duration;
		this.ftepercent = ftepercent;
		this.hours = hours;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
	}

	@Id

	@Column(name = "ResourceRequestWorkEffortID", unique = true, nullable = false)
	public int getResourceRequestWorkEffortId() {
		return this.resourceRequestWorkEffortId;
	}

	public void setResourceRequestWorkEffortId(int resourceRequestWorkEffortId) {
		this.resourceRequestWorkEffortId = resourceRequestWorkEffortId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ResourceRequestID")
	public TblResourceRequests getTblResourceRequests() {
		return this.tblResourceRequests;
	}

	public void setTblResourceRequests(TblResourceRequests tblResourceRequests) {
		this.tblResourceRequests = tblResourceRequests;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", nullable = false, length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "Duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "FTEPercent", nullable = false, precision = 24, scale = 0)
	public float getFtepercent() {
		return this.ftepercent;
	}

	public void setFtepercent(float ftepercent) {
		this.ftepercent = ftepercent;
	}

	@Column(name = "Hours", nullable = false, precision = 24, scale = 0)
	public float getHours() {
		return this.hours;
	}

	public void setHours(float hours) {
		this.hours = hours;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", nullable = false, length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

}
