package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ericsson.isf.model.LanguageBaseVersionModel;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonUnwrapped;

/**
 * TblRpaBotstaging generated by hbm2java
 */
@Entity
@Table(name = "TBL_RPA_BOTSTAGING", schema = "transactionalData")
public class TblRpaBotstaging implements java.io.Serializable {

	private int srno;
	private TblRpaRequest tblRpaRequest;
	private int botid;
	private String assignedTo;
	private String botname;
	private int rpaexecutionTime;
	private String botlanguage;
	private String targetExecutionFileName;
	private String moduleClassName;
	private String moduleClassMethod;
	private String parallelWoexecution;
	private Integer reuseFactor;
	private Integer lineOfCode;
	private String status;
	private String statusDescription;
	private String createdBy;
	private Date createdOn;
	private String modifiedBy;
	private Date modifiedOn;
	private int isActive;
	private int isRunOnServer;
	private Integer languageBaseVersionID;

	
	
	//not part of table model
	@Transient
	private String botConfigJson;

	public TblRpaBotstaging() {
	}
	
	public TblRpaBotstaging(int systemId, int srno, TblRpaRequest tblRpaRequest, int botid, String assignedTo,
			String botname, int rpaexecutionTime, String botlanguage, String targetExecutionFileName,
			String moduleClassName, String moduleClassMethod, String parallelWoexecution, Integer reuseFactor,
			Integer lineOfCode, String status, String statusDescription, String createdBy, Date createdOn,
			String modifiedBy, Date modifiedOn, int isActive, int isRunOnServer, String botConfigJson,
			Integer languageBaseVersionID) {
		this.srno = srno;
		this.tblRpaRequest = tblRpaRequest;
		this.botid = botid;
		this.assignedTo = assignedTo;
		this.botname = botname;
		this.rpaexecutionTime = rpaexecutionTime;
		this.botlanguage = botlanguage;
		this.targetExecutionFileName = targetExecutionFileName;
		this.moduleClassName = moduleClassName;
		this.moduleClassMethod = moduleClassMethod;
		this.parallelWoexecution = parallelWoexecution;
		this.reuseFactor = reuseFactor;
		this.lineOfCode = lineOfCode;
		this.status = status;
		this.statusDescription = statusDescription;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isActive = isActive;
		this.isRunOnServer = isRunOnServer;
		this.botConfigJson = botConfigJson;
		this.languageBaseVersionID=languageBaseVersionID;
		
	}




	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "SRNO", unique = true, nullable = false)
	public int getSrno() {
		return this.srno;
	}

	public void setSrno(int srno) {
		this.srno = srno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rpaRequestID", referencedColumnName = "rpaRequestID")
	public TblRpaRequest getTblRpaRequest() {
		return this.tblRpaRequest;
	}

	public void setTblRpaRequest(TblRpaRequest tblRpaRequest) {
		this.tblRpaRequest = tblRpaRequest;
	}

	@Column(name = "BOTID", nullable = false)
	public int getBotid() {
		return this.botid;
	}

	public void setBotid(int botid) {
		this.botid = botid;
	}

	@Column(name = "AssignedTo", nullable = false, length = 10)
	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "BOTName", nullable = true, length = 200)
	public String getBotname() {
		return this.botname;
	}

	public void setBotname(String botname) {
		this.botname = botname;
	}

	@Column(name = "RPAExecutionTime", nullable = true)
	public int getRpaexecutionTime() {
		return this.rpaexecutionTime;
	}

	public void setRpaexecutionTime(int rpaexecutionTime) {
		this.rpaexecutionTime = rpaexecutionTime;
	}

	@Column(name = "BOTLanguage", nullable = true, length = 20)
	public String getBotlanguage() {
		return this.botlanguage;
	}

	public void setBotlanguage(String botlanguage) {
		this.botlanguage = botlanguage;
	}

	@Column(name = "TargetExecutionFileName", nullable = true, length = 200)
	public String getTargetExecutionFileName() {
		return this.targetExecutionFileName;
	}

	public void setTargetExecutionFileName(String targetExecutionFileName) {
		this.targetExecutionFileName = targetExecutionFileName;
	}

	@Column(name = "ModuleClassName", nullable = true, length = 100)
	public String getModuleClassName() {
		return this.moduleClassName;
	}

	public void setModuleClassName(String moduleClassName) {
		this.moduleClassName = moduleClassName;
	}

	@Column(name = "ModuleClassMethod", nullable = true, length = 100)
	public String getModuleClassMethod() {
		return this.moduleClassMethod;
	}

	public void setModuleClassMethod(String moduleClassMethod) {
		this.moduleClassMethod = moduleClassMethod;
	}

	@Column(name = "ParallelWOExecution", nullable = true, length = 5)
	public String getParallelWoexecution() {
		return this.parallelWoexecution;
	}

	public void setParallelWoexecution(String parallelWoexecution) {
		this.parallelWoexecution = parallelWoexecution;
	}

	@Column(name = "ReuseFactor", nullable = true)
	public Integer getReuseFactor() {
		return this.reuseFactor;
	}

	public void setReuseFactor(Integer reuseFactor) {
		this.reuseFactor = reuseFactor;
	}

	@Column(name = "LineOfCode", nullable = true)
	public Integer getLineOfCode() {
		return this.lineOfCode;
	}

	public void setLineOfCode(Integer lineOfCode) {
		this.lineOfCode = lineOfCode;
	}

	@Column(name = "Status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "StatusDescription", nullable = true, length = 300)
	public String getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}

	@Column(name = "CreatedBY", length = 10)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy", nullable = true, length = 10)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", nullable = true, length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isActive", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isRunOnServer", nullable = false)
	public int getIsRunOnServer() {
		return this.isRunOnServer;
	}

	public void setIsRunOnServer(int isRunOnServer) {
		this.isRunOnServer = isRunOnServer;
	}
	@Transient
	public String getBotConfigJson() {
		return botConfigJson;
	}
	@Transient
	public void setBotConfigJson(String botConfigJson) {
		this.botConfigJson = botConfigJson;
	}
	
	@Column(name = "LanguageBaseVersionID", nullable = true)
	public Integer getLanguageBaseVersionID() {
		return languageBaseVersionID;
	}

	public void setLanguageBaseVersionID(Integer languageBaseVersionID) {
		this.languageBaseVersionID = languageBaseVersionID;
	}	
	
}
