package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import org.hibernate.annotations.NaturalId;

/**
 * TblRpaBotrequirement generated by hbm2java
 */
@Entity
@Table(name = "TBL_RPA_BOTRequirement", schema = "transactionalData")
public class TblRpaBotrequirement implements java.io.Serializable {

	private int systemId;
	@NaturalId
	private int botrequirementId;
	private TblRpaRequest tblRpaRequest;
	private int isDataFetching;
	private int isReportPrepration;
	private String outputFormat;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;
	private String modifiedBy;
	private int isActive;
	private Set<TblRpaRequestTool> tblRpaRequestTools = new HashSet<TblRpaRequestTool>(0);
	
	public TblRpaBotrequirement() {
	}

//	public TblRpaBotrequirement(int botrequirementId, TblRpaRequest tblRpaRequest,
//			int isDataFetching, int isReportPrepration, String outputFormat, String createdBy, Date createdOn,
//			Date modifiedOn, String modifiedBy, int isActive, Set<TblRpaRequestTool> tblRpaRequestTools) {
//		this.botrequirementId = botrequirementId;
//		this.tblRpaRequest = tblRpaRequest;
//		this.isDataFetching = isDataFetching;
//		this.isReportPrepration = isReportPrepration;
//		this.outputFormat = outputFormat;
//		this.createdBy = createdBy;
//		this.createdOn = createdOn;
//		this.modifiedOn = modifiedOn;
//		this.modifiedBy = modifiedBy;
//		this.isActive = isActive;
//		this.tblRpaRequestTools = tblRpaRequestTools;
//		
//	}

	
	public TblRpaBotrequirement(int systemId, int botrequirementId, TblRpaRequest tblRpaRequest, int isDataFetching,
			int isReportPrepration, String outputFormat, String createdBy, Date createdOn, Date modifiedOn,
			String modifiedBy, int isActive, Set<TblRpaRequestTool> tblRpaRequestTools) {
		this.systemId = systemId;
		this.botrequirementId = botrequirementId;
		this.tblRpaRequest = tblRpaRequest;
		this.isDataFetching = isDataFetching;
		this.isReportPrepration = isReportPrepration;
		this.outputFormat = outputFormat;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.isActive = isActive;
		this.tblRpaRequestTools = tblRpaRequestTools;
	}

	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "SystemID", unique = true, nullable = false)
	public int getSystemId() {
		return systemId;
	}

	public void setSystemId(int systemId) {
		this.systemId = systemId;
	}
	
	@Generated( value = GenerationTime.ALWAYS )
	@Column(name = "BOTRequirementId", unique = true, nullable = false)
	public int getBotrequirementId() {
		return this.botrequirementId;
	}

	public void setBotrequirementId(int botrequirementId) {
		this.botrequirementId = botrequirementId;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rpaRequestID", referencedColumnName = "rpaRequestID")
	public TblRpaRequest getTblRpaRequest() {
		return this.tblRpaRequest;
	}

	public void setTblRpaRequest(TblRpaRequest tblRpaRequest) {
		this.tblRpaRequest = tblRpaRequest;
	}

	@Column(name = "IsDataFetching", nullable = false)
	public int getIsDataFetching() {
		return this.isDataFetching;
	}

	public void setIsDataFetching(int isDataFetching) {
		this.isDataFetching = isDataFetching;
	}

	@Column(name = "IsReportPrepration", nullable = false)
	public int getIsReportPrepration() {
		return this.isReportPrepration;
	}

	public void setIsReportPrepration(int isReportPrepration) {
		this.isReportPrepration = isReportPrepration;
	}

	@Column(name = "OutputFormat", nullable = false, length = 300)
	public String getOutputFormat() {
		return this.outputFormat;
	}

	public void setOutputFormat(String outputFormat) {
		this.outputFormat = outputFormat;
	}

	@Column(name = "CreatedBY", nullable = false, length = 10)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedON", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", nullable = true, length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy", nullable = true, length = 10)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "isActive", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRpaBotrequirement")
	public Set<TblRpaRequestTool> getTblRpaRequestTools() {
		return this.tblRpaRequestTools;
	}

	public void setTblRpaRequestTools(Set<TblRpaRequestTool> tblRpaRequestTools) {
		this.tblRpaRequestTools = tblRpaRequestTools;
	}

}
