package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblReportGenerateHistory generated by hbm2java
 */
@Entity
@Table(name = "TBL_REPORT_GENERATE_HISTORY", schema = "transactionalData")
public class TblReportGenerateHistory implements java.io.Serializable {

	private TblReportGenerateHistoryId id;

	public TblReportGenerateHistory() {
	}

	public TblReportGenerateHistory(TblReportGenerateHistoryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "generatedReportId", column = @Column(name = "GeneratedReportID", nullable = false)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 256)),
			@AttributeOverride(name = "moduleName", column = @Column(name = "ModuleName")),
			@AttributeOverride(name = "subModuleName", column = @Column(name = "SubModuleName")),
			@AttributeOverride(name = "reportName", column = @Column(name = "ReportName")),
			@AttributeOverride(name = "groupBy", column = @Column(name = "GroupBy")),
			@AttributeOverride(name = "generatedDate", column = @Column(name = "GeneratedDate", length = 23)) })
	public TblReportGenerateHistoryId getId() {
		return this.id;
	}

	public void setId(TblReportGenerateHistoryId id) {
		this.id = id;
	}

}
