package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * TblRpaRequestTool generated by hbm2java
 */
@Entity
@Table(name = "TBL_RPA_Request_Tool", schema = "transactionalData")
public class TblRpaRequestTool implements java.io.Serializable {

	private int systemId;
	private int rparequestToolId;
	private TblRpaBotrequirement tblRpaBotrequirement;
	private int toolId;
	private String toolName;
	private int isPasswordRequired;
	private int isMobilePassRequired;
	private int isVpnrequired;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;
	private String modifiedBy;
	private int isActive;

	public TblRpaRequestTool() {
	}

	public TblRpaRequestTool(int rparequestToolId, int toolId, String toolName, int isPasswordRequired,
			int isMobilePassRequired, int isVpnrequired, String createdBy, Date createdOn,
			Date modifiedOn, String modifiedBy, int isActive, TblRpaBotrequirement tblRpaBotrequirement) {
		this.rparequestToolId = rparequestToolId;
		this.toolId = toolId;
		this.toolName = toolName; 
		this.isPasswordRequired = isPasswordRequired;
		this.isMobilePassRequired = isMobilePassRequired;
		this.isVpnrequired = isVpnrequired;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.isActive = isActive;
		this.tblRpaBotrequirement= tblRpaBotrequirement;
	}

	public TblRpaRequestTool(int rparequestToolId, int toolId, String toolName, String createdBy, Date createdOn,
			Date modifiedOn, String modifiedBy, int isActive, TblRpaBotrequirement tblRpaBotrequirement) {
		this.rparequestToolId = rparequestToolId;
		this.toolId = toolId;
		this.toolName = toolName; 
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.isActive = isActive;
		this.tblRpaBotrequirement= tblRpaBotrequirement;
	}
	
	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "SystemID", unique = true, nullable = false)
	public int getSystemId() {
		return systemId;
	}

	public void setSystemId(int systemId) {
		this.systemId = systemId;
	}


	@Generated(value= GenerationTime.ALWAYS)
	@Column(name = "RPARequestToolId", unique = true, nullable = false)
	public int getRparequestToolId() {
		return this.rparequestToolId;
	}

	public void setRparequestToolId(int rparequestToolId) {
		this.rparequestToolId = rparequestToolId;
	}

	@Column(name = "ToolId", nullable = false)
	public int getToolId() {
		return this.toolId;
	}

	public void setToolId(int toolId) {
		this.toolId = toolId;
	}

	@Column(name = "ToolName", nullable = true, length = 200)
	public String getToolName() {
		return toolName;
	}

	public void setToolName(String toolName) {
		this.toolName = toolName;
	}

	@Column(name = "IsPasswordRequired", nullable = false)
	public int getIsPasswordRequired() {
		return this.isPasswordRequired;
	}

	public void setIsPasswordRequired(int isPasswordRequired) {
		this.isPasswordRequired = isPasswordRequired;
	}

	@Column(name = "IsMobilePassRequired", nullable = false)
	public int getIsMobilePassRequired() {
		return this.isMobilePassRequired;
	}

	public void setIsMobilePassRequired(int isMobilePassRequired) {
		this.isMobilePassRequired = isMobilePassRequired;
	}

	@Column(name = "IsVPNRequired", nullable = false)
	public int getIsVpnrequired() {
		return this.isVpnrequired;
	}

	public void setIsVpnrequired(int isVpnrequired) {
		this.isVpnrequired = isVpnrequired;
	}

	@Column(name = "CreatedBY", nullable = false, length = 10)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedON", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", nullable = true, length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy", nullable = true, length = 10)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "isActive", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BOTRequirementId", referencedColumnName = "BOTRequirementId")
	public TblRpaBotrequirement getTblRpaBotrequirement() {
		return this.tblRpaBotrequirement;
	}

	public void setTblRpaBotrequirement(TblRpaBotrequirement tblRpaBotrequirement) {
		this.tblRpaBotrequirement = tblRpaBotrequirement;
	}

}
