package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblSubactivityFlowchartDepId generated by hbm2java
 */
@Embeddable
public class TblSubactivityFlowchartDepId implements java.io.Serializable {

	private int subActivityFlowChartDepId;
	private Integer subActivityFlowChartStepId;
	private Integer subActivityFlowChartDependentStepId;
	private String dependencyCondition;
	private String linkJson;

	public TblSubactivityFlowchartDepId() {
	}

	public TblSubactivityFlowchartDepId(int subActivityFlowChartDepId) {
		this.subActivityFlowChartDepId = subActivityFlowChartDepId;
	}

	public TblSubactivityFlowchartDepId(int subActivityFlowChartDepId, Integer subActivityFlowChartStepId,
			Integer subActivityFlowChartDependentStepId, String dependencyCondition, String linkJson) {
		this.subActivityFlowChartDepId = subActivityFlowChartDepId;
		this.subActivityFlowChartStepId = subActivityFlowChartStepId;
		this.subActivityFlowChartDependentStepId = subActivityFlowChartDependentStepId;
		this.dependencyCondition = dependencyCondition;
		this.linkJson = linkJson;
	}

	@Column(name = "SubActivityFlowChartDepID", nullable = false)
	public int getSubActivityFlowChartDepId() {
		return this.subActivityFlowChartDepId;
	}

	public void setSubActivityFlowChartDepId(int subActivityFlowChartDepId) {
		this.subActivityFlowChartDepId = subActivityFlowChartDepId;
	}

	@Column(name = "SubActivityFlowChartStepID")
	public Integer getSubActivityFlowChartStepId() {
		return this.subActivityFlowChartStepId;
	}

	public void setSubActivityFlowChartStepId(Integer subActivityFlowChartStepId) {
		this.subActivityFlowChartStepId = subActivityFlowChartStepId;
	}

	@Column(name = "SubActivityFlowChartDependentStepID")
	public Integer getSubActivityFlowChartDependentStepId() {
		return this.subActivityFlowChartDependentStepId;
	}

	public void setSubActivityFlowChartDependentStepId(Integer subActivityFlowChartDependentStepId) {
		this.subActivityFlowChartDependentStepId = subActivityFlowChartDependentStepId;
	}

	@Column(name = "DependencyCondition")
	public String getDependencyCondition() {
		return this.dependencyCondition;
	}

	public void setDependencyCondition(String dependencyCondition) {
		this.dependencyCondition = dependencyCondition;
	}

	@Column(name = "LinkJSON")
	public String getLinkJson() {
		return this.linkJson;
	}

	public void setLinkJson(String linkJson) {
		this.linkJson = linkJson;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblSubactivityFlowchartDepId))
			return false;
		TblSubactivityFlowchartDepId castOther = (TblSubactivityFlowchartDepId) other;

		return (this.getSubActivityFlowChartDepId() == castOther.getSubActivityFlowChartDepId())
				&& ((this.getSubActivityFlowChartStepId() == castOther.getSubActivityFlowChartStepId())
						|| (this.getSubActivityFlowChartStepId() != null
								&& castOther.getSubActivityFlowChartStepId() != null
								&& this.getSubActivityFlowChartStepId()
										.equals(castOther.getSubActivityFlowChartStepId())))
				&& ((this.getSubActivityFlowChartDependentStepId() == castOther
						.getSubActivityFlowChartDependentStepId())
						|| (this.getSubActivityFlowChartDependentStepId() != null
								&& castOther.getSubActivityFlowChartDependentStepId() != null
								&& this.getSubActivityFlowChartDependentStepId()
										.equals(castOther.getSubActivityFlowChartDependentStepId())))
				&& ((this.getDependencyCondition() == castOther.getDependencyCondition())
						|| (this.getDependencyCondition() != null && castOther.getDependencyCondition() != null
								&& this.getDependencyCondition().equals(castOther.getDependencyCondition())))
				&& ((this.getLinkJson() == castOther.getLinkJson()) || (this.getLinkJson() != null
						&& castOther.getLinkJson() != null && this.getLinkJson().equals(castOther.getLinkJson())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSubActivityFlowChartDepId();
		result = 37 * result
				+ (getSubActivityFlowChartStepId() == null ? 0 : this.getSubActivityFlowChartStepId().hashCode());
		result = 37 * result + (getSubActivityFlowChartDependentStepId() == null ? 0
				: this.getSubActivityFlowChartDependentStepId().hashCode());
		result = 37 * result + (getDependencyCondition() == null ? 0 : this.getDependencyCondition().hashCode());
		result = 37 * result + (getLinkJson() == null ? 0 : this.getLinkJson().hashCode());
		return result;
	}

}
