package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblSubactivityFlowchartStep generated by hbm2java
 */
@Entity
@Table(name = "TBL_SUBACTIVITY_FLOWCHART_STEP", schema = "transactionalData")
public class TblSubactivityFlowchartStep implements java.io.Serializable {

	private TblSubactivityFlowchartStepId id;

	public TblSubactivityFlowchartStep() {
	}

	public TblSubactivityFlowchartStep(TblSubactivityFlowchartStepId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "subActivityFlowChartStepId", column = @Column(name = "SubActivityFlowChartStepID", nullable = false)),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID")),
			@AttributeOverride(name = "stepName", column = @Column(name = "StepName")),
			@AttributeOverride(name = "displayStepName", column = @Column(name = "DisplayStepName")),
			@AttributeOverride(name = "graphicalRepresentation", column = @Column(name = "GraphicalRepresentation")),
			@AttributeOverride(name = "executionType", column = @Column(name = "ExecutionType")),
			@AttributeOverride(name = "responsible", column = @Column(name = "Responsible")),
			@AttributeOverride(name = "isTaskOrSubTask", column = @Column(name = "IsTaskOrSubTask")),
			@AttributeOverride(name = "taskOrParentTaskMapped", column = @Column(name = "TaskOrParentTaskMapped")),
			@AttributeOverride(name = "ordering", column = @Column(name = "Ordering")),
			@AttributeOverride(name = "stepJson", column = @Column(name = "StepJSON")) })
	public TblSubactivityFlowchartStepId getId() {
		return this.id;
	}

	public void setId(TblSubactivityFlowchartStepId id) {
		this.id = id;
	}

}
