package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblServicearea generated by hbm2java
 */
@Entity
@Table(name = "TBL_SERVICEAREA", schema = "refData")
public class TblServicearea implements java.io.Serializable {

	private int serviceAreaId;
	private TblServarea tblServarea;
	private String serviceArea;
	private String subServiceArea;
	private Boolean active;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Serializable pcode;
	private Set<TblSubactivity> tblSubactivities = new HashSet<TblSubactivity>(0);

	public TblServicearea() {
	}

	public TblServicearea(int serviceAreaId) {
		this.serviceAreaId = serviceAreaId;
	}

	public TblServicearea(int serviceAreaId, TblServarea tblServarea, String serviceArea, String subServiceArea,
			Boolean active, String createdBy, Date createdDate, String lastModifiedBy, Date lastModifiedDate,
			Serializable pcode, Set<TblSubactivity> tblSubactivities) {
		this.serviceAreaId = serviceAreaId;
		this.tblServarea = tblServarea;
		this.serviceArea = serviceArea;
		this.subServiceArea = subServiceArea;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.pcode = pcode;
		this.tblSubactivities = tblSubactivities;
	}

	@Id

	@Column(name = "ServiceAreaID", unique = true, nullable = false)
	public int getServiceAreaId() {
		return this.serviceAreaId;
	}

	public void setServiceAreaId(int serviceAreaId) {
		this.serviceAreaId = serviceAreaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ServAreaID")
	public TblServarea getTblServarea() {
		return this.tblServarea;
	}

	public void setTblServarea(TblServarea tblServarea) {
		this.tblServarea = tblServarea;
	}

	@Column(name = "ServiceArea", length = 128)
	public String getServiceArea() {
		return this.serviceArea;
	}

	public void setServiceArea(String serviceArea) {
		this.serviceArea = serviceArea;
	}

	@Column(name = "SubServiceArea", length = 128)
	public String getSubServiceArea() {
		return this.subServiceArea;
	}

	public void setSubServiceArea(String subServiceArea) {
		this.subServiceArea = subServiceArea;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "CreatedBy", length = 128)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LastModifiedBy", length = 128)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "PCode")
	public Serializable getPcode() {
		return this.pcode;
	}

	public void setPcode(Serializable pcode) {
		this.pcode = pcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblServicearea")
	public Set<TblSubactivity> getTblSubactivities() {
		return this.tblSubactivities;
	}

	public void setTblSubactivities(Set<TblSubactivity> tblSubactivities) {
		this.tblSubactivities = tblSubactivities;
	}

}
