package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblSofthumanActivityList generated by hbm2java
 */
@Entity
@Table(name = "TBL_SofthumanActivityList", schema = "refData")
public class TblSofthumanActivityList implements java.io.Serializable {

	private TblSofthumanActivityListId id;

	public TblSofthumanActivityList() {
	}

	public TblSofthumanActivityList(TblSofthumanActivityListId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "automationPlugin", column = @Column(name = "Automation_Plugin", length = 500)),
			@AttributeOverride(name = "softhuman", column = @Column(name = "SOFTHUMAN", precision = 53, scale = 0)),
			@AttributeOverride(name = "category", column = @Column(name = "Category", length = 10)),
			@AttributeOverride(name = "region", column = @Column(name = "Region", length = 10)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 10)),
			@AttributeOverride(name = "developer", column = @Column(name = "Developer", length = 100)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", nullable = false, length = 8)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", nullable = false, length = 23)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", nullable = false, length = 8)),
			@AttributeOverride(name = "lastModifiedOn", column = @Column(name = "LastModifiedOn", nullable = false, length = 23)) })
	public TblSofthumanActivityListId getId() {
		return this.id;
	}

	public void setId(TblSofthumanActivityListId id) {
		this.id = id;
	}

}
