package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblSubactivityFlowchartDefBk14062018 generated by hbm2java
 */
@Entity
@Table(name = "TBL_SUBACTIVITY_FLOWCHART_DEF_bk_14_06_2018", schema = "transactionalData")
public class TblSubactivityFlowchartDefBk14062018 implements java.io.Serializable {

	private TblSubactivityFlowchartDefBk14062018Id id;

	public TblSubactivityFlowchartDefBk14062018() {
	}

	public TblSubactivityFlowchartDefBk14062018(TblSubactivityFlowchartDefBk14062018Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "flowChartJson", column = @Column(name = "FlowChartJSON")),
			@AttributeOverride(name = "sourceProjectId", column = @Column(name = "SourceProjectID")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 1024)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", length = 23)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "versionNumber", column = @Column(name = "VersionNumber")),
			@AttributeOverride(name = "type", column = @Column(name = "Type", length = 512)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", length = 256)),
			@AttributeOverride(name = "lastModifiedDate", column = @Column(name = "LastModifiedDate", length = 23)),
			@AttributeOverride(name = "workFlowName", column = @Column(name = "WorkFlowName")) })
	public TblSubactivityFlowchartDefBk14062018Id getId() {
		return this.id;
	}

	public void setId(TblSubactivityFlowchartDefBk14062018Id id) {
		this.id = id;
	}

}
