package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblToolInventory generated by hbm2java
 */
@Entity
@Table(name = "TBL_TOOL_INVENTORY", schema = "refData")
public class TblToolInventory implements java.io.Serializable {

	private int toolId;
	private String tool;
	private String licenseType;
	private Boolean active;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Set<TblTaskTool> tblTaskTools = new HashSet<TblTaskTool>(0);

	public TblToolInventory() {
	}

	public TblToolInventory(int toolId) {
		this.toolId = toolId;
	}

	public TblToolInventory(int toolId, String tool, String licenseType, Boolean active, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate, Set<TblTaskTool> tblTaskTools) {
		this.toolId = toolId;
		this.tool = tool;
		this.licenseType = licenseType;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.tblTaskTools = tblTaskTools;
	}

	@Id

	@Column(name = "ToolID", unique = true, nullable = false)
	public int getToolId() {
		return this.toolId;
	}

	public void setToolId(int toolId) {
		this.toolId = toolId;
	}

	@Column(name = "Tool", length = 128)
	public String getTool() {
		return this.tool;
	}

	public void setTool(String tool) {
		this.tool = tool;
	}

	@Column(name = "LicenseType", length = 128)
	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "CreatedBy", length = 128)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LastModifiedBy", length = 128)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblToolInventory")
	public Set<TblTaskTool> getTblTaskTools() {
		return this.tblTaskTools;
	}

	public void setTblTaskTools(Set<TblTaskTool> tblTaskTools) {
		this.tblTaskTools = tblTaskTools;
	}

}
