package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTask generated by hbm2java
 */
@Entity
@Table(name = "TBL_TASK", schema = "refData")
public class TblTask implements java.io.Serializable {

	private int taskId;
	private TblSubactivity tblSubactivity;
	private String task;
	private String executionType;
	private Boolean active;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Double avgEstdEffort;
	private String description;
	private Set<TblTaskTool> tblTaskTools = new HashSet<TblTaskTool>(0);

	public TblTask() {
	}

	public TblTask(int taskId) {
		this.taskId = taskId;
	}

	public TblTask(int taskId, TblSubactivity tblSubactivity, String task, String executionType, Boolean active,
			String createdBy, Date createdDate, String lastModifiedBy, Date lastModifiedDate, Double avgEstdEffort,
			String description, Set<TblTaskTool> tblTaskTools) {
		this.taskId = taskId;
		this.tblSubactivity = tblSubactivity;
		this.task = task;
		this.executionType = executionType;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.avgEstdEffort = avgEstdEffort;
		this.description = description;
		this.tblTaskTools = tblTaskTools;
	}

	@Id

	@Column(name = "TaskID", unique = true, nullable = false)
	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SubActivityID")
	public TblSubactivity getTblSubactivity() {
		return this.tblSubactivity;
	}

	public void setTblSubactivity(TblSubactivity tblSubactivity) {
		this.tblSubactivity = tblSubactivity;
	}

	@Column(name = "Task", length = 512)
	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	@Column(name = "ExecutionType", length = 128)
	public String getExecutionType() {
		return this.executionType;
	}

	public void setExecutionType(String executionType) {
		this.executionType = executionType;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "CreatedBy", length = 128)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LastModifiedBy", length = 128)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "AvgEstdEffort", precision = 53, scale = 0)
	public Double getAvgEstdEffort() {
		return this.avgEstdEffort;
	}

	public void setAvgEstdEffort(Double avgEstdEffort) {
		this.avgEstdEffort = avgEstdEffort;
	}

	@Column(name = "Description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblTask")
	public Set<TblTaskTool> getTblTaskTools() {
		return this.tblTaskTools;
	}

	public void setTblTaskTools(Set<TblTaskTool> tblTaskTools) {
		this.tblTaskTools = tblTaskTools;
	}

}
