package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblToolInfo generated by hbm2java
 */
@Entity
@Table(name = "TBL_ToolInfo", schema = "transactionalData")
public class TblToolInfo implements java.io.Serializable {

	private int toolInfoId;
	private String toolName;
	private Boolean status;
	private Date fileUplodedOn;
	private Date modifiedOn;

	public TblToolInfo() {
	}

	public TblToolInfo(int toolInfoId) {
		this.toolInfoId = toolInfoId;
	}

	public TblToolInfo(int toolInfoId, String toolName, Boolean status, Date fileUplodedOn, Date modifiedOn) {
		this.toolInfoId = toolInfoId;
		this.toolName = toolName;
		this.status = status;
		this.fileUplodedOn = fileUplodedOn;
		this.modifiedOn = modifiedOn;
	}

	@Id

	@Column(name = "ToolInfoId", unique = true, nullable = false)
	public int getToolInfoId() {
		return this.toolInfoId;
	}

	public void setToolInfoId(int toolInfoId) {
		this.toolInfoId = toolInfoId;
	}

	@Column(name = "ToolName", length = 100)
	public String getToolName() {
		return this.toolName;
	}

	public void setToolName(String toolName) {
		this.toolName = toolName;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FileUplodedON", length = 23)
	public Date getFileUplodedOn() {
		return this.fileUplodedOn;
	}

	public void setFileUplodedOn(Date fileUplodedOn) {
		this.fileUplodedOn = fileUplodedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedON", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
