package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblUserRole generated by hbm2java
 */
@Entity
@Table(name = "TBL_USER_ROLE", schema = "transactionalData")
public class TblUserRole implements java.io.Serializable {

	private TblUserRoleId id;

	public TblUserRole() {
	}

	public TblUserRole(TblUserRoleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userRoleId", column = @Column(name = "UserRoleID", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "UserName", length = 1024)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 128)),
			@AttributeOverride(name = "role", column = @Column(name = "Role", length = 512)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")) })
	public TblUserRoleId getId() {
		return this.id;
	}

	public void setId(TblUserRoleId id) {
		this.id = id;
	}

}
