package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblUserLoginHistory generated by hbm2java
 */
@Entity
@Table(name = "TBL_USER_LOGIN_HISTORY", schema = "transactionalData")
public class TblUserLoginHistory implements java.io.Serializable {

	private TblUserLoginHistoryId id;

	public TblUserLoginHistory() {
	}

	public TblUserLoginHistory(TblUserLoginHistoryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logid", column = @Column(name = "LOGID", nullable = false)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 1024)),
			@AttributeOverride(name = "loginTime", column = @Column(name = "LoginTime", length = 23)),
			@AttributeOverride(name = "logoutTime", column = @Column(name = "LogoutTime", length = 23)) })
	public TblUserLoginHistoryId getId() {
		return this.id;
	}

	public void setId(TblUserLoginHistoryId id) {
		this.id = id;
	}

}
