package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblUserAccessProfile generated by hbm2java
 */
@Entity
@Table(name = "TBL_USER_ACCESS_PROFILE", schema = "transactionalData")
public class TblUserAccessProfile implements java.io.Serializable {

	private TblUserAccessProfileId id;

	public TblUserAccessProfile() {
	}

	public TblUserAccessProfile(TblUserAccessProfileId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 1024)),
			@AttributeOverride(name = "accessProfileId", column = @Column(name = "AccessProfileID")),
			@AttributeOverride(name = "approvedBy", column = @Column(name = "ApprovedBy", length = 512)),
			@AttributeOverride(name = "approvedDate", column = @Column(name = "ApprovedDate", length = 23)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", length = 512)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "approvalStatus", column = @Column(name = "ApprovalStatus", length = 500)),
			@AttributeOverride(name = "userAccessProfileId", column = @Column(name = "UserAccessProfileID", nullable = false)),
			@AttributeOverride(name = "lastModifiedDate", column = @Column(name = "LastModifiedDate", length = 23)) })
	public TblUserAccessProfileId getId() {
		return this.id;
	}

	public void setId(TblUserAccessProfileId id) {
		this.id = id;
	}

}
