package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserRoleMappings generated by hbm2java
 */
@Entity
@Table(name = "TBL_UserRoleMappings", schema = "refData")
public class TblUserRoleMappings implements java.io.Serializable {

	private int userRoleMappingId;
	private TblRoles tblRoles;
	private Serializable signum;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable lastModifiedBy;
	private Date lastModifiedOn;

	public TblUserRoleMappings() {
	}

	public TblUserRoleMappings(int userRoleMappingId, Date createdOn, Date lastModifiedOn) {
		this.userRoleMappingId = userRoleMappingId;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
	}

	public TblUserRoleMappings(int userRoleMappingId, TblRoles tblRoles, Serializable signum, Serializable createdBy,
			Date createdOn, Serializable lastModifiedBy, Date lastModifiedOn) {
		this.userRoleMappingId = userRoleMappingId;
		this.tblRoles = tblRoles;
		this.signum = signum;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
	}

	@Id

	@Column(name = "UserRoleMappingID", unique = true, nullable = false)
	public int getUserRoleMappingId() {
		return this.userRoleMappingId;
	}

	public void setUserRoleMappingId(int userRoleMappingId) {
		this.userRoleMappingId = userRoleMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoleID")
	public TblRoles getTblRoles() {
		return this.tblRoles;
	}

	public void setTblRoles(TblRoles tblRoles) {
		this.tblRoles = tblRoles;
	}

	@Column(name = "Signum")
	public Serializable getSignum() {
		return this.signum;
	}

	public void setSignum(Serializable signum) {
		this.signum = signum;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy")
	public Serializable getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Serializable lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", nullable = false, length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

}
