package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblVwIsfWorkOrderExecutionSummaryJobDone generated by hbm2java
 */
@Entity
@Table(name = "TBL_vw_ISF_WorkOrderExecutionSummary_JobDone", schema = "refData")
public class TblVwIsfWorkOrderExecutionSummaryJobDone implements java.io.Serializable {

	private TblVwIsfWorkOrderExecutionSummaryJobDoneId id;

	public TblVwIsfWorkOrderExecutionSummaryJobDone() {
	}

	public TblVwIsfWorkOrderExecutionSummaryJobDone(TblVwIsfWorkOrderExecutionSummaryJobDoneId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName")),
			@AttributeOverride(name = "spmname", column = @Column(name = "SPMName")),
			@AttributeOverride(name = "pcode", column = @Column(name = "Pcode")),
			@AttributeOverride(name = "servAreaId", column = @Column(name = "ServAreaID")),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea")),
			@AttributeOverride(name = "serviceAreaId", column = @Column(name = "ServiceAreaID")),
			@AttributeOverride(name = "subServiceArea", column = @Column(name = "SubServiceArea")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology")),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain")),
			@AttributeOverride(name = "subdomain", column = @Column(name = "subdomain")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "activity", column = @Column(name = "Activity")),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity")),
			@AttributeOverride(name = "projectScopeId", column = @Column(name = "ProjectScopeID")),
			@AttributeOverride(name = "scopeName", column = @Column(name = "ScopeName")),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "woplanId", column = @Column(name = "WOPlanID")),
			@AttributeOverride(name = "woActualStartDate", column = @Column(name = "WO Actual start Date")),
			@AttributeOverride(name = "woActualEndDate", column = @Column(name = "WO Actual End Date")),
			@AttributeOverride(name = "woPlannedStartDate", column = @Column(name = "WO Planned Start Date")),
			@AttributeOverride(name = "woPlannedEndDate", column = @Column(name = "WO Planned End Date")),
			@AttributeOverride(name = "woSignum", column = @Column(name = "WO Signum")),
			@AttributeOverride(name = "woStatus", column = @Column(name = "WO Status")),
			@AttributeOverride(name = "executionType", column = @Column(name = "Execution Type")),
			@AttributeOverride(name = "botId", column = @Column(name = "BOT Id")),
			@AttributeOverride(name = "taskId", column = @Column(name = "TaskID")),
			@AttributeOverride(name = "task", column = @Column(name = "Task")),
			@AttributeOverride(name = "bookingId", column = @Column(name = "BookingID")),
			@AttributeOverride(name = "parentBookingDetailsId", column = @Column(name = "ParentBookingDetailsID")),
			@AttributeOverride(name = "bookStartDate", column = @Column(name = "Book Start Date")),
			@AttributeOverride(name = "bookEndDate", column = @Column(name = "Book End Date")),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours")),
			@AttributeOverride(name = "type", column = @Column(name = "Type")),
			@AttributeOverride(name = "status", column = @Column(name = "Status")),
			@AttributeOverride(name = "serviceProfessionalSignum", column = @Column(name = "Service Professional Signum")),
			@AttributeOverride(name = "serviceProfessionalName", column = @Column(name = "Service Professional Name")),
			@AttributeOverride(name = "serviceProfessionalJobStage", column = @Column(name = "Service Professional Job Stage")),
			@AttributeOverride(name = "stepName", column = @Column(name = "StepName")),
			@AttributeOverride(name = "actualStartDate(step)", column = @Column(name = "Actual Start Date (Step)")),
			@AttributeOverride(name = "actualEndDate(step)", column = @Column(name = "Actual End Date (Step)")),
			@AttributeOverride(name = "workFlowName", column = @Column(name = "WorkFlowName")),
			@AttributeOverride(name = "wofcstepDetailsId", column = @Column(name = "WOFCStepDetailsID")),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID")),
			@AttributeOverride(name = "workFlowVersion", column = @Column(name = "WorkFlowVersion")),
			@AttributeOverride(name = "reason", column = @Column(name = "Reason")),
			@AttributeOverride(name = "outputLink", column = @Column(name = "OutputLink")),
			@AttributeOverride(name = "parallelcount", column = @Column(name = "parallelcount")),
			@AttributeOverride(name = "uploadedOn", column = @Column(name = "UploadedOn")) })
	public TblVwIsfWorkOrderExecutionSummaryJobDoneId getId() {
		return this.id;
	}

	public void setId(TblVwIsfWorkOrderExecutionSummaryJobDoneId id) {
		this.id = id;
	}

}
