package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblVwIsfBotDetailsJobDone generated by hbm2java
 */
@Entity
@Table(name = "TBL_vw_ISF_BOT_Details_JobDone", schema = "refData")
public class TblVwIsfBotDetailsJobDone implements java.io.Serializable {

	private TblVwIsfBotDetailsJobDoneId id;

	public TblVwIsfBotDetailsJobDone() {
	}

	public TblVwIsfBotDetailsJobDone(TblVwIsfBotDetailsJobDoneId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID", nullable = false, length = 20)),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName", nullable = false, length = 300)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", length = 20)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName", nullable = false, length = 300)),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID", length = 20)),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName", length = 300)),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID", length = 30)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 300)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID", length = 30)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 300)),
			@AttributeOverride(name = "subdomain", column = @Column(name = "subdomain", length = 300)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID", length = 30)),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 300)),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID", length = 30)),
			@AttributeOverride(name = "fcstepDetailsId", column = @Column(name = "FCStepDetailsID", length = 30)),
			@AttributeOverride(name = "integratedRpa", column = @Column(name = "integrated RPA", length = 30)),
			@AttributeOverride(name = "usedRpa", column = @Column(name = "used RPA", length = 30)),
			@AttributeOverride(name = "bookedRpa", column = @Column(name = "booked RPA", length = 30)),
			@AttributeOverride(name = "uploadedOn", column = @Column(name = "UploadedON", length = 30)) })
	public TblVwIsfBotDetailsJobDoneId getId() {
		return this.id;
	}

	public void setId(TblVwIsfBotDetailsJobDoneId id) {
		this.id = id;
	}

}
