package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblVwIsfWfDetailJobdoneId generated by hbm2java
 */
@Embeddable
public class TblVwIsfWfDetailJobdoneId implements java.io.Serializable {

	private String marketAreaId;
	private String marketAreaName;
	private String projectId;
	private String projectName;
	private String customerId;
	private String customerName;
	private String technologyId;
	private String technology;
	private String domainId;
	private String domain;
	private String subdomain;
	private String subActivityId;
	private String subActivity;
	private String subActivityFlowChartDefId;
	private String fcstepDetailsId;
	private String executionType;
	private String automatedWfs;
	private String uploadedOn;

	public TblVwIsfWfDetailJobdoneId() {
	}

	public TblVwIsfWfDetailJobdoneId(String marketAreaId, String marketAreaName, String projectId) {
		this.marketAreaId = marketAreaId;
		this.marketAreaName = marketAreaName;
		this.projectId = projectId;
	}

	public TblVwIsfWfDetailJobdoneId(String marketAreaId, String marketAreaName, String projectId, String projectName,
			String customerId, String customerName, String technologyId, String technology, String domainId,
			String domain, String subdomain, String subActivityId, String subActivity, String subActivityFlowChartDefId,
			String fcstepDetailsId, String executionType, String automatedWfs, String uploadedOn) {
		this.marketAreaId = marketAreaId;
		this.marketAreaName = marketAreaName;
		this.projectId = projectId;
		this.projectName = projectName;
		this.customerId = customerId;
		this.customerName = customerName;
		this.technologyId = technologyId;
		this.technology = technology;
		this.domainId = domainId;
		this.domain = domain;
		this.subdomain = subdomain;
		this.subActivityId = subActivityId;
		this.subActivity = subActivity;
		this.subActivityFlowChartDefId = subActivityFlowChartDefId;
		this.fcstepDetailsId = fcstepDetailsId;
		this.executionType = executionType;
		this.automatedWfs = automatedWfs;
		this.uploadedOn = uploadedOn;
	}

	@Column(name = "MarketAreaID", nullable = false, length = 20)
	public String getMarketAreaId() {
		return this.marketAreaId;
	}

	public void setMarketAreaId(String marketAreaId) {
		this.marketAreaId = marketAreaId;
	}

	@Column(name = "MarketAreaName", nullable = false, length = 50)
	public String getMarketAreaName() {
		return this.marketAreaName;
	}

	public void setMarketAreaName(String marketAreaName) {
		this.marketAreaName = marketAreaName;
	}

	@Column(name = "ProjectID", nullable = false, length = 20)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ProjectName", length = 250)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "CustomerID", length = 20)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CustomerName", length = 250)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "TechnologyID", length = 20)
	public String getTechnologyId() {
		return this.technologyId;
	}

	public void setTechnologyId(String technologyId) {
		this.technologyId = technologyId;
	}

	@Column(name = "Technology", length = 250)
	public String getTechnology() {
		return this.technology;
	}

	public void setTechnology(String technology) {
		this.technology = technology;
	}

	@Column(name = "DomainID", length = 20)
	public String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(String domainId) {
		this.domainId = domainId;
	}

	@Column(name = "Domain", length = 250)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "subdomain", length = 250)
	public String getSubdomain() {
		return this.subdomain;
	}

	public void setSubdomain(String subdomain) {
		this.subdomain = subdomain;
	}

	@Column(name = "SubActivityID", length = 20)
	public String getSubActivityId() {
		return this.subActivityId;
	}

	public void setSubActivityId(String subActivityId) {
		this.subActivityId = subActivityId;
	}

	@Column(name = "SubActivity", length = 250)
	public String getSubActivity() {
		return this.subActivity;
	}

	public void setSubActivity(String subActivity) {
		this.subActivity = subActivity;
	}

	@Column(name = "SubActivityFlowChartDefID", length = 25)
	public String getSubActivityFlowChartDefId() {
		return this.subActivityFlowChartDefId;
	}

	public void setSubActivityFlowChartDefId(String subActivityFlowChartDefId) {
		this.subActivityFlowChartDefId = subActivityFlowChartDefId;
	}

	@Column(name = "FCStepDetailsID", length = 25)
	public String getFcstepDetailsId() {
		return this.fcstepDetailsId;
	}

	public void setFcstepDetailsId(String fcstepDetailsId) {
		this.fcstepDetailsId = fcstepDetailsId;
	}

	@Column(name = "ExecutionType", length = 25)
	public String getExecutionType() {
		return this.executionType;
	}

	public void setExecutionType(String executionType) {
		this.executionType = executionType;
	}

	@Column(name = "Automated WFs", length = 250)
	public String getAutomatedWfs() {
		return this.automatedWfs;
	}

	public void setAutomatedWfs(String automatedWfs) {
		this.automatedWfs = automatedWfs;
	}

	@Column(name = "UploadedON", length = 30)
	public String getUploadedOn() {
		return this.uploadedOn;
	}

	public void setUploadedOn(String uploadedOn) {
		this.uploadedOn = uploadedOn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblVwIsfWfDetailJobdoneId))
			return false;
		TblVwIsfWfDetailJobdoneId castOther = (TblVwIsfWfDetailJobdoneId) other;

		return ((this.getMarketAreaId() == castOther.getMarketAreaId()) || (this.getMarketAreaId() != null
				&& castOther.getMarketAreaId() != null && this.getMarketAreaId().equals(castOther.getMarketAreaId())))
				&& ((this.getMarketAreaName() == castOther.getMarketAreaName())
						|| (this.getMarketAreaName() != null && castOther.getMarketAreaName() != null
								&& this.getMarketAreaName().equals(castOther.getMarketAreaName())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getProjectName() == castOther.getProjectName())
						|| (this.getProjectName() != null && castOther.getProjectName() != null
								&& this.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCustomerName() == castOther.getCustomerName())
						|| (this.getCustomerName() != null && castOther.getCustomerName() != null
								&& this.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getTechnologyId() == castOther.getTechnologyId())
						|| (this.getTechnologyId() != null && castOther.getTechnologyId() != null
								&& this.getTechnologyId().equals(castOther.getTechnologyId())))
				&& ((this.getTechnology() == castOther.getTechnology()) || (this.getTechnology() != null
						&& castOther.getTechnology() != null && this.getTechnology().equals(castOther.getTechnology())))
				&& ((this.getDomainId() == castOther.getDomainId()) || (this.getDomainId() != null
						&& castOther.getDomainId() != null && this.getDomainId().equals(castOther.getDomainId())))
				&& ((this.getDomain() == castOther.getDomain()) || (this.getDomain() != null
						&& castOther.getDomain() != null && this.getDomain().equals(castOther.getDomain())))
				&& ((this.getSubdomain() == castOther.getSubdomain()) || (this.getSubdomain() != null
						&& castOther.getSubdomain() != null && this.getSubdomain().equals(castOther.getSubdomain())))
				&& ((this.getSubActivityId() == castOther.getSubActivityId())
						|| (this.getSubActivityId() != null && castOther.getSubActivityId() != null
								&& this.getSubActivityId().equals(castOther.getSubActivityId())))
				&& ((this.getSubActivity() == castOther.getSubActivity())
						|| (this.getSubActivity() != null && castOther.getSubActivity() != null
								&& this.getSubActivity().equals(castOther.getSubActivity())))
				&& ((this.getSubActivityFlowChartDefId() == castOther.getSubActivityFlowChartDefId())
						|| (this.getSubActivityFlowChartDefId() != null
								&& castOther.getSubActivityFlowChartDefId() != null
								&& this.getSubActivityFlowChartDefId()
										.equals(castOther.getSubActivityFlowChartDefId())))
				&& ((this.getFcstepDetailsId() == castOther.getFcstepDetailsId())
						|| (this.getFcstepDetailsId() != null && castOther.getFcstepDetailsId() != null
								&& this.getFcstepDetailsId().equals(castOther.getFcstepDetailsId())))
				&& ((this.getExecutionType() == castOther.getExecutionType())
						|| (this.getExecutionType() != null && castOther.getExecutionType() != null
								&& this.getExecutionType().equals(castOther.getExecutionType())))
				&& ((this.getAutomatedWfs() == castOther.getAutomatedWfs())
						|| (this.getAutomatedWfs() != null && castOther.getAutomatedWfs() != null
								&& this.getAutomatedWfs().equals(castOther.getAutomatedWfs())))
				&& ((this.getUploadedOn() == castOther.getUploadedOn())
						|| (this.getUploadedOn() != null && castOther.getUploadedOn() != null
								&& this.getUploadedOn().equals(castOther.getUploadedOn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMarketAreaId() == null ? 0 : this.getMarketAreaId().hashCode());
		result = 37 * result + (getMarketAreaName() == null ? 0 : this.getMarketAreaName().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
		result = 37 * result + (getTechnologyId() == null ? 0 : this.getTechnologyId().hashCode());
		result = 37 * result + (getTechnology() == null ? 0 : this.getTechnology().hashCode());
		result = 37 * result + (getDomainId() == null ? 0 : this.getDomainId().hashCode());
		result = 37 * result + (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result + (getSubdomain() == null ? 0 : this.getSubdomain().hashCode());
		result = 37 * result + (getSubActivityId() == null ? 0 : this.getSubActivityId().hashCode());
		result = 37 * result + (getSubActivity() == null ? 0 : this.getSubActivity().hashCode());
		result = 37 * result
				+ (getSubActivityFlowChartDefId() == null ? 0 : this.getSubActivityFlowChartDefId().hashCode());
		result = 37 * result + (getFcstepDetailsId() == null ? 0 : this.getFcstepDetailsId().hashCode());
		result = 37 * result + (getExecutionType() == null ? 0 : this.getExecutionType().hashCode());
		result = 37 * result + (getAutomatedWfs() == null ? 0 : this.getAutomatedWfs().hashCode());
		result = 37 * result + (getUploadedOn() == null ? 0 : this.getUploadedOn().hashCode());
		return result;
	}

}
