package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblVendor generated by hbm2java
 */
@Entity
@Table(name = "TBL_VENDOR", schema = "refData")
public class TblVendor implements java.io.Serializable {

	private TblVendorId id;

	public TblVendor() {
	}

	public TblVendor(TblVendorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "vendorId", column = @Column(name = "VendorID", nullable = false)),
			@AttributeOverride(name = "vendor", column = @Column(name = "Vendor", length = 1024)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 1024)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", length = 23)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", length = 1024)),
			@AttributeOverride(name = "lastModifiedDate", column = @Column(name = "LastModifiedDate", length = 23)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")) })
	public TblVendorId getId() {
		return this.id;
	}

	public void setId(TblVendorId id) {
		this.id = id;
	}

}
