package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblVwIsfProjectdetailsJobDone generated by hbm2java
 */
@Entity
@Table(name = "TBL_vw_ISF_Projectdetails_JobDone", schema = "refData")
public class TblVwIsfProjectdetailsJobDone implements java.io.Serializable {

	private TblVwIsfProjectdetailsJobDoneId id;

	public TblVwIsfProjectdetailsJobDone() {
	}

	public TblVwIsfProjectdetailsJobDone(TblVwIsfProjectdetailsJobDoneId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID", nullable = false, length = 15)),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName", nullable = false, length = 20)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 50)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", length = 15)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName", length = 200)),
			@AttributeOverride(name = "projectType", column = @Column(name = "ProjectType", length = 20)),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID", length = 15)),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName", length = 200)),
			@AttributeOverride(name = "cpm", column = @Column(name = "CPM", length = 15)),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator", length = 15)),
			@AttributeOverride(name = "projectStartDate", column = @Column(name = "ProjectStartDate", length = 50)),
			@AttributeOverride(name = "projectEndDate", column = @Column(name = "ProjectEndDate", length = 25)),
			@AttributeOverride(name = "projectCreatedOn", column = @Column(name = "ProjectCreatedON", length = 25)),
			@AttributeOverride(name = "projectStatus", column = @Column(name = "ProjectStatus", length = 20)),
			@AttributeOverride(name = "operationalManager", column = @Column(name = "OperationalManager", length = 20)),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID", length = 20)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID", length = 15)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 50)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 50)),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID", length = 15)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 50)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID", length = 15)),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 500)),
			@AttributeOverride(name = "uploadedOn", column = @Column(name = "UploadedON", nullable = false, length = 50)) })
	public TblVwIsfProjectdetailsJobDoneId getId() {
		return this.id;
	}

	public void setId(TblVwIsfProjectdetailsJobDoneId id) {
		this.id = id;
	}

}
