package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDone generated by hbm2java
 */
@Entity
@Table(name = "TBL_VW_ProjectDetails_ISFDailyUpdateRDL_DataSet1_JobDone", schema = "refData")
public class TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDone implements java.io.Serializable {

	private TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDoneId id;

	public TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDone() {
	}

	public TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDone(
			TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDoneId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false, length = 15)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName", nullable = false, length = 500)),
			@AttributeOverride(name = "projectType", column = @Column(name = "ProjectType", length = 100)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 500)),
			@AttributeOverride(name = "opportunityName", column = @Column(name = "OpportunityName", length = 500)),
			@AttributeOverride(name = "opportunityCode", column = @Column(name = "OpportunityCode", length = 500)),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName", length = 500)),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName", length = 500)),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName", length = 100)),
			@AttributeOverride(name = "companyName", column = @Column(name = "CompanyName", length = 100)),
			@AttributeOverride(name = "cpm", column = @Column(name = "CPM", length = 500)),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator", length = 500)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", length = 35)),
			@AttributeOverride(name = "enddate", column = @Column(name = "Enddate", length = 35)),
			@AttributeOverride(name = "projectDescription", column = @Column(name = "ProjectDescription")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", nullable = false, length = 500)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 35)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 100)),
			@AttributeOverride(name = "operationalManager", column = @Column(name = "OperationalManager", length = 500)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted", nullable = false, length = 1)) })
	public TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDoneId getId() {
		return this.id;
	}

	public void setId(TblVwProjectDetailsIsfdailyUpdateRdlDataSet1JobDoneId id) {
		this.id = id;
	}

}
