package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblVwProjectDetailsJobdone generated by hbm2java
 */
@Entity
@Table(name = "tbl_VW_ProjectDetails_Jobdone", schema = "transactionalData")
public class TblVwProjectDetailsJobdone implements java.io.Serializable {

	private TblVwProjectDetailsJobdoneId id;

	public TblVwProjectDetailsJobdone() {
	}

	public TblVwProjectDetailsJobdone(TblVwProjectDetailsJobdoneId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "PRojectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName", length = 150)),
			@AttributeOverride(name = "projectType", column = @Column(name = "ProjectType", length = 15)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 40)),
			@AttributeOverride(name = "opportunityName", column = @Column(name = "OpportunityName", length = 100)),
			@AttributeOverride(name = "opportunityCode", column = @Column(name = "OpportunityCode", length = 100)),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName", length = 40)),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName", length = 100)),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName", length = 10)),
			@AttributeOverride(name = "companyName", column = @Column(name = "CompanyName", length = 10)),
			@AttributeOverride(name = "cpm", column = @Column(name = "CPM", length = 10)),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator", length = 10)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", length = 23)),
			@AttributeOverride(name = "enddate", column = @Column(name = "Enddate", length = 23)),
			@AttributeOverride(name = "projectDescription", column = @Column(name = "ProjectDescription")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 10)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 15)),
			@AttributeOverride(name = "operationalManager", column = @Column(name = "OperationalManager", length = 10)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted")),
			@AttributeOverride(name = "uploadedOn", column = @Column(name = "UploadedON", length = 23)) })
	public TblVwProjectDetailsJobdoneId getId() {
		return this.id;
	}

	public void setId(TblVwProjectDetailsJobdoneId id) {
		this.id = id;
	}

}
