package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWorkOrderBookingDetails generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_BOOKING_DETAILS", schema = "transactionalData")
public class TblWorkOrderBookingDetails implements java.io.Serializable {

	private int bookingId;
	private Integer woid;
	private Integer taskId;
	private Date startDate;
	private Date endDate;
	private Double hours;
	private Integer parentBookingDetailsId;
	private String type;
	private String status;
	private String signumId;
	private String reason;
	private String outputLink;
	private Integer parallelcount;
	private Integer isIssue;

	public TblWorkOrderBookingDetails() {
	}

	public TblWorkOrderBookingDetails(int bookingId) {
		this.bookingId = bookingId;
	}

	public TblWorkOrderBookingDetails(int bookingId, Integer woid, Integer taskId, Date startDate, Date endDate,
			Double hours, Integer parentBookingDetailsId, String type, String status, String signumId, String reason,
			String outputLink, Integer parallelcount, Integer isIssue) {
		this.bookingId = bookingId;
		this.woid = woid;
		this.taskId = taskId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.hours = hours;
		this.parentBookingDetailsId = parentBookingDetailsId;
		this.type = type;
		this.status = status;
		this.signumId = signumId;
		this.reason = reason;
		this.outputLink = outputLink;
		this.parallelcount = parallelcount;
		this.isIssue = isIssue;
	}

	@Id

	@Column(name = "BookingID", unique = true, nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "WOID")
	public Integer getWoid() {
		return this.woid;
	}

	public void setWoid(Integer woid) {
		this.woid = woid;
	}

	@Column(name = "TaskID")
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "Hours", precision = 53, scale = 0)
	public Double getHours() {
		return this.hours;
	}

	public void setHours(Double hours) {
		this.hours = hours;
	}

	@Column(name = "ParentBookingDetailsID")
	public Integer getParentBookingDetailsId() {
		return this.parentBookingDetailsId;
	}

	public void setParentBookingDetailsId(Integer parentBookingDetailsId) {
		this.parentBookingDetailsId = parentBookingDetailsId;
	}

	@Column(name = "Type", length = 512)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Status", length = 512)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "SignumID", length = 512)
	public String getSignumId() {
		return this.signumId;
	}

	public void setSignumId(String signumId) {
		this.signumId = signumId;
	}

	@Column(name = "Reason", length = 1024)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "OutputLink")
	public String getOutputLink() {
		return this.outputLink;
	}

	public void setOutputLink(String outputLink) {
		this.outputLink = outputLink;
	}

	@Column(name = "parallelcount")
	public Integer getParallelcount() {
		return this.parallelcount;
	}

	public void setParallelcount(Integer parallelcount) {
		this.parallelcount = parallelcount;
	}

	@Column(name = "isIssue")
	public Integer getIsIssue() {
		return this.isIssue;
	}

	public void setIsIssue(Integer isIssue) {
		this.isIssue = isIssue;
	}

}
