package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWorkFlowLinks generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_FLOW_LINKS", schema = "transactionalData")
public class TblWorkFlowLinks implements java.io.Serializable {

	private int workFlowLinkId;
	private Integer workFlowId;
	private Serializable linkClientId;
	private Serializable router;
	private Serializable connector;
	private Integer sourceStepClientId;
	private Integer targetStepClientId;
	private Integer z;
	private Serializable labelText;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable type;

	public TblWorkFlowLinks() {
	}

	public TblWorkFlowLinks(int workFlowLinkId) {
		this.workFlowLinkId = workFlowLinkId;
	}

	public TblWorkFlowLinks(int workFlowLinkId, Integer workFlowId, Serializable linkClientId, Serializable router,
			Serializable connector, Integer sourceStepClientId, Integer targetStepClientId, Integer z,
			Serializable labelText, Serializable createdBy, Date createdOn, Serializable type) {
		this.workFlowLinkId = workFlowLinkId;
		this.workFlowId = workFlowId;
		this.linkClientId = linkClientId;
		this.router = router;
		this.connector = connector;
		this.sourceStepClientId = sourceStepClientId;
		this.targetStepClientId = targetStepClientId;
		this.z = z;
		this.labelText = labelText;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.type = type;
	}

	@Id

	@Column(name = "WorkFlow_LinkID", unique = true, nullable = false)
	public int getWorkFlowLinkId() {
		return this.workFlowLinkId;
	}

	public void setWorkFlowLinkId(int workFlowLinkId) {
		this.workFlowLinkId = workFlowLinkId;
	}

	@Column(name = "WorkFlowID")
	public Integer getWorkFlowId() {
		return this.workFlowId;
	}

	public void setWorkFlowId(Integer workFlowId) {
		this.workFlowId = workFlowId;
	}

	@Column(name = "LinkClientID")
	public Serializable getLinkClientId() {
		return this.linkClientId;
	}

	public void setLinkClientId(Serializable linkClientId) {
		this.linkClientId = linkClientId;
	}

	@Column(name = "Router")
	public Serializable getRouter() {
		return this.router;
	}

	public void setRouter(Serializable router) {
		this.router = router;
	}

	@Column(name = "Connector")
	public Serializable getConnector() {
		return this.connector;
	}

	public void setConnector(Serializable connector) {
		this.connector = connector;
	}

	@Column(name = "SourceStepClientID")
	public Integer getSourceStepClientId() {
		return this.sourceStepClientId;
	}

	public void setSourceStepClientId(Integer sourceStepClientId) {
		this.sourceStepClientId = sourceStepClientId;
	}

	@Column(name = "TargetStepClientID")
	public Integer getTargetStepClientId() {
		return this.targetStepClientId;
	}

	public void setTargetStepClientId(Integer targetStepClientId) {
		this.targetStepClientId = targetStepClientId;
	}

	@Column(name = "Z")
	public Integer getZ() {
		return this.z;
	}

	public void setZ(Integer z) {
		this.z = z;
	}

	@Column(name = "Label_Text")
	public Serializable getLabelText() {
		return this.labelText;
	}

	public void setLabelText(Serializable labelText) {
		this.labelText = labelText;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "Type")
	public Serializable getType() {
		return this.type;
	}

	public void setType(Serializable type) {
		this.type = type;
	}

}
