package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderFailureReason generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_FAILURE_REASON", schema = "refData")
public class TblWorkOrderFailureReason implements java.io.Serializable {

	private TblWorkOrderFailureReasonId id;

	public TblWorkOrderFailureReason() {
	}

	public TblWorkOrderFailureReason(TblWorkOrderFailureReasonId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "failureReasonId", column = @Column(name = "FailureReasonID", nullable = false)),
			@AttributeOverride(name = "failureReason", column = @Column(name = "FailureReason")),
			@AttributeOverride(name = "failureCategory", column = @Column(name = "FailureCategory", length = 512)) })
	public TblWorkOrderFailureReasonId getId() {
		return this.id;
	}

	public void setId(TblWorkOrderFailureReasonId id) {
		this.id = id;
	}

}
