package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderRpaExecutionLog generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_RPA_EXECUTION_LOG", schema = "transactionalData")
public class TblWorkOrderRpaExecutionLog implements java.io.Serializable {

	private TblWorkOrderRpaExecutionLogId id;

	public TblWorkOrderRpaExecutionLog() {
	}

	public TblWorkOrderRpaExecutionLog(TblWorkOrderRpaExecutionLogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "LogID", nullable = false)),
			@AttributeOverride(name = "woId", column = @Column(name = "WoID")),
			@AttributeOverride(name = "taskId", column = @Column(name = "TaskID")),
			@AttributeOverride(name = "bookingId", column = @Column(name = "BookingID")),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 1024)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 1024)),
			@AttributeOverride(name = "bookedOn", column = @Column(name = "BookedOn", length = 23)) })
	public TblWorkOrderRpaExecutionLogId getId() {
		return this.id;
	}

	public void setId(TblWorkOrderRpaExecutionLogId id) {
		this.id = id;
	}

}
