package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWorkOrderPlan generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_PLAN", schema = "transactionalData")
public class TblWorkOrderPlan implements java.io.Serializable {

	private int woplanId;
	private Integer projectId;
	private Integer scopeId;
	private Integer subActivityId;
	private String periodicityDaily;
	private String periodicityWeekly;
	private Date startDate;
	private Date startTime;
	private Date endDate;
	private String woname;
	private String signumId;
	private Boolean active;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private String priority;
	private Double sla;
	private String type;

	public TblWorkOrderPlan() {
	}

	public TblWorkOrderPlan(int woplanId) {
		this.woplanId = woplanId;
	}

	public TblWorkOrderPlan(int woplanId, Integer projectId, Integer scopeId, Integer subActivityId,
			String periodicityDaily, String periodicityWeekly, Date startDate, Date startTime, Date endDate,
			String woname, String signumId, Boolean active, String createdBy, Date createdDate, String lastModifiedBy,
			Date lastModifiedDate, String priority, Double sla, String type) {
		this.woplanId = woplanId;
		this.projectId = projectId;
		this.scopeId = scopeId;
		this.subActivityId = subActivityId;
		this.periodicityDaily = periodicityDaily;
		this.periodicityWeekly = periodicityWeekly;
		this.startDate = startDate;
		this.startTime = startTime;
		this.endDate = endDate;
		this.woname = woname;
		this.signumId = signumId;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.priority = priority;
		this.sla = sla;
		this.type = type;
	}

	@Id

	@Column(name = "WOPlanID", unique = true, nullable = false)
	public int getWoplanId() {
		return this.woplanId;
	}

	public void setWoplanId(int woplanId) {
		this.woplanId = woplanId;
	}

	@Column(name = "ProjectID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ScopeID")
	public Integer getScopeId() {
		return this.scopeId;
	}

	public void setScopeId(Integer scopeId) {
		this.scopeId = scopeId;
	}

	@Column(name = "SubActivityID")
	public Integer getSubActivityId() {
		return this.subActivityId;
	}

	public void setSubActivityId(Integer subActivityId) {
		this.subActivityId = subActivityId;
	}

	@Column(name = "Periodicity_Daily", length = 512)
	public String getPeriodicityDaily() {
		return this.periodicityDaily;
	}

	public void setPeriodicityDaily(String periodicityDaily) {
		this.periodicityDaily = periodicityDaily;
	}

	@Column(name = "Periodicity_Weekly", length = 128)
	public String getPeriodicityWeekly() {
		return this.periodicityWeekly;
	}

	public void setPeriodicityWeekly(String periodicityWeekly) {
		this.periodicityWeekly = periodicityWeekly;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "StartDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "StartTime", length = 16)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EndDate", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "WOName")
	public String getWoname() {
		return this.woname;
	}

	public void setWoname(String woname) {
		this.woname = woname;
	}

	@Column(name = "SignumID", length = 1024)
	public String getSignumId() {
		return this.signumId;
	}

	public void setSignumId(String signumId) {
		this.signumId = signumId;
	}

	@Column(name = "Active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "CreatedBy", length = 1024)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LastModifiedBy", length = 1024)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Priority", length = 30)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "SLA", precision = 53, scale = 0)
	public Double getSla() {
		return this.sla;
	}

	public void setSla(Double sla) {
		this.sla = sla;
	}

	@Column(name = "Type", length = 128)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
