package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWoWfMapping generated by hbm2java
 */
@Entity
@Table(name = "TBL_WO_WF_MAPPING", schema = "transactionalData")
public class TblWoWfMapping implements java.io.Serializable {

	private int woWfMappingId;
	private Integer woId;
	private Integer workFlowId;
	private Serializable createdBy;
	private Date createdOn;

	public TblWoWfMapping() {
	}

	public TblWoWfMapping(int woWfMappingId) {
		this.woWfMappingId = woWfMappingId;
	}

	public TblWoWfMapping(int woWfMappingId, Integer woId, Integer workFlowId, Serializable createdBy, Date createdOn) {
		this.woWfMappingId = woWfMappingId;
		this.woId = woId;
		this.workFlowId = workFlowId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	@Id

	@Column(name = "WO_WF_MappingID", unique = true, nullable = false)
	public int getWoWfMappingId() {
		return this.woWfMappingId;
	}

	public void setWoWfMappingId(int woWfMappingId) {
		this.woWfMappingId = woWfMappingId;
	}

	@Column(name = "WO_ID")
	public Integer getWoId() {
		return this.woId;
	}

	public void setWoId(Integer woId) {
		this.woId = woId;
	}

	@Column(name = "WorkFlowID")
	public Integer getWorkFlowId() {
		return this.workFlowId;
	}

	public void setWorkFlowId(Integer workFlowId) {
		this.workFlowId = workFlowId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
