package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWorkFlowUserProficiency generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_FLOW_USER_PROFICIENCY", schema = "transactionalData")
public class TblWorkFlowUserProficiency implements java.io.Serializable {

	private int wfuserProficenctId;
	private TblSubactivity tblSubactivity;
	private TblProjects tblProjects;
	private String signumId;
	private Boolean displayedMode;
	private String createdBy;
	private Date createdOn;
	private String lastModifiedBy;
	private Date lastModifiedOn;

	public TblWorkFlowUserProficiency() {
	}

	public TblWorkFlowUserProficiency(int wfuserProficenctId) {
		this.wfuserProficenctId = wfuserProficenctId;
	}

	public TblWorkFlowUserProficiency(int wfuserProficenctId, TblSubactivity tblSubactivity, TblProjects tblProjects,
			String signumId, Boolean displayedMode, String createdBy, Date createdOn, String lastModifiedBy,
			Date lastModifiedOn) {
		this.wfuserProficenctId = wfuserProficenctId;
		this.tblSubactivity = tblSubactivity;
		this.tblProjects = tblProjects;
		this.signumId = signumId;
		this.displayedMode = displayedMode;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedOn = lastModifiedOn;
	}

	@Id

	@Column(name = "WFUserProficenctID", unique = true, nullable = false)
	public int getWfuserProficenctId() {
		return this.wfuserProficenctId;
	}

	public void setWfuserProficenctId(int wfuserProficenctId) {
		this.wfuserProficenctId = wfuserProficenctId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SubActivityID")
	public TblSubactivity getTblSubactivity() {
		return this.tblSubactivity;
	}

	public void setTblSubactivity(TblSubactivity tblSubactivity) {
		this.tblSubactivity = tblSubactivity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID")
	public TblProjects getTblProjects() {
		return this.tblProjects;
	}

	public void setTblProjects(TblProjects tblProjects) {
		this.tblProjects = tblProjects;
	}

	@Column(name = "SignumID", length = 128)
	public String getSignumId() {
		return this.signumId;
	}

	public void setSignumId(String signumId) {
		this.signumId = signumId;
	}

	@Column(name = "DisplayedMode")
	public Boolean getDisplayedMode() {
		return this.displayedMode;
	}

	public void setDisplayedMode(Boolean displayedMode) {
		this.displayedMode = displayedMode;
	}

	@Column(name = "CreatedBy", length = 128)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastModifiedBy", length = 128)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedOn", length = 23)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

}
