package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderTransferLogHistory generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_TRANSFER_LOG_HISTORY", schema = "transactionalData")
public class TblWorkOrderTransferLogHistory implements java.io.Serializable {

	private TblWorkOrderTransferLogHistoryId id;

	public TblWorkOrderTransferLogHistory() {
	}

	public TblWorkOrderTransferLogHistory(TblWorkOrderTransferLogHistoryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "wotransferlogid", column = @Column(name = "WOTRANSFERLOGID", nullable = false)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "senderid", column = @Column(name = "SENDERID")),
			@AttributeOverride(name = "receiverid", column = @Column(name = "RECEIVERID")) })
	public TblWorkOrderTransferLogHistoryId getId() {
		return this.id;
	}

	public void setId(TblWorkOrderTransferLogHistoryId id) {
		this.id = id;
	}

}
