package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderPriority generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_PRIORITY", schema = "refData")
public class TblWorkOrderPriority implements java.io.Serializable {

	private TblWorkOrderPriorityId id;

	public TblWorkOrderPriority() {
	}

	public TblWorkOrderPriority(TblWorkOrderPriorityId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "wopriority", column = @Column(name = "WOPriority", nullable = false)),
			@AttributeOverride(name = "priority", column = @Column(name = "Priority", length = 1024)),
			@AttributeOverride(name = "description", column = @Column(name = "Description", length = 1204)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")) })
	public TblWorkOrderPriorityId getId() {
		return this.id;
	}

	public void setId(TblWorkOrderPriorityId id) {
		this.id = id;
	}

}
