package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderDeliveryAcceptance generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_DELIVERY_ACCEPTANCE", schema = "transactionalData")
public class TblWorkOrderDeliveryAcceptance implements java.io.Serializable {

	private TblWorkOrderDeliveryAcceptanceId id;

	public TblWorkOrderDeliveryAcceptance() {
	}

	public TblWorkOrderDeliveryAcceptance(TblWorkOrderDeliveryAcceptanceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "deliveryAcceptanceId", column = @Column(name = "DeliveryAcceptanceID", nullable = false)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "woname", column = @Column(name = "WOName", length = 1024)),
			@AttributeOverride(name = "rating", column = @Column(name = "Rating", length = 512)),
			@AttributeOverride(name = "acceptance", column = @Column(name = "Acceptance", length = 1024)),
			@AttributeOverride(name = "deliveryStatus", column = @Column(name = "DeliveryStatus", length = 512)),
			@AttributeOverride(name = "reason", column = @Column(name = "Reason", length = 1024)),
			@AttributeOverride(name = "comment", column = @Column(name = "Comment", length = 500)),
			@AttributeOverride(name = "acceptedOrRejectedBy", column = @Column(name = "AcceptedOrRejectedBy", length = 512)),
			@AttributeOverride(name = "acceptedOrRejectedDate", column = @Column(name = "AcceptedOrRejectedDate", length = 23)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", length = 512)),
			@AttributeOverride(name = "lastModifiedDate", column = @Column(name = "LastModifiedDate", length = 23)) })
	public TblWorkOrderDeliveryAcceptanceId getId() {
		return this.id;
	}

	public void setId(TblWorkOrderDeliveryAcceptanceId id) {
		this.id = id;
	}

}
