package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderFlowchartStepLinkDetails generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_FLOWCHART_STEP_LINK_DETAILS", schema = "transactionalData")
public class TblWorkOrderFlowchartStepLinkDetails implements java.io.Serializable {

	private TblWorkOrderFlowchartStepLinkDetailsId id;

	public TblWorkOrderFlowchartStepLinkDetails() {
	}

	public TblWorkOrderFlowchartStepLinkDetails(TblWorkOrderFlowchartStepLinkDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "stepLinkId", column = @Column(name = "StepLinkID", nullable = false)),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID")),
			@AttributeOverride(name = "flowchartSourceId", column = @Column(name = "FlowchartSourceID", length = 512)),
			@AttributeOverride(name = "flowchartTargetId", column = @Column(name = "FlowchartTargetID", length = 512)) })
	public TblWorkOrderFlowchartStepLinkDetailsId getId() {
		return this.id;
	}

	public void setId(TblWorkOrderFlowchartStepLinkDetailsId id) {
		this.id = id;
	}

}
