package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWorkFlowStepToolMapping generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_FLOW_STEP_TOOL_MAPPING", schema = "transactionalData")
public class TblWorkFlowStepToolMapping implements java.io.Serializable {

	private int wfsToolMappingId;
	private Integer flowChartStepId;
	private Integer toolId;
	private Serializable createdBy;
	private Date createdOn;

	public TblWorkFlowStepToolMapping() {
	}

	public TblWorkFlowStepToolMapping(int wfsToolMappingId) {
		this.wfsToolMappingId = wfsToolMappingId;
	}

	public TblWorkFlowStepToolMapping(int wfsToolMappingId, Integer flowChartStepId, Integer toolId,
			Serializable createdBy, Date createdOn) {
		this.wfsToolMappingId = wfsToolMappingId;
		this.flowChartStepId = flowChartStepId;
		this.toolId = toolId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	@Id

	@Column(name = "WFS_Tool_MappingID", unique = true, nullable = false)
	public int getWfsToolMappingId() {
		return this.wfsToolMappingId;
	}

	public void setWfsToolMappingId(int wfsToolMappingId) {
		this.wfsToolMappingId = wfsToolMappingId;
	}

	@Column(name = "FlowChartStepID")
	public Integer getFlowChartStepId() {
		return this.flowChartStepId;
	}

	public void setFlowChartStepId(Integer flowChartStepId) {
		this.flowChartStepId = flowChartStepId;
	}

	@Column(name = "ToolID")
	public Integer getToolId() {
		return this.toolId;
	}

	public void setToolId(Integer toolId) {
		this.toolId = toolId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
