package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderBk25062018 generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_BK_25062018", schema = "transactionalData")
public class TblWorkOrderBk25062018 implements java.io.Serializable {

	private TblWorkOrderBk25062018Id id;

	public TblWorkOrderBk25062018() {
	}

	public TblWorkOrderBk25062018(TblWorkOrderBk25062018Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "woid", column = @Column(name = "WOID", nullable = false)),
			@AttributeOverride(name = "woplanId", column = @Column(name = "WOPlanID")),
			@AttributeOverride(name = "plannedStartDate", column = @Column(name = "PlannedStartDate", length = 23)),
			@AttributeOverride(name = "plannedEndDate", column = @Column(name = "PlannedEndDate", length = 23)),
			@AttributeOverride(name = "actualStartDate", column = @Column(name = "ActualStartDate", length = 23)),
			@AttributeOverride(name = "actualEndDate", column = @Column(name = "ActualEndDate", length = 23)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 1024)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 512)),
			@AttributeOverride(name = "closedOn", column = @Column(name = "ClosedOn", length = 23)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 1024)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", length = 23)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", length = 1024)),
			@AttributeOverride(name = "lastModifiedDate", column = @Column(name = "LastModifiedDate", length = 23)),
			@AttributeOverride(name = "priority", column = @Column(name = "Priority", length = 30)),
			@AttributeOverride(name = "market", column = @Column(name = "Market", length = 1024)),
			@AttributeOverride(name = "vendor", column = @Column(name = "Vendor")),
			@AttributeOverride(name = "adhocWoid", column = @Column(name = "AdhocWOID")),
			@AttributeOverride(name = "deliveryStatus", column = @Column(name = "DeliveryStatus", length = 1024)),
			@AttributeOverride(name = "failureReason", column = @Column(name = "FailureReason", length = 1024)),
			@AttributeOverride(name = "description", column = @Column(name = "Description", length = 1024)),
			@AttributeOverride(name = "statusComment", column = @Column(name = "StatusComment", length = 5000)),
			@AttributeOverride(name = "parentWorkOrderId", column = @Column(name = "ParentWorkOrderID")),
			@AttributeOverride(name = "workFlowVersion", column = @Column(name = "WorkFlowVersion")) })
	public TblWorkOrderBk25062018Id getId() {
		return this.id;
	}

	public void setId(TblWorkOrderBk25062018Id id) {
		this.id = id;
	}

}
