package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWorkFlowStepAttr generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_FLOW_STEP_ATTR", schema = "transactionalData")
public class TblWorkFlowStepAttr implements java.io.Serializable {

	private int attributeId;
	private Integer flowChartStepId;
	private Serializable attributeType;
	private Serializable attributeName;
	private Serializable attributeValue;
	private Serializable createdBy;
	private Date createdOn;

	public TblWorkFlowStepAttr() {
	}

	public TblWorkFlowStepAttr(int attributeId) {
		this.attributeId = attributeId;
	}

	public TblWorkFlowStepAttr(int attributeId, Integer flowChartStepId, Serializable attributeType,
			Serializable attributeName, Serializable attributeValue, Serializable createdBy, Date createdOn) {
		this.attributeId = attributeId;
		this.flowChartStepId = flowChartStepId;
		this.attributeType = attributeType;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	@Id

	@Column(name = "AttributeID", unique = true, nullable = false)
	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	@Column(name = "FlowChartStepID")
	public Integer getFlowChartStepId() {
		return this.flowChartStepId;
	}

	public void setFlowChartStepId(Integer flowChartStepId) {
		this.flowChartStepId = flowChartStepId;
	}

	@Column(name = "AttributeType")
	public Serializable getAttributeType() {
		return this.attributeType;
	}

	public void setAttributeType(Serializable attributeType) {
		this.attributeType = attributeType;
	}

	@Column(name = "AttributeName")
	public Serializable getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(Serializable attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "AttributeValue")
	public Serializable getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(Serializable attributeValue) {
		this.attributeValue = attributeValue;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
