package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblWorkOrderFlowchartDetails generated by hbm2java
 */
@Entity
@Table(name = "TBL_WORK_ORDER_FLOWCHART_DETAILS", schema = "transactionalData")
public class TblWorkOrderFlowchartDetails implements java.io.Serializable {

	private TblWorkOrderFlowchartDetailsId id;

	public TblWorkOrderFlowchartDetails() {
	}

	public TblWorkOrderFlowchartDetails(TblWorkOrderFlowchartDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "woflowChartId", column = @Column(name = "WOFlowChartID", nullable = false)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID")),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 1024)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", length = 23)),
			@AttributeOverride(name = "parentSubActivityFlowChartDefId", column = @Column(name = "ParentSubActivityFlowChartDefID")) })
	public TblWorkOrderFlowchartDetailsId getId() {
		return this.id;
	}

	public void setId(TblWorkOrderFlowchartDetailsId id) {
		this.id = id;
	}

}
