package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tool generated by hbm2java
 */
@Entity
@Table(name = "TOOL", schema = "dbo")
public class Tool implements java.io.Serializable {

	private ToolId id;

	public Tool() {
	}

	public Tool(ToolId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "fcstepId", column = @Column(name = "FCStepID", nullable = false)),
			@AttributeOverride(name = "presentTool", column = @Column(name = "Present_Tool")),
			@AttributeOverride(name = "newTool1", column = @Column(name = "New_Tool_1", nullable = false)) })
	public ToolId getId() {
		return this.id;
	}

	public void setId(ToolId id) {
		this.id = id;
	}

}
