package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UploadExcelForWorkflow generated by hbm2java
 */
@Entity
@Table(name = "UPLOAD_EXCEL_FOR_WORKFLOW", schema = "dbo")
public class UploadExcelForWorkflow implements java.io.Serializable {

	private int fileId;
	private Serializable fileName;
	private Serializable filePath;
	private Integer flowChartDefId;
	private Integer projectId;
	private Serializable createdBy;
	private Date createdOn;
	private Integer isActive;

	public UploadExcelForWorkflow() {
	}

	public UploadExcelForWorkflow(int fileId) {
		this.fileId = fileId;
	}

	public UploadExcelForWorkflow(int fileId, Serializable fileName, Serializable filePath, Integer flowChartDefId,
			Integer projectId, Serializable createdBy, Date createdOn, Integer isActive) {
		this.fileId = fileId;
		this.fileName = fileName;
		this.filePath = filePath;
		this.flowChartDefId = flowChartDefId;
		this.projectId = projectId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isActive = isActive;
	}

	@Id

	@Column(name = "FileID", unique = true, nullable = false)
	public int getFileId() {
		return this.fileId;
	}

	public void setFileId(int fileId) {
		this.fileId = fileId;
	}

	@Column(name = "FileName")
	public Serializable getFileName() {
		return this.fileName;
	}

	public void setFileName(Serializable fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FilePath")
	public Serializable getFilePath() {
		return this.filePath;
	}

	public void setFilePath(Serializable filePath) {
		this.filePath = filePath;
	}

	@Column(name = "FlowChartDefID")
	public Integer getFlowChartDefId() {
		return this.flowChartDefId;
	}

	public void setFlowChartDefId(Integer flowChartDefId) {
		this.flowChartDefId = flowChartDefId;
	}

	@Column(name = "ProjectID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "isActive")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

}
