package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwAdhocWoissue generated by hbm2java
 */
@Entity
@Table(name = "vw_AdhocWOIssue", schema = "dbo")
public class VwAdhocWoissue implements java.io.Serializable {

	private VwAdhocWoissueId id;

	public VwAdhocWoissue() {
	}

	public VwAdhocWoissue(VwAdhocWoissueId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted")),
			@AttributeOverride(name = "status", column = @Column(name = "Status")),
			@AttributeOverride(name = "adhocWoid", column = @Column(name = "AdhocWOID", nullable = false)),
			@AttributeOverride(name = "awoActive", column = @Column(name = "AWO Active")),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID", nullable = false)),
			@AttributeOverride(name = "woActive", column = @Column(name = "WO Active")) })
	public VwAdhocWoissueId getId() {
		return this.id;
	}

	public void setId(VwAdhocWoissueId id) {
		this.id = id;
	}

}
