package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwAllocatedResources generated by hbm2java
 */
@Entity
@Table(name = "vw_AllocatedResources", schema = "refData")
public class VwAllocatedResources implements java.io.Serializable {

	private VwAllocatedResourcesId id;

	public VwAllocatedResources() {
	}

	public VwAllocatedResources(VwAllocatedResourcesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "signum", column = @Column(name = "Signum", nullable = false, length = 8)),
			@AttributeOverride(name = "employeeName", column = @Column(name = "EmployeeName", nullable = false, length = 500)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "positionid", column = @Column(name = "Positionid")),
			@AttributeOverride(name = "wfid", column = @Column(name = "WFID")),
			@AttributeOverride(name = "blockDate", column = @Column(name = "BlockDate", length = 10)),
			@AttributeOverride(name = "blockedHrs", column = @Column(name = "BlockedHrs", precision = 53, scale = 0)),
			@AttributeOverride(name = "blockWeek", column = @Column(name = "BlockWeek")),
			@AttributeOverride(name = "resourceRequestId", column = @Column(name = "ResourceRequestID")),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID")),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "domainSubDomain", column = @Column(name = "Domain_SubDomain", length = 259)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)) })
	public VwAllocatedResourcesId getId() {
		return this.id;
	}

	public void setId(VwAllocatedResourcesId id) {
		this.id = id;
	}

}
