package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwBookingIssue generated by hbm2java
 */
@Entity
@Table(name = "vw_BookingIssue", schema = "dbo")
public class VwBookingIssue implements java.io.Serializable {

	private VwBookingIssueId id;

	public VwBookingIssue() {
	}

	public VwBookingIssue(VwBookingIssueId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "woid", column = @Column(name = "WOID", nullable = false)),
			@AttributeOverride(name = "bookingId", column = @Column(name = "BookingID", nullable = false)),
			@AttributeOverride(name = "woActive", column = @Column(name = "WO Active")),
			@AttributeOverride(name = "lastModifiedDate", column = @Column(name = "LastModifiedDate", length = 23)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", length = 23)) })
	public VwBookingIssueId getId() {
		return this.id;
	}

	public void setId(VwBookingIssueId id) {
		this.id = id;
	}

}
