package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwBookingIssueId generated by hbm2java
 */
@Embeddable
public class VwBookingIssueId implements java.io.Serializable {

	private int woid;
	private int bookingId;
	private Boolean woActive;
	private Date lastModifiedDate;
	private Date endDate;

	public VwBookingIssueId() {
	}

	public VwBookingIssueId(int woid, int bookingId) {
		this.woid = woid;
		this.bookingId = bookingId;
	}

	public VwBookingIssueId(int woid, int bookingId, Boolean woActive, Date lastModifiedDate, Date endDate) {
		this.woid = woid;
		this.bookingId = bookingId;
		this.woActive = woActive;
		this.lastModifiedDate = lastModifiedDate;
		this.endDate = endDate;
	}

	@Column(name = "WOID", nullable = false)
	public int getWoid() {
		return this.woid;
	}

	public void setWoid(int woid) {
		this.woid = woid;
	}

	@Column(name = "BookingID", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "WO Active")
	public Boolean getWoActive() {
		return this.woActive;
	}

	public void setWoActive(Boolean woActive) {
		this.woActive = woActive;
	}

	@Column(name = "LastModifiedDate", length = 23)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwBookingIssueId))
			return false;
		VwBookingIssueId castOther = (VwBookingIssueId) other;

		return (this.getWoid() == castOther.getWoid()) && (this.getBookingId() == castOther.getBookingId())
				&& ((this.getWoActive() == castOther.getWoActive()) || (this.getWoActive() != null
						&& castOther.getWoActive() != null && this.getWoActive().equals(castOther.getWoActive())))
				&& ((this.getLastModifiedDate() == castOther.getLastModifiedDate())
						|| (this.getLastModifiedDate() != null && castOther.getLastModifiedDate() != null
								&& this.getLastModifiedDate().equals(castOther.getLastModifiedDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this.getEndDate() != null
						&& castOther.getEndDate() != null && this.getEndDate().equals(castOther.getEndDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWoid();
		result = 37 * result + this.getBookingId();
		result = 37 * result + (getWoActive() == null ? 0 : this.getWoActive().hashCode());
		result = 37 * result + (getLastModifiedDate() == null ? 0 : this.getLastModifiedDate().hashCode());
		result = 37 * result + (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		return result;
	}

}
