package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIsfProjectdetails generated by hbm2java
 */
@Entity
@Table(name = "vw_ISF_Projectdetails", schema = "dbo")
public class VwIsfProjectdetails implements java.io.Serializable {

	private VwIsfProjectdetailsId id;

	public VwIsfProjectdetails() {
	}

	public VwIsfProjectdetails(VwIsfProjectdetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "projectType", column = @Column(name = "ProjectType")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "cpm", column = @Column(name = "CPM")),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator")),
			@AttributeOverride(name = "projectStartDate", column = @Column(name = "ProjectStartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "projectEndDate", column = @Column(name = "ProjectEndDate", length = 23)),
			@AttributeOverride(name = "projectCreatedOn", column = @Column(name = "ProjectCreatedON", length = 23)),
			@AttributeOverride(name = "projectStatus", column = @Column(name = "ProjectStatus")),
			@AttributeOverride(name = "operationalManager", column = @Column(name = "OperationalManager")),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subdomain", column = @Column(name = "subdomain", length = 128)),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)) })
	public VwIsfProjectdetailsId getId() {
		return this.id;
	}

	public void setId(VwIsfProjectdetailsId id) {
		this.id = id;
	}

}
