package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIsfWorkOrderExecutionSummaryExcelDumpBcp generated by hbm2java
 */
@Entity
@Table(name = "vw_ISF_WorkOrderExecutionSummary_ExcelDump_bcp", schema = "dbo")
public class VwIsfWorkOrderExecutionSummaryExcelDumpBcp implements java.io.Serializable {

	private VwIsfWorkOrderExecutionSummaryExcelDumpBcpId id;

	public VwIsfWorkOrderExecutionSummaryExcelDumpBcp() {
	}

	public VwIsfWorkOrderExecutionSummaryExcelDumpBcp(VwIsfWorkOrderExecutionSummaryExcelDumpBcpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID", length = 15)),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", length = 15)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID", length = 15)),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID", length = 15)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID", length = 15)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 128)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID", length = 15)),
			@AttributeOverride(name = "activity", column = @Column(name = "Activity", length = 512)),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID", length = 15)),
			@AttributeOverride(name = "woplanId", column = @Column(name = "WOPlanID", length = 15)),
			@AttributeOverride(name = "woActualStartDate", column = @Column(name = "WO Actual start Date", length = 50)),
			@AttributeOverride(name = "woActualEndDate", column = @Column(name = "WO Actual End Date", length = 50)),
			@AttributeOverride(name = "woPlannedStartDate", column = @Column(name = "WO Planned Start Date", length = 50)),
			@AttributeOverride(name = "woPlannedEndDate", column = @Column(name = "WO Planned End Date", length = 50)),
			@AttributeOverride(name = "woSignum", column = @Column(name = "WO Signum", length = 1024)),
			@AttributeOverride(name = "woStatus", column = @Column(name = "WO Status", length = 512)),
			@AttributeOverride(name = "executionType", column = @Column(name = "Execution Type", length = 1024)),
			@AttributeOverride(name = "botId", column = @Column(name = "BOT Id", length = 15)),
			@AttributeOverride(name = "taskId", column = @Column(name = "TaskID", length = 15)),
			@AttributeOverride(name = "task", column = @Column(name = "Task", length = 1024)),
			@AttributeOverride(name = "bookingId", column = @Column(name = "BookingID", length = 15)),
			@AttributeOverride(name = "parentBookingDetailsId", column = @Column(name = "ParentBookingDetailsID", length = 22)),
			@AttributeOverride(name = "bookStartDate", column = @Column(name = "Book Start Date", length = 50)),
			@AttributeOverride(name = "bookEndDate", column = @Column(name = "Book End Date", length = 50)),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", length = 15)),
			@AttributeOverride(name = "type", column = @Column(name = "Type", length = 512)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 512)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 512)),
			@AttributeOverride(name = "workFlowVersion", column = @Column(name = "WorkFlowVersion", length = 15)),
			@AttributeOverride(name = "reason", column = @Column(name = "Reason", length = 1024)),
			@AttributeOverride(name = "outputLink", column = @Column(name = "OutputLink")) })
	public VwIsfWorkOrderExecutionSummaryExcelDumpBcpId getId() {
		return this.id;
	}

	public void setId(VwIsfWorkOrderExecutionSummaryExcelDumpBcpId id) {
		this.id = id;
	}

}
