package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIsfWfDetail generated by hbm2java
 */
@Entity
@Table(name = "vw_ISF_WF_Detail", schema = "dbo")
public class VwIsfWfDetail implements java.io.Serializable {

	private VwIsfWfDetailId id;

	public VwIsfWfDetail() {
	}

	public VwIsfWfDetail(VwIsfWfDetailId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subdomain", column = @Column(name = "subdomain", length = 128)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)),
			@AttributeOverride(name = "subActivityFlowChartDefId", column = @Column(name = "SubActivityFlowChartDefID")),
			@AttributeOverride(name = "fcstepDetailsId", column = @Column(name = "FCStepDetailsID")),
			@AttributeOverride(name = "executionType", column = @Column(name = "ExecutionType", length = 1024)),
			@AttributeOverride(name = "automatedWfs", column = @Column(name = "Automated WFs")) })
	public VwIsfWfDetailId getId() {
		return this.id;
	}

	public void setId(VwIsfWfDetailId id) {
		this.id = id;
	}

}
