package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIsfPositiondetails generated by hbm2java
 */
@Entity
@Table(name = "vw_ISF_Positiondetails", schema = "dbo")
public class VwIsfPositiondetails implements java.io.Serializable {

	private VwIsfPositiondetailsId id;

	public VwIsfPositiondetails() {
	}

	public VwIsfPositiondetails(VwIsfPositiondetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "projectType", column = @Column(name = "ProjectType")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "cpm", column = @Column(name = "CPM")),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator")),
			@AttributeOverride(name = "projectStartDate", column = @Column(name = "ProjectStartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "projectEndDate", column = @Column(name = "ProjectEndDate", length = 23)),
			@AttributeOverride(name = "projectCreatedOn", column = @Column(name = "ProjectCreatedON", length = 23)),
			@AttributeOverride(name = "projectStatus", column = @Column(name = "ProjectStatus")),
			@AttributeOverride(name = "operationalManager", column = @Column(name = "OperationalManager")),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subdomain", column = @Column(name = "subdomain", length = 128)),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "resourceRequestId", column = @Column(name = "ResourceRequestID", nullable = false)),
			@AttributeOverride(name = "resourceType", column = @Column(name = "ResourceType")),
			@AttributeOverride(name = "resourcePositionId", column = @Column(name = "ResourcePositionID")),
			@AttributeOverride(name = "positionStatus", column = @Column(name = "PositionStatus", length = 100)),
			@AttributeOverride(name = "remoteOnsite", column = @Column(name = "Remote_Onsite")),
			@AttributeOverride(name = "resourcPositionIsActive", column = @Column(name = "ResourcPositionIsActive")),
			@AttributeOverride(name = "workEffortId", column = @Column(name = "WorkEffortID")),
			@AttributeOverride(name = "workEffortStartDate", column = @Column(name = "WorkEffortStartDate", length = 10)),
			@AttributeOverride(name = "workEffortEndDate", column = @Column(name = "WorkEffortEndDate", length = 10)),
			@AttributeOverride(name = "workEffortDuration", column = @Column(name = "WorkEffortDuration")),
			@AttributeOverride(name = "ftePercent", column = @Column(name = "FTE_Percent", precision = 53, scale = 0)),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", precision = 53, scale = 0)),
			@AttributeOverride(name = "signum", column = @Column(name = "Signum", length = 8)),
			@AttributeOverride(name = "workEffortStatus", column = @Column(name = "WorkEffortStatus", length = 100)),
			@AttributeOverride(name = "woekEffortIsActive", column = @Column(name = "WoekEffortIsActive")),
			@AttributeOverride(name = "crid", column = @Column(name = "CRID")),
			@AttributeOverride(name = "workEffortPositionStatus", column = @Column(name = "WorkEffortPositionStatus", length = 100)),
			@AttributeOverride(name = "workEffortCreatedBy", column = @Column(name = "WorkEffortCreatedBy", length = 8)),
			@AttributeOverride(name = "workEffortCreatedOn", column = @Column(name = "WorkEffortCreatedOn", length = 23)) })
	public VwIsfPositiondetailsId getId() {
		return this.id;
	}

	public void setId(VwIsfPositiondetailsId id) {
		this.id = id;
	}

}
