package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIsfWorkOrderExecutionSummary generated by hbm2java
 */
@Entity
@Table(name = "vw_ISF_WorkOrderExecutionSummary", schema = "dbo")
public class VwIsfWorkOrderExecutionSummary implements java.io.Serializable {

	private VwIsfWorkOrderExecutionSummaryId id;

	public VwIsfWorkOrderExecutionSummary() {
	}

	public VwIsfWorkOrderExecutionSummary(VwIsfWorkOrderExecutionSummaryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subdomain", column = @Column(name = "subdomain", length = 128)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "activity", column = @Column(name = "Activity", length = 512)),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "woplanId", column = @Column(name = "WOPlanID")),
			@AttributeOverride(name = "woActualStartDate", column = @Column(name = "WO Actual start Date", length = 120)),
			@AttributeOverride(name = "woActualEndDate", column = @Column(name = "WO Actual End Date", length = 120)),
			@AttributeOverride(name = "woPlannedStartDate", column = @Column(name = "WO Planned Start Date", length = 120)),
			@AttributeOverride(name = "woPlannedEndDate", column = @Column(name = "WO Planned End Date", length = 120)),
			@AttributeOverride(name = "woSignum", column = @Column(name = "WO Signum", length = 1024)),
			@AttributeOverride(name = "woStatus", column = @Column(name = "WO Status", length = 512)),
			@AttributeOverride(name = "executionType", column = @Column(name = "Execution Type", length = 1024)),
			@AttributeOverride(name = "botId", column = @Column(name = "BOT Id")),
			@AttributeOverride(name = "taskId", column = @Column(name = "TaskID")),
			@AttributeOverride(name = "task", column = @Column(name = "Task", length = 1024)),
			@AttributeOverride(name = "bookingId", column = @Column(name = "BookingID", nullable = false)),
			@AttributeOverride(name = "parentBookingDetailsId", column = @Column(name = "ParentBookingDetailsID")),
			@AttributeOverride(name = "bookStartDate", column = @Column(name = "Book Start Date", length = 120)),
			@AttributeOverride(name = "bookEndDate", column = @Column(name = "Book End Date", length = 120)),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", precision = 53, scale = 0)),
			@AttributeOverride(name = "type", column = @Column(name = "Type", length = 512)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 512)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 512)),
			@AttributeOverride(name = "workFlowVersion", column = @Column(name = "WorkFlowVersion")),
			@AttributeOverride(name = "reason", column = @Column(name = "Reason", length = 1024)),
			@AttributeOverride(name = "outputLink", column = @Column(name = "OutputLink")) })
	public VwIsfWorkOrderExecutionSummaryId getId() {
		return this.id;
	}

	public void setId(VwIsfWorkOrderExecutionSummaryId id) {
		this.id = id;
	}

}
