package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIsfDeployedBotDetails generated by hbm2java
 */
@Entity
@Table(name = "vw_ISF_Deployed_BOT_Details", schema = "dbo")
public class VwIsfDeployedBotDetails implements java.io.Serializable {

	private VwIsfDeployedBotDetailsId id;

	public VwIsfDeployedBotDetails() {
	}

	public VwIsfDeployedBotDetails(VwIsfDeployedBotDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idbehaviourDetails", column = @Column(name = "idbehaviourDetails")),
			@AttributeOverride(name = "idShTasks", column = @Column(name = "idSH_Tasks", nullable = false)),
			@AttributeOverride(name = "shBehaviourDetailsName", column = @Column(name = "SH_behaviourDetailsName", nullable = false, length = 350)),
			@AttributeOverride(name = "shTasksname", column = @Column(name = "SH_Tasksname", nullable = false, length = 100)),
			@AttributeOverride(name = "shOutFolder", column = @Column(name = "SH_Out_Folder", nullable = false, length = 45)),
			@AttributeOverride(name = "shActionName", column = @Column(name = "SH_Action_Name", length = 100)),
			@AttributeOverride(name = "shClass", column = @Column(name = "SH_Class", nullable = false, length = 400)),
			@AttributeOverride(name = "shValidation", column = @Column(name = "SH_Validation", nullable = false, length = 3)),
			@AttributeOverride(name = "shType", column = @Column(name = "SH_Type", nullable = false, length = 7)),
			@AttributeOverride(name = "shInitiator", column = @Column(name = "SH_Initiator", length = 10)),
			@AttributeOverride(name = "shDetails", column = @Column(name = "SH_Details")),
			@AttributeOverride(name = "shDeployedAt", column = @Column(name = "SH_DeployedAt", length = 27)),
			@AttributeOverride(name = "shBehaviourDetailsStatus", column = @Column(name = "SH_behaviourDetailsStatus", nullable = false, length = 10)),
			@AttributeOverride(name = "shManualTime", column = @Column(name = "SH_ManualTime", length = 10)),
			@AttributeOverride(name = "shShtime", column = @Column(name = "SH_SHTime", length = 10)),
			@AttributeOverride(name = "shSpoc", column = @Column(name = "SH_SPOC", length = 45)),
			@AttributeOverride(name = "shProject", column = @Column(name = "SH_Project", length = 45)),
			@AttributeOverride(name = "shRegion", column = @Column(name = "SH_Region", length = 45)),
			@AttributeOverride(name = "shDeveloper", column = @Column(name = "SH_Developer", length = 45)),
			@AttributeOverride(name = "shCategory", column = @Column(name = "SH_Category", length = 45)),
			@AttributeOverride(name = "shTimeBookingAvailable", column = @Column(name = "SH_TimeBookingAvailable", length = 15)),
			@AttributeOverride(name = "shUseFrequency", column = @Column(name = "SH_UseFrequency", length = 45)),
			@AttributeOverride(name = "shUserCount", column = @Column(name = "SH_UserCount")),
			@AttributeOverride(name = "shNdxactivity", column = @Column(name = "SH_NDXActivity", length = 250)),
			@AttributeOverride(name = "shNdxsubActivity", column = @Column(name = "SH_NDXSubActivity", length = 250)),
			@AttributeOverride(name = "shDomain", column = @Column(name = "SH_Domain", length = 45)),
			@AttributeOverride(name = "shJarName", column = @Column(name = "SH_JarName", length = 45)),
			@AttributeOverride(name = "shBotfor", column = @Column(name = "SH_BOTFor", length = 45)),
			@AttributeOverride(name = "shParallelWoexecution", column = @Column(name = "SH_ParallelWOExecution", length = 3)),
			@AttributeOverride(name = "shSubactivityId", column = @Column(name = "SH_Subactivity_ID", length = 100)),
			@AttributeOverride(name = "shProjectName", column = @Column(name = "SH_ProjectName", length = 100)),
			@AttributeOverride(name = "shCodeReuseFactor", column = @Column(name = "SH_CodeReuseFactor", length = 45)),
			@AttributeOverride(name = "shLineOfCode", column = @Column(name = "SH_LineOfCode", length = 45)),
			@AttributeOverride(name = "shUatstatus", column = @Column(name = "SH_UATStatus", length = 3)),
			@AttributeOverride(name = "shUatowner", column = @Column(name = "SH_UATOwner", length = 45)),
			@AttributeOverride(name = "shUatcompletionDate", column = @Column(name = "SH_UATCompletionDate", length = 27)) })
	public VwIsfDeployedBotDetailsId getId() {
		return this.id;
	}

	public void setId(VwIsfDeployedBotDetailsId id) {
		this.id = id;
	}

}
