package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIsfUserAccess generated by hbm2java
 */
@Entity
@Table(name = "VW_ISF_USER_ACCESS", schema = "dbo")
public class VwIsfUserAccess implements java.io.Serializable {

	private VwIsfUserAccessId id;

	public VwIsfUserAccess() {
	}

	public VwIsfUserAccess(VwIsfUserAccessId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accessProfileName", column = @Column(name = "AccessProfileName", length = 1024)),
			@AttributeOverride(name = "role", column = @Column(name = "Role", length = 512)),
			@AttributeOverride(name = "alias", column = @Column(name = "Alias", length = 128)),
			@AttributeOverride(name = "organisation", column = @Column(name = "Organisation", length = 1024)),
			@AttributeOverride(name = "employeeName", column = @Column(name = "EmployeeName", nullable = false, length = 500)),
			@AttributeOverride(name = "signum", column = @Column(name = "Signum", nullable = false, length = 8)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 100)),
			@AttributeOverride(name = "contactNumber", column = @Column(name = "ContactNumber", length = 13)),
			@AttributeOverride(name = "officeBuilding", column = @Column(name = "OfficeBuilding", length = 100)),
			@AttributeOverride(name = "hrlocation", column = @Column(name = "HRLocation", length = 100)),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName", length = 100)),
			@AttributeOverride(name = "city", column = @Column(name = "City", length = 100)),
			@AttributeOverride(name = "companyName", column = @Column(name = "CompanyName", length = 150)),
			@AttributeOverride(name = "jobName", column = @Column(name = "JobName", length = 50)),
			@AttributeOverride(name = "jobRoleFamily", column = @Column(name = "JobRoleFamily", length = 50)),
			@AttributeOverride(name = "jobStage", column = @Column(name = "JobStage", length = 50)),
			@AttributeOverride(name = "functionalArea", column = @Column(name = "FunctionalArea", length = 100)),
			@AttributeOverride(name = "industryVertical", column = @Column(name = "IndustryVertical", length = 100)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 100)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 100)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 100)),
			@AttributeOverride(name = "employeeEmailId", column = @Column(name = "EmployeeEmailID", length = 100)),
			@AttributeOverride(name = "isLineManager", column = @Column(name = "IsLineManager", length = 10)),
			@AttributeOverride(name = "managerSignum", column = @Column(name = "ManagerSignum", length = 8)),
			@AttributeOverride(name = "parentUnit", column = @Column(name = "ParentUnit", length = 150)),
			@AttributeOverride(name = "unit", column = @Column(name = "Unit", length = 100)),
			@AttributeOverride(name = "personnelNumber", column = @Column(name = "PersonnelNumber", nullable = false)) })
	public VwIsfUserAccessId getId() {
		return this.id;
	}

	public void setId(VwIsfUserAccessId id) {
		this.id = id;
	}

}
