package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwManaWoNodeFilter generated by hbm2java
 */
@Entity
@Table(name = "vw_MANA_WO_Node_Filter", schema = "dbo")
public class VwManaWoNodeFilter implements java.io.Serializable {

	private String nodeNames;

	public VwManaWoNodeFilter() {
	}

	public VwManaWoNodeFilter(String nodeNames) {
		this.nodeNames = nodeNames;
	}

	@Id

	@Column(name = "NodeNames")
	public String getNodeNames() {
		return this.nodeNames;
	}

	public void setNodeNames(String nodeNames) {
		this.nodeNames = nodeNames;
	}

}
