package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwMasterDataSubActivityTaskId generated by hbm2java
 */
@Embeddable
public class VwMasterDataSubActivityTaskId implements java.io.Serializable {

	private int subActivityId;
	private Integer domainId;
	private String domain;
	private String subDomain;
	private Integer serviceAreaId;
	private String serviceArea;
	private String subServiceArea;
	private Integer technologyId;
	private String technology;
	private String activity;
	private String subActivity;
	private Integer taskId;
	private String task;
	private String executionType;

	public VwMasterDataSubActivityTaskId() {
	}

	public VwMasterDataSubActivityTaskId(int subActivityId) {
		this.subActivityId = subActivityId;
	}

	public VwMasterDataSubActivityTaskId(int subActivityId, Integer domainId, String domain, String subDomain,
			Integer serviceAreaId, String serviceArea, String subServiceArea, Integer technologyId, String technology,
			String activity, String subActivity, Integer taskId, String task, String executionType) {
		this.subActivityId = subActivityId;
		this.domainId = domainId;
		this.domain = domain;
		this.subDomain = subDomain;
		this.serviceAreaId = serviceAreaId;
		this.serviceArea = serviceArea;
		this.subServiceArea = subServiceArea;
		this.technologyId = technologyId;
		this.technology = technology;
		this.activity = activity;
		this.subActivity = subActivity;
		this.taskId = taskId;
		this.task = task;
		this.executionType = executionType;
	}

	@Column(name = "SubActivityID", nullable = false)
	public int getSubActivityId() {
		return this.subActivityId;
	}

	public void setSubActivityId(int subActivityId) {
		this.subActivityId = subActivityId;
	}

	@Column(name = "DomainID")
	public Integer getDomainId() {
		return this.domainId;
	}

	public void setDomainId(Integer domainId) {
		this.domainId = domainId;
	}

	@Column(name = "Domain", length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "SubDomain", length = 128)
	public String getSubDomain() {
		return this.subDomain;
	}

	public void setSubDomain(String subDomain) {
		this.subDomain = subDomain;
	}

	@Column(name = "ServiceAreaID")
	public Integer getServiceAreaId() {
		return this.serviceAreaId;
	}

	public void setServiceAreaId(Integer serviceAreaId) {
		this.serviceAreaId = serviceAreaId;
	}

	@Column(name = "ServiceArea", length = 128)
	public String getServiceArea() {
		return this.serviceArea;
	}

	public void setServiceArea(String serviceArea) {
		this.serviceArea = serviceArea;
	}

	@Column(name = "SubServiceArea", length = 128)
	public String getSubServiceArea() {
		return this.subServiceArea;
	}

	public void setSubServiceArea(String subServiceArea) {
		this.subServiceArea = subServiceArea;
	}

	@Column(name = "TechnologyID")
	public Integer getTechnologyId() {
		return this.technologyId;
	}

	public void setTechnologyId(Integer technologyId) {
		this.technologyId = technologyId;
	}

	@Column(name = "Technology", length = 128)
	public String getTechnology() {
		return this.technology;
	}

	public void setTechnology(String technology) {
		this.technology = technology;
	}

	@Column(name = "Activity", length = 512)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "SubActivity", length = 512)
	public String getSubActivity() {
		return this.subActivity;
	}

	public void setSubActivity(String subActivity) {
		this.subActivity = subActivity;
	}

	@Column(name = "TaskID")
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "Task", length = 512)
	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	@Column(name = "ExecutionType", length = 128)
	public String getExecutionType() {
		return this.executionType;
	}

	public void setExecutionType(String executionType) {
		this.executionType = executionType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwMasterDataSubActivityTaskId))
			return false;
		VwMasterDataSubActivityTaskId castOther = (VwMasterDataSubActivityTaskId) other;

		return (this.getSubActivityId() == castOther.getSubActivityId())
				&& ((this.getDomainId() == castOther.getDomainId()) || (this.getDomainId() != null
						&& castOther.getDomainId() != null && this.getDomainId().equals(castOther.getDomainId())))
				&& ((this.getDomain() == castOther.getDomain()) || (this.getDomain() != null
						&& castOther.getDomain() != null && this.getDomain().equals(castOther.getDomain())))
				&& ((this.getSubDomain() == castOther.getSubDomain()) || (this.getSubDomain() != null
						&& castOther.getSubDomain() != null && this.getSubDomain().equals(castOther.getSubDomain())))
				&& ((this.getServiceAreaId() == castOther.getServiceAreaId())
						|| (this.getServiceAreaId() != null && castOther.getServiceAreaId() != null
								&& this.getServiceAreaId().equals(castOther.getServiceAreaId())))
				&& ((this.getServiceArea() == castOther.getServiceArea())
						|| (this.getServiceArea() != null && castOther.getServiceArea() != null
								&& this.getServiceArea().equals(castOther.getServiceArea())))
				&& ((this.getSubServiceArea() == castOther.getSubServiceArea())
						|| (this.getSubServiceArea() != null && castOther.getSubServiceArea() != null
								&& this.getSubServiceArea().equals(castOther.getSubServiceArea())))
				&& ((this.getTechnologyId() == castOther.getTechnologyId())
						|| (this.getTechnologyId() != null && castOther.getTechnologyId() != null
								&& this.getTechnologyId().equals(castOther.getTechnologyId())))
				&& ((this.getTechnology() == castOther.getTechnology()) || (this.getTechnology() != null
						&& castOther.getTechnology() != null && this.getTechnology().equals(castOther.getTechnology())))
				&& ((this.getActivity() == castOther.getActivity()) || (this.getActivity() != null
						&& castOther.getActivity() != null && this.getActivity().equals(castOther.getActivity())))
				&& ((this.getSubActivity() == castOther.getSubActivity())
						|| (this.getSubActivity() != null && castOther.getSubActivity() != null
								&& this.getSubActivity().equals(castOther.getSubActivity())))
				&& ((this.getTaskId() == castOther.getTaskId()) || (this.getTaskId() != null
						&& castOther.getTaskId() != null && this.getTaskId().equals(castOther.getTaskId())))
				&& ((this.getTask() == castOther.getTask()) || (this.getTask() != null && castOther.getTask() != null
						&& this.getTask().equals(castOther.getTask())))
				&& ((this.getExecutionType() == castOther.getExecutionType())
						|| (this.getExecutionType() != null && castOther.getExecutionType() != null
								&& this.getExecutionType().equals(castOther.getExecutionType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSubActivityId();
		result = 37 * result + (getDomainId() == null ? 0 : this.getDomainId().hashCode());
		result = 37 * result + (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result + (getSubDomain() == null ? 0 : this.getSubDomain().hashCode());
		result = 37 * result + (getServiceAreaId() == null ? 0 : this.getServiceAreaId().hashCode());
		result = 37 * result + (getServiceArea() == null ? 0 : this.getServiceArea().hashCode());
		result = 37 * result + (getSubServiceArea() == null ? 0 : this.getSubServiceArea().hashCode());
		result = 37 * result + (getTechnologyId() == null ? 0 : this.getTechnologyId().hashCode());
		result = 37 * result + (getTechnology() == null ? 0 : this.getTechnology().hashCode());
		result = 37 * result + (getActivity() == null ? 0 : this.getActivity().hashCode());
		result = 37 * result + (getSubActivity() == null ? 0 : this.getSubActivity().hashCode());
		result = 37 * result + (getTaskId() == null ? 0 : this.getTaskId().hashCode());
		result = 37 * result + (getTask() == null ? 0 : this.getTask().hashCode());
		result = 37 * result + (getExecutionType() == null ? 0 : this.getExecutionType().hashCode());
		return result;
	}

}
