package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwManaFilters generated by hbm2java
 */
@Entity
@Table(name = "vw_MANA_Filters", schema = "dbo")
public class VwManaFilters implements java.io.Serializable {

	private VwManaFiltersId id;

	public VwManaFilters() {
	}

	public VwManaFilters(VwManaFiltersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID")),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID")),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)),
			@AttributeOverride(name = "domainSubDomainSubActivity", column = @Column(name = "Domain_subDomain_subActivity", length = 770)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "woname", column = @Column(name = "WOName")),
			@AttributeOverride(name = "woStatus", column = @Column(name = "WO Status", length = 512)) })
	public VwManaFiltersId getId() {
		return this.id;
	}

	public void setId(VwManaFiltersId id) {
		this.id = id;
	}

}
