package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwMissingToolId generated by hbm2java
 */
@Entity
@Table(name = "vw_missingToolID", schema = "dbo")
public class VwMissingToolId implements java.io.Serializable {

	private VwMissingToolIdId id;

	public VwMissingToolId() {
	}

	public VwMissingToolId(VwMissingToolIdId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", precision = 53, scale = 0)),
			@AttributeOverride(name = "type", column = @Column(name = "Type", length = 512)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 512)),
			@AttributeOverride(name = "woplanId", column = @Column(name = "WOPlanID")),
			@AttributeOverride(name = "woActualStartDate", column = @Column(name = "WO Actual start Date", length = 23)),
			@AttributeOverride(name = "woActualEndDate", column = @Column(name = "WO Actual End Date", length = 23)),
			@AttributeOverride(name = "woPlannedStartDate", column = @Column(name = "WO Planned Start Date", length = 23)),
			@AttributeOverride(name = "woPlannedEndDate", column = @Column(name = "WO Planned End Date", length = 23)),
			@AttributeOverride(name = "woSignum", column = @Column(name = "WO Signum", length = 1024)),
			@AttributeOverride(name = "woStatus", column = @Column(name = "WO Status", length = 512)),
			@AttributeOverride(name = "workFlowVersion", column = @Column(name = "WorkFlowVersion")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "workFlowName", column = @Column(name = "WorkFlowName")),
			@AttributeOverride(name = "signumid", column = @Column(name = "SIGNUMID", length = 512)),
			@AttributeOverride(name = "taskId", column = @Column(name = "TaskID")),
			@AttributeOverride(name = "task", column = @Column(name = "Task", length = 1024)),
			@AttributeOverride(name = "toolId", column = @Column(name = "ToolID")),
			@AttributeOverride(name = "executionType", column = @Column(name = "ExecutionType", length = 1024)),
			@AttributeOverride(name = "avgEstdEffort", column = @Column(name = "AvgEstdEffort", precision = 53, scale = 0)),
			@AttributeOverride(name = "botId", column = @Column(name = "BOT Id")),
			@AttributeOverride(name = "bookingId", column = @Column(name = "BookingID", nullable = false)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", length = 23)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", length = 23)),
			@AttributeOverride(name = "parentBookingDetailsId", column = @Column(name = "ParentBookingDetailsID")),
			@AttributeOverride(name = "reason", column = @Column(name = "Reason", length = 1024)),
			@AttributeOverride(name = "outputLink", column = @Column(name = "OutputLink")),
			@AttributeOverride(name = "stepId", column = @Column(name = "StepID")),
			@AttributeOverride(name = "stepName", column = @Column(name = "StepName", length = 1024)) })
	public VwMissingToolIdId getId() {
		return this.id;
	}

	public void setId(VwMissingToolIdId id) {
		this.id = id;
	}

}
