package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwProjectDetails generated by hbm2java
 */
@Entity
@Table(name = "VW_ProjectDetails", schema = "dbo")
public class VwProjectDetails implements java.io.Serializable {

	private VwProjectDetailsId id;

	public VwProjectDetails() {
	}

	public VwProjectDetails(VwProjectDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "PRojectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "cpmName", column = @Column(name = "CpmName", length = 250)),
			@AttributeOverride(name = "createdByName", column = @Column(name = "CreatedByName", length = 500)),
			@AttributeOverride(name = "operationalManagerName", column = @Column(name = "OperationalManagerName", length = 500)),
			@AttributeOverride(name = "projectType", column = @Column(name = "ProjectType")),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "opportunityName", column = @Column(name = "OpportunityName")),
			@AttributeOverride(name = "opportunityCode", column = @Column(name = "OpportunityCode", length = 100)),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName")),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "companyName", column = @Column(name = "CompanyName")),
			@AttributeOverride(name = "cpm", column = @Column(name = "CPM")),
			@AttributeOverride(name = "projectCreator", column = @Column(name = "ProjectCreator")),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", length = 10)),
			@AttributeOverride(name = "enddate", column = @Column(name = "Enddate", length = 10)),
			@AttributeOverride(name = "projectDescription", column = @Column(name = "ProjectDescription")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "status", column = @Column(name = "Status")),
			@AttributeOverride(name = "operationalManager", column = @Column(name = "OperationalManager")),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted")),
			@AttributeOverride(name = "approvedWlaDocument", column = @Column(name = "Approved WLA Document")),
			@AttributeOverride(name = "mailReference", column = @Column(name = "Mail Reference")),
			@AttributeOverride(name = "others", column = @Column(name = "Others")),
			@AttributeOverride(name = "rfpDocument", column = @Column(name = "RFP Document")) })
	public VwProjectDetailsId getId() {
		return this.id;
	}

	public void setId(VwProjectDetailsId id) {
		this.id = id;
	}

}
