package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwProjectDetailsId generated by hbm2java
 */
@Embeddable
public class VwProjectDetailsId implements java.io.Serializable {

	private int projectId;
	private Serializable projectName;
	private String cpmName;
	private String createdByName;
	private String operationalManagerName;
	private Serializable projectType;
	private String serviceArea;
	private Serializable opportunityName;
	private String opportunityCode;
	private Serializable countryName;
	private Serializable customerName;
	private Serializable marketAreaName;
	private Serializable companyName;
	private Serializable cpm;
	private Serializable projectCreator;
	private Date startDate;
	private Date enddate;
	private Serializable projectDescription;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable status;
	private Serializable operationalManager;
	private Integer isDeleted;
	private Integer approvedWlaDocument;
	private Integer mailReference;
	private Integer others;
	private Integer rfpDocument;

	public VwProjectDetailsId() {
	}

	public VwProjectDetailsId(int projectId) {
		this.projectId = projectId;
	}

	public VwProjectDetailsId(int projectId, Serializable projectName, String cpmName, String createdByName,
			String operationalManagerName, Serializable projectType, String serviceArea, Serializable opportunityName,
			String opportunityCode, Serializable countryName, Serializable customerName, Serializable marketAreaName,
			Serializable companyName, Serializable cpm, Serializable projectCreator, Date startDate, Date enddate,
			Serializable projectDescription, Serializable createdBy, Date createdOn, Serializable status,
			Serializable operationalManager, Integer isDeleted, Integer approvedWlaDocument, Integer mailReference,
			Integer others, Integer rfpDocument) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.cpmName = cpmName;
		this.createdByName = createdByName;
		this.operationalManagerName = operationalManagerName;
		this.projectType = projectType;
		this.serviceArea = serviceArea;
		this.opportunityName = opportunityName;
		this.opportunityCode = opportunityCode;
		this.countryName = countryName;
		this.customerName = customerName;
		this.marketAreaName = marketAreaName;
		this.companyName = companyName;
		this.cpm = cpm;
		this.projectCreator = projectCreator;
		this.startDate = startDate;
		this.enddate = enddate;
		this.projectDescription = projectDescription;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.status = status;
		this.operationalManager = operationalManager;
		this.isDeleted = isDeleted;
		this.approvedWlaDocument = approvedWlaDocument;
		this.mailReference = mailReference;
		this.others = others;
		this.rfpDocument = rfpDocument;
	}

	@Column(name = "PRojectID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ProjectName")
	public Serializable getProjectName() {
		return this.projectName;
	}

	public void setProjectName(Serializable projectName) {
		this.projectName = projectName;
	}

	@Column(name = "CpmName", length = 250)
	public String getCpmName() {
		return this.cpmName;
	}

	public void setCpmName(String cpmName) {
		this.cpmName = cpmName;
	}

	@Column(name = "CreatedByName", length = 500)
	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	@Column(name = "OperationalManagerName", length = 500)
	public String getOperationalManagerName() {
		return this.operationalManagerName;
	}

	public void setOperationalManagerName(String operationalManagerName) {
		this.operationalManagerName = operationalManagerName;
	}

	@Column(name = "ProjectType")
	public Serializable getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Serializable projectType) {
		this.projectType = projectType;
	}

	@Column(name = "ServiceArea", length = 128)
	public String getServiceArea() {
		return this.serviceArea;
	}

	public void setServiceArea(String serviceArea) {
		this.serviceArea = serviceArea;
	}

	@Column(name = "OpportunityName")
	public Serializable getOpportunityName() {
		return this.opportunityName;
	}

	public void setOpportunityName(Serializable opportunityName) {
		this.opportunityName = opportunityName;
	}

	@Column(name = "OpportunityCode", length = 100)
	public String getOpportunityCode() {
		return this.opportunityCode;
	}

	public void setOpportunityCode(String opportunityCode) {
		this.opportunityCode = opportunityCode;
	}

	@Column(name = "CountryName")
	public Serializable getCountryName() {
		return this.countryName;
	}

	public void setCountryName(Serializable countryName) {
		this.countryName = countryName;
	}

	@Column(name = "CustomerName")
	public Serializable getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(Serializable customerName) {
		this.customerName = customerName;
	}

	@Column(name = "MarketAreaName")
	public Serializable getMarketAreaName() {
		return this.marketAreaName;
	}

	public void setMarketAreaName(Serializable marketAreaName) {
		this.marketAreaName = marketAreaName;
	}

	@Column(name = "CompanyName")
	public Serializable getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(Serializable companyName) {
		this.companyName = companyName;
	}

	@Column(name = "CPM")
	public Serializable getCpm() {
		return this.cpm;
	}

	public void setCpm(Serializable cpm) {
		this.cpm = cpm;
	}

	@Column(name = "ProjectCreator")
	public Serializable getProjectCreator() {
		return this.projectCreator;
	}

	public void setProjectCreator(Serializable projectCreator) {
		this.projectCreator = projectCreator;
	}

	@Column(name = "StartDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "Enddate", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "ProjectDescription")
	public Serializable getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(Serializable projectDescription) {
		this.projectDescription = projectDescription;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "OperationalManager")
	public Serializable getOperationalManager() {
		return this.operationalManager;
	}

	public void setOperationalManager(Serializable operationalManager) {
		this.operationalManager = operationalManager;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "Approved WLA Document")
	public Integer getApprovedWlaDocument() {
		return this.approvedWlaDocument;
	}

	public void setApprovedWlaDocument(Integer approvedWlaDocument) {
		this.approvedWlaDocument = approvedWlaDocument;
	}

	@Column(name = "Mail Reference")
	public Integer getMailReference() {
		return this.mailReference;
	}

	public void setMailReference(Integer mailReference) {
		this.mailReference = mailReference;
	}

	@Column(name = "Others")
	public Integer getOthers() {
		return this.others;
	}

	public void setOthers(Integer others) {
		this.others = others;
	}

	@Column(name = "RFP Document")
	public Integer getRfpDocument() {
		return this.rfpDocument;
	}

	public void setRfpDocument(Integer rfpDocument) {
		this.rfpDocument = rfpDocument;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwProjectDetailsId))
			return false;
		VwProjectDetailsId castOther = (VwProjectDetailsId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& ((this.getProjectName() == castOther.getProjectName())
						|| (this.getProjectName() != null && castOther.getProjectName() != null
								&& this.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getCpmName() == castOther.getCpmName()) || (this.getCpmName() != null
						&& castOther.getCpmName() != null && this.getCpmName().equals(castOther.getCpmName())))
				&& ((this.getCreatedByName() == castOther.getCreatedByName())
						|| (this.getCreatedByName() != null && castOther.getCreatedByName() != null
								&& this.getCreatedByName().equals(castOther.getCreatedByName())))
				&& ((this.getOperationalManagerName() == castOther.getOperationalManagerName())
						|| (this.getOperationalManagerName() != null && castOther.getOperationalManagerName() != null
								&& this.getOperationalManagerName().equals(castOther.getOperationalManagerName())))
				&& ((this.getProjectType() == castOther.getProjectType())
						|| (this.getProjectType() != null && castOther.getProjectType() != null
								&& this.getProjectType().equals(castOther.getProjectType())))
				&& ((this.getServiceArea() == castOther.getServiceArea())
						|| (this.getServiceArea() != null && castOther.getServiceArea() != null
								&& this.getServiceArea().equals(castOther.getServiceArea())))
				&& ((this.getOpportunityName() == castOther.getOpportunityName())
						|| (this.getOpportunityName() != null && castOther.getOpportunityName() != null
								&& this.getOpportunityName().equals(castOther.getOpportunityName())))
				&& ((this.getOpportunityCode() == castOther.getOpportunityCode())
						|| (this.getOpportunityCode() != null && castOther.getOpportunityCode() != null
								&& this.getOpportunityCode().equals(castOther.getOpportunityCode())))
				&& ((this.getCountryName() == castOther.getCountryName())
						|| (this.getCountryName() != null && castOther.getCountryName() != null
								&& this.getCountryName().equals(castOther.getCountryName())))
				&& ((this.getCustomerName() == castOther.getCustomerName())
						|| (this.getCustomerName() != null && castOther.getCustomerName() != null
								&& this.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getMarketAreaName() == castOther.getMarketAreaName())
						|| (this.getMarketAreaName() != null && castOther.getMarketAreaName() != null
								&& this.getMarketAreaName().equals(castOther.getMarketAreaName())))
				&& ((this.getCompanyName() == castOther.getCompanyName())
						|| (this.getCompanyName() != null && castOther.getCompanyName() != null
								&& this.getCompanyName().equals(castOther.getCompanyName())))
				&& ((this.getCpm() == castOther.getCpm()) || (this.getCpm() != null && castOther.getCpm() != null
						&& this.getCpm().equals(castOther.getCpm())))
				&& ((this.getProjectCreator() == castOther.getProjectCreator())
						|| (this.getProjectCreator() != null && castOther.getProjectCreator() != null
								&& this.getProjectCreator().equals(castOther.getProjectCreator())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this.getStartDate() != null
						&& castOther.getStartDate() != null && this.getStartDate().equals(castOther.getStartDate())))
				&& ((this.getEnddate() == castOther.getEnddate()) || (this.getEnddate() != null
						&& castOther.getEnddate() != null && this.getEnddate().equals(castOther.getEnddate())))
				&& ((this.getProjectDescription() == castOther.getProjectDescription())
						|| (this.getProjectDescription() != null && castOther.getProjectDescription() != null
								&& this.getProjectDescription().equals(castOther.getProjectDescription())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getOperationalManager() == castOther.getOperationalManager())
						|| (this.getOperationalManager() != null && castOther.getOperationalManager() != null
								&& this.getOperationalManager().equals(castOther.getOperationalManager())))
				&& ((this.getIsDeleted() == castOther.getIsDeleted()) || (this.getIsDeleted() != null
						&& castOther.getIsDeleted() != null && this.getIsDeleted().equals(castOther.getIsDeleted())))
				&& ((this.getApprovedWlaDocument() == castOther.getApprovedWlaDocument())
						|| (this.getApprovedWlaDocument() != null && castOther.getApprovedWlaDocument() != null
								&& this.getApprovedWlaDocument().equals(castOther.getApprovedWlaDocument())))
				&& ((this.getMailReference() == castOther.getMailReference())
						|| (this.getMailReference() != null && castOther.getMailReference() != null
								&& this.getMailReference().equals(castOther.getMailReference())))
				&& ((this.getOthers() == castOther.getOthers()) || (this.getOthers() != null
						&& castOther.getOthers() != null && this.getOthers().equals(castOther.getOthers())))
				&& ((this.getRfpDocument() == castOther.getRfpDocument())
						|| (this.getRfpDocument() != null && castOther.getRfpDocument() != null
								&& this.getRfpDocument().equals(castOther.getRfpDocument())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + (getCpmName() == null ? 0 : this.getCpmName().hashCode());
		result = 37 * result + (getCreatedByName() == null ? 0 : this.getCreatedByName().hashCode());
		result = 37 * result + (getOperationalManagerName() == null ? 0 : this.getOperationalManagerName().hashCode());
		result = 37 * result + (getProjectType() == null ? 0 : this.getProjectType().hashCode());
		result = 37 * result + (getServiceArea() == null ? 0 : this.getServiceArea().hashCode());
		result = 37 * result + (getOpportunityName() == null ? 0 : this.getOpportunityName().hashCode());
		result = 37 * result + (getOpportunityCode() == null ? 0 : this.getOpportunityCode().hashCode());
		result = 37 * result + (getCountryName() == null ? 0 : this.getCountryName().hashCode());
		result = 37 * result + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
		result = 37 * result + (getMarketAreaName() == null ? 0 : this.getMarketAreaName().hashCode());
		result = 37 * result + (getCompanyName() == null ? 0 : this.getCompanyName().hashCode());
		result = 37 * result + (getCpm() == null ? 0 : this.getCpm().hashCode());
		result = 37 * result + (getProjectCreator() == null ? 0 : this.getProjectCreator().hashCode());
		result = 37 * result + (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37 * result + (getEnddate() == null ? 0 : this.getEnddate().hashCode());
		result = 37 * result + (getProjectDescription() == null ? 0 : this.getProjectDescription().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getOperationalManager() == null ? 0 : this.getOperationalManager().hashCode());
		result = 37 * result + (getIsDeleted() == null ? 0 : this.getIsDeleted().hashCode());
		result = 37 * result + (getApprovedWlaDocument() == null ? 0 : this.getApprovedWlaDocument().hashCode());
		result = 37 * result + (getMailReference() == null ? 0 : this.getMailReference().hashCode());
		result = 37 * result + (getOthers() == null ? 0 : this.getOthers().hashCode());
		result = 37 * result + (getRfpDocument() == null ? 0 : this.getRfpDocument().hashCode());
		return result;
	}

}
