package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwProjectWos generated by hbm2java
 */
@Entity
@Table(name = "vw_Project_WOs", schema = "dbo")
public class VwProjectWos implements java.io.Serializable {

	private VwProjectWosId id;

	public VwProjectWos() {
	}

	public VwProjectWos(VwProjectWosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "woplanId", column = @Column(name = "WOPlanID")),
			@AttributeOverride(name = "adhocWoid", column = @Column(name = "AdhocWOID")),
			@AttributeOverride(name = "woname", column = @Column(name = "WOName")),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", length = 1024)),
			@AttributeOverride(name = "priority", column = @Column(name = "Priority", length = 1024)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID", nullable = false)),
			@AttributeOverride(name = "plannedStartDate", column = @Column(name = "PlannedStartDate", length = 23)),
			@AttributeOverride(name = "plannedEndDate", column = @Column(name = "PlannedEndDate", length = 23)),
			@AttributeOverride(name = "actualStartDate", column = @Column(name = "ActualStartDate", length = 23)),
			@AttributeOverride(name = "actualEndDate", column = @Column(name = "ActualEndDate", length = 23)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", length = 512)),
			@AttributeOverride(name = "closedOn", column = @Column(name = "ClosedOn", length = 23)),
			@AttributeOverride(name = "signumId", column = @Column(name = "SignumID", length = 1024)),
			@AttributeOverride(name = "lastModifiedBy", column = @Column(name = "LastModifiedBy", length = 1024)),
			@AttributeOverride(name = "deliveryStatus", column = @Column(name = "DeliveryStatus", length = 1024)),
			@AttributeOverride(name = "failureReason", column = @Column(name = "FailureReason", length = 1024)),
			@AttributeOverride(name = "description", column = @Column(name = "Description", length = 1024)),
			@AttributeOverride(name = "statusComment", column = @Column(name = "StatusComment")),
			@AttributeOverride(name = "parentWorkOrderId", column = @Column(name = "ParentWorkOrderID")),
			@AttributeOverride(name = "woNodeType", column = @Column(name = "WO NodeType", length = 512)),
			@AttributeOverride(name = "woNodeNames", column = @Column(name = "WO NodeNames")) })
	public VwProjectWosId getId() {
		return this.id;
	}

	public void setId(VwProjectWosId id) {
		this.id = id;
	}

}
