package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwProjectScope generated by hbm2java
 */
@Entity
@Table(name = "Vw_ProjectScope", schema = "dbo")
public class VwProjectScope implements java.io.Serializable {

	private VwProjectScopeId id;

	public VwProjectScope() {
	}

	public VwProjectScope(VwProjectScopeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "projectScopeId", column = @Column(name = "ProjectScopeID")),
			@AttributeOverride(name = "scopeName", column = @Column(name = "ScopeName")),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID", nullable = false)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "servareaId", column = @Column(name = "servareaID")),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "serviceAreaId", column = @Column(name = "ServiceAreaID", nullable = false)),
			@AttributeOverride(name = "subservicearea", column = @Column(name = "Subservicearea", length = 128)),
			@AttributeOverride(name = "technologyid", column = @Column(name = "technologyid", nullable = false)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "activityScopeId", column = @Column(name = "ActivityScopeID", nullable = false)),
			@AttributeOverride(name = "activity", column = @Column(name = "Activity", length = 512)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID")),
			@AttributeOverride(name = "subActivity", column = @Column(name = "SubActivity", length = 512)),
			@AttributeOverride(name = "avgEstdEffort", column = @Column(name = "AvgEstdEffort", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", nullable = false, length = 23)),
			@AttributeOverride(name = "createdby", column = @Column(name = "Createdby", length = 256)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", length = 23)),
			@AttributeOverride(name = "active", column = @Column(name = "Active")),
			@AttributeOverride(name = "requestType", column = @Column(name = "RequestType", nullable = false, length = 100)) })
	public VwProjectScopeId getId() {
		return this.id;
	}

	public void setId(VwProjectScopeId id) {
		this.id = id;
	}

}
