package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwProjectDemad generated by hbm2java
 */
@Entity
@Table(name = "vw_ProjectDemad", schema = "dbo")
public class VwProjectDemad implements java.io.Serializable {

	private VwProjectDemadId id;

	public VwProjectDemad() {
	}

	public VwProjectDemad(VwProjectDemadId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "resourceRequestId", column = @Column(name = "ResourceRequestID", nullable = false)),
			@AttributeOverride(name = "resourceType", column = @Column(name = "ResourceType")),
			@AttributeOverride(name = "requestType", column = @Column(name = "RequestType")),
			@AttributeOverride(name = "onsiteCount", column = @Column(name = "OnsiteCount", nullable = false)),
			@AttributeOverride(name = "remoteCount", column = @Column(name = "RemoteCount", nullable = false)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy")),
			@AttributeOverride(name = "jobRoleId", column = @Column(name = "JobRoleID")),
			@AttributeOverride(name = "jobStageId", column = @Column(name = "JobStageID")),
			@AttributeOverride(name = "onsiteLocationId", column = @Column(name = "OnsiteLocationID")),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "active", column = @Column(name = "active")),
			@AttributeOverride(name = "resourceDescription", column = @Column(name = "ResourceDescription")),
			@AttributeOverride(name = "onsiteLocation", column = @Column(name = "OnsiteLocation")),
			@AttributeOverride(name = "remoteLocation", column = @Column(name = "RemoteLocation")),
			@AttributeOverride(name = "city", column = @Column(name = "City")),
			@AttributeOverride(name = "country", column = @Column(name = "Country")),
			@AttributeOverride(name = "latitude", column = @Column(name = "Latitude", precision = 53, scale = 0)),
			@AttributeOverride(name = "longitude", column = @Column(name = "Longitude", precision = 53, scale = 0)),
			@AttributeOverride(name = "timeZone", column = @Column(name = "TimeZone")),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", nullable = false, length = 23)),
			@AttributeOverride(name = "duration", column = @Column(name = "Duration", nullable = false)),
			@AttributeOverride(name = "ftepercent", column = @Column(name = "FTEPercent", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "domainId", column = @Column(name = "DomainID", nullable = false)),
			@AttributeOverride(name = "technologyId", column = @Column(name = "TechnologyID", nullable = false)),
			@AttributeOverride(name = "serviceAreaId", column = @Column(name = "ServiceAreaID", nullable = false)),
			@AttributeOverride(name = "projectScopeId", column = @Column(name = "ProjectScopeID")) })
	public VwProjectDemadId getId() {
		return this.id;
	}

	public void setId(VwProjectDemadId id) {
		this.id = id;
	}

}
