package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwProjectScopeIssue generated by hbm2java
 */
@Entity
@Table(name = "vw_ProjectScopeISSue", schema = "dbo")
public class VwProjectScopeIssue implements java.io.Serializable {

	private VwProjectScopeIssueId id;

	public VwProjectScopeIssue() {
	}

	public VwProjectScopeIssue(VwProjectScopeIssueId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "projectScopeId", column = @Column(name = "ProjectScopeID")),
			@AttributeOverride(name = "scopeName", column = @Column(name = "ScopeName")),
			@AttributeOverride(name = "projectScopeActive", column = @Column(name = "ProjectScopeActive")),
			@AttributeOverride(name = "projectScopeDetailId", column = @Column(name = "ProjectScopeDetailID")),
			@AttributeOverride(name = "projectScopeDetailActive", column = @Column(name = "ProjectScopeDetailActive")),
			@AttributeOverride(name = "activityScopeId", column = @Column(name = "ActivityScopeID")),
			@AttributeOverride(name = "activityScopeActive", column = @Column(name = "ActivityScopeActive")) })
	public VwProjectScopeIssueId getId() {
		return this.id;
	}

	public void setId(VwProjectScopeIssueId id) {
		this.id = id;
	}

}
