package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwProjectDemandFulfillment generated by hbm2java
 */
@Entity
@Table(name = "vw_ProjectDemandFulfillment", schema = "dbo")
public class VwProjectDemandFulfillment implements java.io.Serializable {

	private VwProjectDemandFulfillmentId id;

	public VwProjectDemandFulfillment() {
	}

	public VwProjectDemandFulfillment(VwProjectDemandFulfillmentId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "marketAreaId", column = @Column(name = "MarketAreaID")),
			@AttributeOverride(name = "marketAreaName", column = @Column(name = "MarketAreaName")),
			@AttributeOverride(name = "resourcePositionId", column = @Column(name = "ResourcePositionID", nullable = false)),
			@AttributeOverride(name = "workEffortId", column = @Column(name = "WorkEffortID", nullable = false)),
			@AttributeOverride(name = "workEffortStatus", column = @Column(name = "WorkEffortStatus", length = 100)),
			@AttributeOverride(name = "positionStatus", column = @Column(name = "PositionStatus", length = 100)),
			@AttributeOverride(name = "hours", column = @Column(name = "Hours", precision = 53, scale = 0)),
			@AttributeOverride(name = "signum", column = @Column(name = "Signum", length = 8)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate")),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate")),
			@AttributeOverride(name = "fte", column = @Column(name = "FTE", precision = 53, scale = 0)),
			@AttributeOverride(name = "jobStage", column = @Column(name = "JobStage", length = 50)),
			@AttributeOverride(name = "managerName", column = @Column(name = "ManagerName", length = 500)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 128)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "managerSignum", column = @Column(name = "ManagerSignum", length = 8)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "subServiceArea", column = @Column(name = "SubServiceArea", length = 128)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "employeeName", column = @Column(name = "EmployeeName", length = 500)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "positionStartDate", column = @Column(name = "PositionStartDate")),
			@AttributeOverride(name = "positionEndDate", column = @Column(name = "PositionEndDate")),
			@AttributeOverride(name = "crid", column = @Column(name = "CRID")),
			@AttributeOverride(name = "isPendingCr", column = @Column(name = "IsPendingCR", nullable = false)) })
	public VwProjectDemandFulfillmentId getId() {
		return this.id;
	}

	public void setId(VwProjectDemandFulfillmentId id) {
		this.id = id;
	}

}
