package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwRampDownReort generated by hbm2java
 */
@Entity
@Table(name = "vw_RampDown_Reort", schema = "dbo")
public class VwRampDownReort implements java.io.Serializable {

	private VwRampDownReortId id;

	public VwRampDownReort() {
	}

	public VwRampDownReort(VwRampDownReortId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resourcePositionId", column = @Column(name = "ResourcePositionID", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID")),
			@AttributeOverride(name = "projectName", column = @Column(name = "ProjectName")),
			@AttributeOverride(name = "projectStartDate", column = @Column(name = "ProjectStartDate", length = 23)),
			@AttributeOverride(name = "projectEndDate", column = @Column(name = "ProjectEndDate", length = 23)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 128)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 128)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "serviceArea", column = @Column(name = "ServiceArea", length = 128)),
			@AttributeOverride(name = "subServiceArea", column = @Column(name = "SubServiceArea", length = 128)),
			@AttributeOverride(name = "positionStatus", column = @Column(name = "PositionStatus", length = 100)),
			@AttributeOverride(name = "signum", column = @Column(name = "Signum", length = 8)),
			@AttributeOverride(name = "employeeName", column = @Column(name = "EmployeeName", nullable = false, length = 500)),
			@AttributeOverride(name = "personnelNumber", column = @Column(name = "PersonnelNumber", nullable = false)),
			@AttributeOverride(name = "workEffortId", column = @Column(name = "WorkEffortID", nullable = false)),
			@AttributeOverride(name = "managerSignum", column = @Column(name = "ManagerSignum", length = 8)),
			@AttributeOverride(name = "positionStartDate", column = @Column(name = "PositionStartDate", nullable = false, length = 10)),
			@AttributeOverride(name = "positionEndDate", column = @Column(name = "PositionEndDate", nullable = false, length = 10)),
			@AttributeOverride(name = "rampDownWeek", column = @Column(name = "RampDownWeek", length = 9)),
			@AttributeOverride(name = "rampDownYear", column = @Column(name = "RampDownYear")),
			@AttributeOverride(name = "certificateName", column = @Column(name = "CertificateName", nullable = false)),
			@AttributeOverride(name = "region", column = @Column(name = "Region")),
			@AttributeOverride(name = "marketArea", column = @Column(name = "MarketArea")),
			@AttributeOverride(name = "marketAreaRegion", column = @Column(name = "MarketAreaRegion")),
			@AttributeOverride(name = "countryName", column = @Column(name = "CountryName")),
			@AttributeOverride(name = "orgUnit", column = @Column(name = "ORG_UNIT", length = 128)) })
	public VwRampDownReortId getId() {
		return this.id;
	}

	public void setId(VwRampDownReortId id) {
		this.id = id;
	}

}
