package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwWoplanIssueId generated by hbm2java
 */
@Embeddable
public class VwWoplanIssueId implements java.io.Serializable {

	private int projectId;
	private Integer isDeleted;
	private Serializable status;
	private int woplanId;
	private Boolean wopActive;
	private int woid;
	private Boolean woActive;

	public VwWoplanIssueId() {
	}

	public VwWoplanIssueId(int projectId, int woplanId, int woid) {
		this.projectId = projectId;
		this.woplanId = woplanId;
		this.woid = woid;
	}

	public VwWoplanIssueId(int projectId, Integer isDeleted, Serializable status, int woplanId, Boolean wopActive,
			int woid, Boolean woActive) {
		this.projectId = projectId;
		this.isDeleted = isDeleted;
		this.status = status;
		this.woplanId = woplanId;
		this.wopActive = wopActive;
		this.woid = woid;
		this.woActive = woActive;
	}

	@Column(name = "ProjectID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "WOPlanID", nullable = false)
	public int getWoplanId() {
		return this.woplanId;
	}

	public void setWoplanId(int woplanId) {
		this.woplanId = woplanId;
	}

	@Column(name = "WOP Active")
	public Boolean getWopActive() {
		return this.wopActive;
	}

	public void setWopActive(Boolean wopActive) {
		this.wopActive = wopActive;
	}

	@Column(name = "WOID", nullable = false)
	public int getWoid() {
		return this.woid;
	}

	public void setWoid(int woid) {
		this.woid = woid;
	}

	@Column(name = "WO Active")
	public Boolean getWoActive() {
		return this.woActive;
	}

	public void setWoActive(Boolean woActive) {
		this.woActive = woActive;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwWoplanIssueId))
			return false;
		VwWoplanIssueId castOther = (VwWoplanIssueId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& ((this.getIsDeleted() == castOther.getIsDeleted()) || (this.getIsDeleted() != null
						&& castOther.getIsDeleted() != null && this.getIsDeleted().equals(castOther.getIsDeleted())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& (this.getWoplanId() == castOther.getWoplanId())
				&& ((this.getWopActive() == castOther.getWopActive()) || (this.getWopActive() != null
						&& castOther.getWopActive() != null && this.getWopActive().equals(castOther.getWopActive())))
				&& (this.getWoid() == castOther.getWoid())
				&& ((this.getWoActive() == castOther.getWoActive()) || (this.getWoActive() != null
						&& castOther.getWoActive() != null && this.getWoActive().equals(castOther.getWoActive())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + (getIsDeleted() == null ? 0 : this.getIsDeleted().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + this.getWoplanId();
		result = 37 * result + (getWopActive() == null ? 0 : this.getWopActive().hashCode());
		result = 37 * result + this.getWoid();
		result = 37 * result + (getWoActive() == null ? 0 : this.getWoActive().hashCode());
		return result;
	}

}
