package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwWorkFlowStepId generated by hbm2java
 */
@Embeddable
public class VwWorkFlowStepId implements java.io.Serializable {

	private String marketAreaName;
	private String countryName;
	private String customerName;
	private String countryId;
	private String serviceArea;
	private String projectName;
	private String projectId;
	private String subActivityId;
	private String domain;
	private String subDomain;
	private String subServiceArea;
	private String technology;
	private String activity;
	private String subActivity;
	private String subActivityFlowChartDefId;
	private String taskId;
	private String task;
	private String fcstepId;
	private String executionType;
	private String toolId;
	private String tool;
	private String versionNumber;
	private String workFlowName;
	private String stepName;
	private String avgEstdEffort;

	public VwWorkFlowStepId() {
	}

	public VwWorkFlowStepId(String marketAreaName, String countryName, String customerName, String countryId,
			String serviceArea, String projectName, String projectId, String subActivityId, String domain,
			String subDomain, String subServiceArea, String technology, String activity, String subActivity,
			String subActivityFlowChartDefId, String taskId, String task, String fcstepId, String executionType,
			String toolId, String tool, String versionNumber, String workFlowName, String stepName,
			String avgEstdEffort) {
		this.marketAreaName = marketAreaName;
		this.countryName = countryName;
		this.customerName = customerName;
		this.countryId = countryId;
		this.serviceArea = serviceArea;
		this.projectName = projectName;
		this.projectId = projectId;
		this.subActivityId = subActivityId;
		this.domain = domain;
		this.subDomain = subDomain;
		this.subServiceArea = subServiceArea;
		this.technology = technology;
		this.activity = activity;
		this.subActivity = subActivity;
		this.subActivityFlowChartDefId = subActivityFlowChartDefId;
		this.taskId = taskId;
		this.task = task;
		this.fcstepId = fcstepId;
		this.executionType = executionType;
		this.toolId = toolId;
		this.tool = tool;
		this.versionNumber = versionNumber;
		this.workFlowName = workFlowName;
		this.stepName = stepName;
		this.avgEstdEffort = avgEstdEffort;
	}

	@Column(name = "MarketAreaName", length = 20)
	public String getMarketAreaName() {
		return this.marketAreaName;
	}

	public void setMarketAreaName(String marketAreaName) {
		this.marketAreaName = marketAreaName;
	}

	@Column(name = "CountryName", length = 250)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "CustomerName", length = 200)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "CountryID", length = 10)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "ServiceArea", length = 128)
	public String getServiceArea() {
		return this.serviceArea;
	}

	public void setServiceArea(String serviceArea) {
		this.serviceArea = serviceArea;
	}

	@Column(name = "ProjectName", length = 250)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "ProjectID", length = 10)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "SubActivityID", length = 13)
	public String getSubActivityId() {
		return this.subActivityId;
	}

	public void setSubActivityId(String subActivityId) {
		this.subActivityId = subActivityId;
	}

	@Column(name = "Domain", length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "SubDomain", length = 128)
	public String getSubDomain() {
		return this.subDomain;
	}

	public void setSubDomain(String subDomain) {
		this.subDomain = subDomain;
	}

	@Column(name = "SubServiceArea", length = 128)
	public String getSubServiceArea() {
		return this.subServiceArea;
	}

	public void setSubServiceArea(String subServiceArea) {
		this.subServiceArea = subServiceArea;
	}

	@Column(name = "Technology", length = 128)
	public String getTechnology() {
		return this.technology;
	}

	public void setTechnology(String technology) {
		this.technology = technology;
	}

	@Column(name = "Activity", length = 512)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "SubActivity", length = 512)
	public String getSubActivity() {
		return this.subActivity;
	}

	public void setSubActivity(String subActivity) {
		this.subActivity = subActivity;
	}

	@Column(name = "SubActivityFlowChartDefID", length = 25)
	public String getSubActivityFlowChartDefId() {
		return this.subActivityFlowChartDefId;
	}

	public void setSubActivityFlowChartDefId(String subActivityFlowChartDefId) {
		this.subActivityFlowChartDefId = subActivityFlowChartDefId;
	}

	@Column(name = "TaskID", length = 10)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "Task", length = 500)
	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	@Column(name = "FCStepID", length = 10)
	public String getFcstepId() {
		return this.fcstepId;
	}

	public void setFcstepId(String fcstepId) {
		this.fcstepId = fcstepId;
	}

	@Column(name = "ExecutionType", length = 20)
	public String getExecutionType() {
		return this.executionType;
	}

	public void setExecutionType(String executionType) {
		this.executionType = executionType;
	}

	@Column(name = "ToolID", length = 10)
	public String getToolId() {
		return this.toolId;
	}

	public void setToolId(String toolId) {
		this.toolId = toolId;
	}

	@Column(name = "Tool", length = 128)
	public String getTool() {
		return this.tool;
	}

	public void setTool(String tool) {
		this.tool = tool;
	}

	@Column(name = "VersionNumber", length = 13)
	public String getVersionNumber() {
		return this.versionNumber;
	}

	public void setVersionNumber(String versionNumber) {
		this.versionNumber = versionNumber;
	}

	@Column(name = "WorkFlowName")
	public String getWorkFlowName() {
		return this.workFlowName;
	}

	public void setWorkFlowName(String workFlowName) {
		this.workFlowName = workFlowName;
	}

	@Column(name = "StepName", length = 1024)
	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	@Column(name = "AvgEstdEffort", length = 13)
	public String getAvgEstdEffort() {
		return this.avgEstdEffort;
	}

	public void setAvgEstdEffort(String avgEstdEffort) {
		this.avgEstdEffort = avgEstdEffort;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwWorkFlowStepId))
			return false;
		VwWorkFlowStepId castOther = (VwWorkFlowStepId) other;

		return ((this.getMarketAreaName() == castOther.getMarketAreaName())
				|| (this.getMarketAreaName() != null && castOther.getMarketAreaName() != null
						&& this.getMarketAreaName().equals(castOther.getMarketAreaName())))
				&& ((this.getCountryName() == castOther.getCountryName())
						|| (this.getCountryName() != null && castOther.getCountryName() != null
								&& this.getCountryName().equals(castOther.getCountryName())))
				&& ((this.getCustomerName() == castOther.getCustomerName())
						|| (this.getCustomerName() != null && castOther.getCustomerName() != null
								&& this.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getCountryId() == castOther.getCountryId()) || (this.getCountryId() != null
						&& castOther.getCountryId() != null && this.getCountryId().equals(castOther.getCountryId())))
				&& ((this.getServiceArea() == castOther.getServiceArea())
						|| (this.getServiceArea() != null && castOther.getServiceArea() != null
								&& this.getServiceArea().equals(castOther.getServiceArea())))
				&& ((this.getProjectName() == castOther.getProjectName())
						|| (this.getProjectName() != null && castOther.getProjectName() != null
								&& this.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getSubActivityId() == castOther.getSubActivityId())
						|| (this.getSubActivityId() != null && castOther.getSubActivityId() != null
								&& this.getSubActivityId().equals(castOther.getSubActivityId())))
				&& ((this.getDomain() == castOther.getDomain()) || (this.getDomain() != null
						&& castOther.getDomain() != null && this.getDomain().equals(castOther.getDomain())))
				&& ((this.getSubDomain() == castOther.getSubDomain()) || (this.getSubDomain() != null
						&& castOther.getSubDomain() != null && this.getSubDomain().equals(castOther.getSubDomain())))
				&& ((this.getSubServiceArea() == castOther.getSubServiceArea())
						|| (this.getSubServiceArea() != null && castOther.getSubServiceArea() != null
								&& this.getSubServiceArea().equals(castOther.getSubServiceArea())))
				&& ((this.getTechnology() == castOther.getTechnology()) || (this.getTechnology() != null
						&& castOther.getTechnology() != null && this.getTechnology().equals(castOther.getTechnology())))
				&& ((this.getActivity() == castOther.getActivity()) || (this.getActivity() != null
						&& castOther.getActivity() != null && this.getActivity().equals(castOther.getActivity())))
				&& ((this.getSubActivity() == castOther.getSubActivity())
						|| (this.getSubActivity() != null && castOther.getSubActivity() != null
								&& this.getSubActivity().equals(castOther.getSubActivity())))
				&& ((this.getSubActivityFlowChartDefId() == castOther.getSubActivityFlowChartDefId())
						|| (this.getSubActivityFlowChartDefId() != null
								&& castOther.getSubActivityFlowChartDefId() != null
								&& this.getSubActivityFlowChartDefId()
										.equals(castOther.getSubActivityFlowChartDefId())))
				&& ((this.getTaskId() == castOther.getTaskId()) || (this.getTaskId() != null
						&& castOther.getTaskId() != null && this.getTaskId().equals(castOther.getTaskId())))
				&& ((this.getTask() == castOther.getTask()) || (this.getTask() != null && castOther.getTask() != null
						&& this.getTask().equals(castOther.getTask())))
				&& ((this.getFcstepId() == castOther.getFcstepId()) || (this.getFcstepId() != null
						&& castOther.getFcstepId() != null && this.getFcstepId().equals(castOther.getFcstepId())))
				&& ((this.getExecutionType() == castOther.getExecutionType())
						|| (this.getExecutionType() != null && castOther.getExecutionType() != null
								&& this.getExecutionType().equals(castOther.getExecutionType())))
				&& ((this.getToolId() == castOther.getToolId()) || (this.getToolId() != null
						&& castOther.getToolId() != null && this.getToolId().equals(castOther.getToolId())))
				&& ((this.getTool() == castOther.getTool()) || (this.getTool() != null && castOther.getTool() != null
						&& this.getTool().equals(castOther.getTool())))
				&& ((this.getVersionNumber() == castOther.getVersionNumber())
						|| (this.getVersionNumber() != null && castOther.getVersionNumber() != null
								&& this.getVersionNumber().equals(castOther.getVersionNumber())))
				&& ((this.getWorkFlowName() == castOther.getWorkFlowName())
						|| (this.getWorkFlowName() != null && castOther.getWorkFlowName() != null
								&& this.getWorkFlowName().equals(castOther.getWorkFlowName())))
				&& ((this.getStepName() == castOther.getStepName()) || (this.getStepName() != null
						&& castOther.getStepName() != null && this.getStepName().equals(castOther.getStepName())))
				&& ((this.getAvgEstdEffort() == castOther.getAvgEstdEffort())
						|| (this.getAvgEstdEffort() != null && castOther.getAvgEstdEffort() != null
								&& this.getAvgEstdEffort().equals(castOther.getAvgEstdEffort())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMarketAreaName() == null ? 0 : this.getMarketAreaName().hashCode());
		result = 37 * result + (getCountryName() == null ? 0 : this.getCountryName().hashCode());
		result = 37 * result + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
		result = 37 * result + (getCountryId() == null ? 0 : this.getCountryId().hashCode());
		result = 37 * result + (getServiceArea() == null ? 0 : this.getServiceArea().hashCode());
		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getSubActivityId() == null ? 0 : this.getSubActivityId().hashCode());
		result = 37 * result + (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result + (getSubDomain() == null ? 0 : this.getSubDomain().hashCode());
		result = 37 * result + (getSubServiceArea() == null ? 0 : this.getSubServiceArea().hashCode());
		result = 37 * result + (getTechnology() == null ? 0 : this.getTechnology().hashCode());
		result = 37 * result + (getActivity() == null ? 0 : this.getActivity().hashCode());
		result = 37 * result + (getSubActivity() == null ? 0 : this.getSubActivity().hashCode());
		result = 37 * result
				+ (getSubActivityFlowChartDefId() == null ? 0 : this.getSubActivityFlowChartDefId().hashCode());
		result = 37 * result + (getTaskId() == null ? 0 : this.getTaskId().hashCode());
		result = 37 * result + (getTask() == null ? 0 : this.getTask().hashCode());
		result = 37 * result + (getFcstepId() == null ? 0 : this.getFcstepId().hashCode());
		result = 37 * result + (getExecutionType() == null ? 0 : this.getExecutionType().hashCode());
		result = 37 * result + (getToolId() == null ? 0 : this.getToolId().hashCode());
		result = 37 * result + (getTool() == null ? 0 : this.getTool().hashCode());
		result = 37 * result + (getVersionNumber() == null ? 0 : this.getVersionNumber().hashCode());
		result = 37 * result + (getWorkFlowName() == null ? 0 : this.getWorkFlowName().hashCode());
		result = 37 * result + (getStepName() == null ? 0 : this.getStepName().hashCode());
		result = 37 * result + (getAvgEstdEffort() == null ? 0 : this.getAvgEstdEffort().hashCode());
		return result;
	}

}
