package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwWoplanIssue generated by hbm2java
 */
@Entity
@Table(name = "vw_WOPlanIssue", schema = "dbo")
public class VwWoplanIssue implements java.io.Serializable {

	private VwWoplanIssueId id;

	public VwWoplanIssue() {
	}

	public VwWoplanIssue(VwWoplanIssueId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "ProjectID", nullable = false)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted")),
			@AttributeOverride(name = "status", column = @Column(name = "Status")),
			@AttributeOverride(name = "woplanId", column = @Column(name = "WOPlanID", nullable = false)),
			@AttributeOverride(name = "wopActive", column = @Column(name = "WOP Active")),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID", nullable = false)),
			@AttributeOverride(name = "woActive", column = @Column(name = "WO Active")) })
	public VwWoplanIssueId getId() {
		return this.id;
	}

	public void setId(VwWoplanIssueId id) {
		this.id = id;
	}

}
