package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WorkOrderCreationTmp generated by hbm2java
 */
@Entity
@Table(name = "WorkOrderCreationTmp", schema = "dbo")
public class WorkOrderCreationTmp implements java.io.Serializable {

	private WorkOrderCreationTmpId id;

	public WorkOrderCreationTmp() {
	}

	public WorkOrderCreationTmp(WorkOrderCreationTmpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "subserviceArea", column = @Column(name = "SubserviceArea", length = 1024)),
			@AttributeOverride(name = "domain", column = @Column(name = "Domain", length = 1024)),
			@AttributeOverride(name = "subDomain", column = @Column(name = "SubDomain", length = 1024)),
			@AttributeOverride(name = "technology", column = @Column(name = "Technology", length = 128)),
			@AttributeOverride(name = "woid", column = @Column(name = "WOID", length = 100)),
			@AttributeOverride(name = "scopeName", column = @Column(name = "ScopeName", length = 1024)),
			@AttributeOverride(name = "subActivityId", column = @Column(name = "SubActivityID", length = 100)),
			@AttributeOverride(name = "subActivityName", column = @Column(name = "SubActivityName", length = 1024)),
			@AttributeOverride(name = "priority", column = @Column(name = "Priority", length = 1024)),
			@AttributeOverride(name = "slahours", column = @Column(name = "SLAHours", length = 20)),
			@AttributeOverride(name = "assignTo", column = @Column(name = "AssignTo", length = 1024)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", length = 200)),
			@AttributeOverride(name = "startTime", column = @Column(name = "StartTime", length = 200)),
			@AttributeOverride(name = "workOrderName", column = @Column(name = "WorkOrderName", length = 1024)),
			@AttributeOverride(name = "workFlowName", column = @Column(name = "WorkFlowName", length = 1024)),
			@AttributeOverride(name = "nodeType", column = @Column(name = "NodeType", length = 1024)),
			@AttributeOverride(name = "nodeNames", column = @Column(name = "NodeNames", length = 1024)),
			@AttributeOverride(name = "externalSourceId", column = @Column(name = "ExternalSourceID", length = 100)),
			@AttributeOverride(name = "externalSourceName", column = @Column(name = "ExternalSourceName", length = 1024)),
			@AttributeOverride(name = "executionPlanId", column = @Column(name = "ExecutionPlanID", length = 512)) })
	public WorkOrderCreationTmpId getId() {
		return this.id;
	}

	public void setId(WorkOrderCreationTmpId id) {
		this.id = id;
	}

}
