package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Wotfix generated by hbm2java
 */
@Entity
@Table(name = "wotfix", schema = "dbo")
public class Wotfix implements java.io.Serializable {

	private WotfixId id;

	public Wotfix() {
	}

	public Wotfix(WotfixId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "woid", column = @Column(name = "WOID")),
			@AttributeOverride(name = "bookingid", column = @Column(name = "BOOKINGID")),
			@AttributeOverride(name = "signumid", column = @Column(name = "SIGNUMID", length = 10)),
			@AttributeOverride(name = "transferedon", column = @Column(name = "TRANSFEREDON", length = 23)) })
	public WotfixId getId() {
		return this.id;
	}

	public void setId(WotfixId id) {
		this.id = id;
	}

}
