package com.ericsson.isf.model.botstore;
// Generated Jul 24, 2018 11:07:24 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * YearlyDates generated by hbm2java
 */
@Entity
@Table(name = "yearlyDates", schema = "refData")
public class YearlyDates implements java.io.Serializable {

	private Date date;

	public YearlyDates() {
	}

	public YearlyDates(Date date) {
		this.date = date;
	}

	@Id

	@Temporal(TemporalType.DATE)
	@Column(name = "_Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
